import type { NounEntry } from '../../types'

// Starter German nouns (M5). Gender is part of the word — always taught with the article.
export const DE_NOUNS: NounEntry[] = [
  { id: 'de/noun/mann', lang: 'de', lemma: 'Mann', gloss: 'man', glossPlural: 'men', glossIt: 'l’uomo', glossItPl: 'gli uomini', tags: ['human'], de: { gender: 'm', plural: 'Männer' } },
  { id: 'de/noun/frau', lang: 'de', lemma: 'Frau', gloss: 'woman', glossPlural: 'women', glossIt: 'la donna', glossItPl: 'le donne', tags: ['human'], de: { gender: 'f', plural: 'Frauen' } },
  { id: 'de/noun/kind', lang: 'de', lemma: 'Kind', gloss: 'child', glossPlural: 'children', glossIt: 'il bambino', glossItPl: 'i bambini', tags: ['human', 'family'], de: { gender: 'n', plural: 'Kinder' } },
  { id: 'de/noun/tisch', lang: 'de', lemma: 'Tisch', gloss: 'table', glossIt: 'il tavolo', glossItPl: 'i tavoli', tags: ['object'], de: { gender: 'm', plural: 'Tische' } },
  { id: 'de/noun/tür', lang: 'de', lemma: 'Tür', gloss: 'door', glossIt: 'la porta', glossItPl: 'le porte', tags: ['object'], de: { gender: 'f', plural: 'Türen' } },
  { id: 'de/noun/buch', lang: 'de', lemma: 'Buch', gloss: 'book', glossIt: 'il libro', glossItPl: 'i libri', tags: ['object'], de: { gender: 'n', plural: 'Bücher' } },
  { id: 'de/noun/haus', lang: 'de', lemma: 'Haus', gloss: 'house', glossIt: 'la casa', glossItPl: 'le case', tags: ['place'], de: { gender: 'n', plural: 'Häuser' } },
  { id: 'de/noun/stadt', lang: 'de', lemma: 'Stadt', gloss: 'city', glossIt: 'la città', glossItPl: 'le città', tags: ['place'], de: { gender: 'f', plural: 'Städte' } },
  { id: 'de/noun/wasser', lang: 'de', lemma: 'Wasser', gloss: 'water', glossIt: 'l’acqua', glossItPl: 'le acque', tags: ['drink'], de: { gender: 'n', plural: 'Wasser' } },
  { id: 'de/noun/kaffee', lang: 'de', lemma: 'Kaffee', gloss: 'coffee', glossIt: 'il caffè', glossItPl: 'i caffè', tags: ['drink'], de: { gender: 'm', plural: 'Kaffees' } },
  { id: 'de/noun/brot', lang: 'de', lemma: 'Brot', gloss: 'bread', glossIt: 'il pane', glossItPl: 'i pani', tags: ['food'], de: { gender: 'n', plural: 'Brote' } },
  { id: 'de/noun/apfel', lang: 'de', lemma: 'Apfel', gloss: 'apple', glossIt: 'la mela', glossItPl: 'le mele', tags: ['food'], de: { gender: 'm', plural: 'Äpfel' } },
  { id: 'de/noun/student', lang: 'de', lemma: 'Student', gloss: 'student', glossIt: 'lo studente', glossItPl: 'gli studenti', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Studenten', nDeclension: true } },
  { id: 'de/noun/freund', lang: 'de', lemma: 'Freund', gloss: 'friend', glossIt: 'l’amico', glossItPl: 'gli amici', tags: ['human'], de: { gender: 'm', plural: 'Freunde' } },
  // family
  { id: 'de/noun/vater', lang: 'de', lemma: 'Vater', gloss: 'father', glossIt: 'il padre', glossItPl: 'i padri', tags: ['family', 'human'], de: { gender: 'm', plural: 'Väter' } },
  { id: 'de/noun/mutter', lang: 'de', lemma: 'Mutter', gloss: 'mother', glossIt: 'la madre', glossItPl: 'le madri', tags: ['family', 'human'], de: { gender: 'f', plural: 'Mütter' } },
  { id: 'de/noun/bruder', lang: 'de', lemma: 'Bruder', gloss: 'brother', glossIt: 'il fratello', glossItPl: 'i fratelli', tags: ['family', 'human'], de: { gender: 'm', plural: 'Brüder' } },
  { id: 'de/noun/schwester', lang: 'de', lemma: 'Schwester', gloss: 'sister', glossIt: 'la sorella', glossItPl: 'le sorelle', tags: ['family', 'human'], de: { gender: 'f', plural: 'Schwestern' } },
  { id: 'de/noun/sohn', lang: 'de', lemma: 'Sohn', gloss: 'son', glossIt: 'il figlio', glossItPl: 'i figli', tags: ['family', 'human'], de: { gender: 'm', plural: 'Söhne' } },
  { id: 'de/noun/tochter', lang: 'de', lemma: 'Tochter', gloss: 'daughter', glossIt: 'la figlia', glossItPl: 'le figlie', tags: ['family', 'human'], de: { gender: 'f', plural: 'Töchter' } },
  { id: 'de/noun/familie', lang: 'de', lemma: 'Familie', gloss: 'family', glossIt: 'la famiglia', glossItPl: 'le famiglie', tags: ['family'], de: { gender: 'f', plural: 'Familien' } },
  // people & professions
  { id: 'de/noun/lehrer', lang: 'de', lemma: 'Lehrer', gloss: 'teacher (male)', glossIt: 'il professore', glossItPl: 'i professori', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Lehrer' } },
  { id: 'de/noun/lehrerin', lang: 'de', lemma: 'Lehrerin', gloss: 'teacher (female)', glossIt: 'la professoressa', glossItPl: 'le professoresse', tags: ['human', 'profession'], de: { gender: 'f', plural: 'Lehrerinnen' } },
  { id: 'de/noun/junge', lang: 'de', lemma: 'Junge', gloss: 'boy', glossIt: 'il ragazzo', glossItPl: 'i ragazzi', tags: ['human'], de: { gender: 'm', plural: 'Jungen', nDeclension: true } },
  { id: 'de/noun/mädchen', lang: 'de', lemma: 'Mädchen', gloss: 'girl', glossIt: 'la ragazza', glossItPl: 'le ragazze', tags: ['human'], de: { gender: 'n', plural: 'Mädchen' } },
  { id: 'de/noun/arzt', lang: 'de', lemma: 'Arzt', gloss: 'doctor (male)', glossIt: 'il medico', glossItPl: 'i medici', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Ärzte' } },
  { id: 'de/noun/ärztin', lang: 'de', lemma: 'Ärztin', gloss: 'doctor (female)', glossIt: 'la dottoressa', glossItPl: 'le dottoresse', tags: ['human', 'profession'], de: { gender: 'f', plural: 'Ärztinnen' } },
  // food & drink
  { id: 'de/noun/milch', lang: 'de', lemma: 'Milch', gloss: 'milk', glossIt: 'il latte', glossItPl: 'il latte', tags: ['drink'], de: { gender: 'f', plural: 'Milch' } },
  { id: 'de/noun/käse', lang: 'de', lemma: 'Käse', gloss: 'cheese', glossIt: 'il formaggio', glossItPl: 'i formaggi', tags: ['food'], de: { gender: 'm', plural: 'Käse' } },
  { id: 'de/noun/ei', lang: 'de', lemma: 'Ei', gloss: 'egg', glossIt: 'l’uovo', glossItPl: 'le uova', tags: ['food'], de: { gender: 'n', plural: 'Eier' } },
  { id: 'de/noun/fleisch', lang: 'de', lemma: 'Fleisch', gloss: 'meat', glossIt: 'la carne', glossItPl: 'la carne', tags: ['food'], de: { gender: 'n', plural: 'Fleisch' } },
  { id: 'de/noun/reis', lang: 'de', lemma: 'Reis', gloss: 'rice', glossIt: 'il riso', glossItPl: 'il riso', tags: ['food'], de: { gender: 'm', plural: 'Reis' } },
  { id: 'de/noun/obst', lang: 'de', lemma: 'Obst', gloss: 'fruit', glossIt: 'la frutta', glossItPl: 'la frutta', tags: ['food'], de: { gender: 'n', plural: 'Obst' } },
  { id: 'de/noun/bier', lang: 'de', lemma: 'Bier', gloss: 'beer', glossIt: 'la birra', glossItPl: 'le birre', tags: ['drink'], de: { gender: 'n', plural: 'Biere' } },
  { id: 'de/noun/wein', lang: 'de', lemma: 'Wein', gloss: 'wine', glossIt: 'il vino', glossItPl: 'i vini', tags: ['drink'], de: { gender: 'm', plural: 'Weine' } },
  { id: 'de/noun/tee', lang: 'de', lemma: 'Tee', gloss: 'tea', glossIt: 'il tè', glossItPl: 'i tè', tags: ['drink'], de: { gender: 'm', plural: 'Tees' } },
  { id: 'de/noun/saft', lang: 'de', lemma: 'Saft', gloss: 'juice', glossIt: 'il succo', glossItPl: 'i succhi', tags: ['drink'], de: { gender: 'm', plural: 'Säfte' } },
  // places
  { id: 'de/noun/schule', lang: 'de', lemma: 'Schule', gloss: 'school', glossIt: 'la scuola', glossItPl: 'le scuole', tags: ['place'], de: { gender: 'f', plural: 'Schulen' } },
  { id: 'de/noun/straße', lang: 'de', lemma: 'Straße', gloss: 'street', glossIt: 'la strada', glossItPl: 'le strade', tags: ['place'], de: { gender: 'f', plural: 'Straßen' } },
  { id: 'de/noun/park', lang: 'de', lemma: 'Park', gloss: 'park', glossIt: 'il parco', glossItPl: 'i parchi', tags: ['place'], de: { gender: 'm', plural: 'Parks' } },
  { id: 'de/noun/land', lang: 'de', lemma: 'Land', gloss: 'country', glossPlural: 'countries', glossIt: 'il paese', glossItPl: 'i paesi', tags: ['place'], de: { gender: 'n', plural: 'Länder' } },
  { id: 'de/noun/dorf', lang: 'de', lemma: 'Dorf', gloss: 'village', glossIt: 'il villaggio', glossItPl: 'i villaggi', tags: ['place'], de: { gender: 'n', plural: 'Dörfer' } },
  { id: 'de/noun/bahnhof', lang: 'de', lemma: 'Bahnhof', gloss: 'train station', glossIt: 'la stazione', glossItPl: 'le stazioni', tags: ['place'], de: { gender: 'm', plural: 'Bahnhöfe' } },
  { id: 'de/noun/supermarkt', lang: 'de', lemma: 'Supermarkt', gloss: 'supermarket', glossIt: 'il supermercato', glossItPl: 'i supermercati', tags: ['place'], de: { gender: 'm', plural: 'Supermärkte' } },
  { id: 'de/noun/restaurant', lang: 'de', lemma: 'Restaurant', gloss: 'restaurant', glossIt: 'il ristorante', glossItPl: 'i ristoranti', tags: ['place'], de: { gender: 'n', plural: 'Restaurants' } },
  // everyday objects
  { id: 'de/noun/stuhl', lang: 'de', lemma: 'Stuhl', gloss: 'chair', glossIt: 'la sedia', glossItPl: 'le sedie', tags: ['object'], de: { gender: 'm', plural: 'Stühle' } },
  { id: 'de/noun/fenster', lang: 'de', lemma: 'Fenster', gloss: 'window', glossIt: 'la finestra', glossItPl: 'le finestre', tags: ['object'], de: { gender: 'n', plural: 'Fenster' } },
  { id: 'de/noun/auto', lang: 'de', lemma: 'Auto', gloss: 'car', glossIt: 'la macchina', glossItPl: 'le macchine', tags: ['vehicle'], de: { gender: 'n', plural: 'Autos' } },
  { id: 'de/noun/telefon', lang: 'de', lemma: 'Telefon', gloss: 'telephone', glossIt: 'il telefono', glossItPl: 'i telefoni', tags: ['object'], de: { gender: 'n', plural: 'Telefone' } },
  { id: 'de/noun/computer', lang: 'de', lemma: 'Computer', gloss: 'computer', glossIt: 'il computer', glossItPl: 'i computer', tags: ['object'], de: { gender: 'm', plural: 'Computer' } },
  { id: 'de/noun/handy', lang: 'de', lemma: 'Handy', gloss: 'mobile phone', glossIt: 'il cellulare', glossItPl: 'i cellulari', tags: ['object'], de: { gender: 'n', plural: 'Handys' } },
  { id: 'de/noun/tasche', lang: 'de', lemma: 'Tasche', gloss: 'bag', glossIt: 'la borsa', glossItPl: 'le borse', tags: ['object'], de: { gender: 'f', plural: 'Taschen' } },
  { id: 'de/noun/schuh', lang: 'de', lemma: 'Schuh', gloss: 'shoe', glossIt: 'la scarpa', glossItPl: 'le scarpe', tags: ['clothing'], de: { gender: 'm', plural: 'Schuhe' } },
  { id: 'de/noun/zeitung', lang: 'de', lemma: 'Zeitung', gloss: 'newspaper', glossIt: 'il giornale', glossItPl: 'i giornali', tags: ['object'], de: { gender: 'f', plural: 'Zeitungen' } },
  // time & abstract
  { id: 'de/noun/tag', lang: 'de', lemma: 'Tag', gloss: 'day', glossIt: 'il giorno', glossItPl: 'i giorni', tags: ['time'], de: { gender: 'm', plural: 'Tage' } },
  { id: 'de/noun/nacht', lang: 'de', lemma: 'Nacht', gloss: 'night', glossIt: 'la notte', glossItPl: 'le notti', tags: ['time'], de: { gender: 'f', plural: 'Nächte' } },
  { id: 'de/noun/woche', lang: 'de', lemma: 'Woche', gloss: 'week', glossIt: 'la settimana', glossItPl: 'le settimane', tags: ['time'], de: { gender: 'f', plural: 'Wochen' } },
  { id: 'de/noun/jahr', lang: 'de', lemma: 'Jahr', gloss: 'year', glossIt: 'l’anno', glossItPl: 'gli anni', tags: ['time'], de: { gender: 'n', plural: 'Jahre' } },
  { id: 'de/noun/zeit', lang: 'de', lemma: 'Zeit', gloss: 'time', glossIt: 'il tempo', glossItPl: 'i tempi', tags: ['time'], de: { gender: 'f', plural: 'Zeiten' } },
  { id: 'de/noun/sprache', lang: 'de', lemma: 'Sprache', gloss: 'language', glossIt: 'la lingua', glossItPl: 'le lingue', tags: ['abstract'], de: { gender: 'f', plural: 'Sprachen' } },
  // house & rooms
  { id: 'de/noun/küche', lang: 'de', lemma: 'Küche', gloss: 'kitchen', glossIt: 'la cucina', glossItPl: 'le cucine', tags: ['place'], de: { gender: 'f', plural: 'Küchen' } },
  { id: 'de/noun/bad', lang: 'de', lemma: 'Bad', gloss: 'bathroom', glossIt: 'il bagno', glossItPl: 'i bagni', tags: ['place'], de: { gender: 'n', plural: 'Bäder' } },
  { id: 'de/noun/schlafzimmer', lang: 'de', lemma: 'Schlafzimmer', gloss: 'bedroom', glossIt: 'la camera da letto', glossItPl: 'le camere da letto', tags: ['place'], de: { gender: 'n', plural: 'Schlafzimmer' } },
  { id: 'de/noun/wohnzimmer', lang: 'de', lemma: 'Wohnzimmer', gloss: 'living room', glossIt: 'il soggiorno', glossItPl: 'i soggiorni', tags: ['place'], de: { gender: 'n', plural: 'Wohnzimmer' } },
  { id: 'de/noun/bett', lang: 'de', lemma: 'Bett', gloss: 'bed', glossIt: 'il letto', glossItPl: 'i letti', tags: ['object'], de: { gender: 'n', plural: 'Betten' } },
  { id: 'de/noun/garten', lang: 'de', lemma: 'Garten', gloss: 'garden', glossIt: 'il giardino', glossItPl: 'i giardini', tags: ['place', 'nature'], de: { gender: 'm', plural: 'Gärten' } },
  { id: 'de/noun/spiegel', lang: 'de', lemma: 'Spiegel', gloss: 'mirror', glossIt: 'lo specchio', glossItPl: 'gli specchi', tags: ['object'], de: { gender: 'm', plural: 'Spiegel' } },
  { id: 'de/noun/lampe', lang: 'de', lemma: 'Lampe', gloss: 'lamp', glossIt: 'la lampada', glossItPl: 'le lampade', tags: ['object'], de: { gender: 'f', plural: 'Lampen' } },
  // clothes & shopping
  { id: 'de/noun/hemd', lang: 'de', lemma: 'Hemd', gloss: 'shirt', glossIt: 'la camicia', glossItPl: 'le camicie', tags: ['clothing'], de: { gender: 'n', plural: 'Hemden' } },
  { id: 'de/noun/hose', lang: 'de', lemma: 'Hose', gloss: 'trousers', glossIt: 'i pantaloni', glossItPl: 'i pantaloni', tags: ['clothing'], de: { gender: 'f', plural: 'Hosen' } },
  { id: 'de/noun/kleid', lang: 'de', lemma: 'Kleid', gloss: 'dress', glossIt: 'il vestito', glossItPl: 'i vestiti', tags: ['clothing'], de: { gender: 'n', plural: 'Kleider' } },
  { id: 'de/noun/rock', lang: 'de', lemma: 'Rock', gloss: 'skirt', glossIt: 'la gonna', glossItPl: 'le gonne', tags: ['clothing'], de: { gender: 'm', plural: 'Röcke' } },
  { id: 'de/noun/mantel', lang: 'de', lemma: 'Mantel', gloss: 'coat', glossIt: 'il cappotto', glossItPl: 'i cappotti', tags: ['clothing'], de: { gender: 'm', plural: 'Mäntel' } },
  { id: 'de/noun/jacke', lang: 'de', lemma: 'Jacke', gloss: 'jacket', glossIt: 'la giacca', glossItPl: 'le giacche', tags: ['clothing'], de: { gender: 'f', plural: 'Jacken' } },
  { id: 'de/noun/geld', lang: 'de', lemma: 'Geld', gloss: 'money', glossIt: 'i soldi', glossItPl: 'i soldi', tags: ['object'], de: { gender: 'n', plural: 'Geld' } },
  { id: 'de/noun/preis', lang: 'de', lemma: 'Preis', gloss: 'price', glossIt: 'il prezzo', glossItPl: 'i prezzi', tags: ['abstract'], de: { gender: 'm', plural: 'Preise' } },
  { id: 'de/noun/geschenk', lang: 'de', lemma: 'Geschenk', gloss: 'gift', glossIt: 'il regalo', glossItPl: 'i regali', tags: ['object'], de: { gender: 'n', plural: 'Geschenke' } },
  // travel
  { id: 'de/noun/reise', lang: 'de', lemma: 'Reise', gloss: 'trip', glossIt: 'il viaggio', glossItPl: 'i viaggi', tags: ['abstract'], de: { gender: 'f', plural: 'Reisen' } },
  { id: 'de/noun/zug', lang: 'de', lemma: 'Zug', gloss: 'train', glossIt: 'il treno', glossItPl: 'i treni', tags: ['vehicle'], de: { gender: 'm', plural: 'Züge' } },
  { id: 'de/noun/flugzeug', lang: 'de', lemma: 'Flugzeug', gloss: 'airplane', glossIt: 'l’aereo', glossItPl: 'gli aerei', tags: ['vehicle'], de: { gender: 'n', plural: 'Flugzeuge' } },
  { id: 'de/noun/flughafen', lang: 'de', lemma: 'Flughafen', gloss: 'airport', glossIt: 'l’aeroporto', glossItPl: 'gli aeroporti', tags: ['place'], de: { gender: 'm', plural: 'Flughäfen' } },
  { id: 'de/noun/hotel', lang: 'de', lemma: 'Hotel', gloss: 'hotel', glossIt: 'l’albergo', glossItPl: 'gli alberghi', tags: ['place'], de: { gender: 'n', plural: 'Hotels' } },
  { id: 'de/noun/koffer', lang: 'de', lemma: 'Koffer', gloss: 'suitcase', glossIt: 'la valigia', glossItPl: 'le valigie', tags: ['object'], de: { gender: 'm', plural: 'Koffer' } },
  { id: 'de/noun/fahrkarte', lang: 'de', lemma: 'Fahrkarte', gloss: 'ticket', glossIt: 'il biglietto', glossItPl: 'i biglietti', tags: ['object'], de: { gender: 'f', plural: 'Fahrkarten' } },
  { id: 'de/noun/meer', lang: 'de', lemma: 'Meer', gloss: 'sea', glossIt: 'il mare', glossItPl: 'i mari', tags: ['nature', 'place'], de: { gender: 'n', plural: 'Meere' } },
  { id: 'de/noun/berg', lang: 'de', lemma: 'Berg', gloss: 'mountain', glossIt: 'la montagna', glossItPl: 'le montagne', tags: ['nature', 'place'], de: { gender: 'm', plural: 'Berge' } },
  { id: 'de/noun/sonne', lang: 'de', lemma: 'Sonne', gloss: 'sun', glossIt: 'il sole', glossItPl: 'i soli', tags: ['nature'], de: { gender: 'f', plural: 'Sonnen' } },
  // daily routine & time
  { id: 'de/noun/frühstück', lang: 'de', lemma: 'Frühstück', gloss: 'breakfast', glossIt: 'la colazione', glossItPl: 'le colazioni', tags: ['food', 'daily-routine'], de: { gender: 'n', plural: 'Frühstücke' } },
  { id: 'de/noun/abendessen', lang: 'de', lemma: 'Abendessen', gloss: 'dinner', glossIt: 'la cena', glossItPl: 'le cene', tags: ['food', 'daily-routine'], de: { gender: 'n', plural: 'Abendessen' } },
  { id: 'de/noun/morgen', lang: 'de', lemma: 'Morgen', gloss: 'morning', glossIt: 'la mattina', glossItPl: 'le mattine', tags: ['time'], de: { gender: 'm', plural: 'Morgen' } },
  { id: 'de/noun/abend', lang: 'de', lemma: 'Abend', gloss: 'evening', glossIt: 'la sera', glossItPl: 'le sere', tags: ['time'], de: { gender: 'm', plural: 'Abende' } },
  { id: 'de/noun/stunde', lang: 'de', lemma: 'Stunde', gloss: 'hour', glossIt: 'l’ora', glossItPl: 'le ore', tags: ['time'], de: { gender: 'f', plural: 'Stunden' } },
  { id: 'de/noun/minute', lang: 'de', lemma: 'Minute', gloss: 'minute', glossIt: 'il minuto', glossItPl: 'i minuti', tags: ['time'], de: { gender: 'f', plural: 'Minuten' } },
  // body & health
  { id: 'de/noun/kopf', lang: 'de', lemma: 'Kopf', gloss: 'head', glossIt: 'la testa', glossItPl: 'le teste', tags: ['object'], de: { gender: 'm', plural: 'Köpfe' } },
  { id: 'de/noun/auge', lang: 'de', lemma: 'Auge', gloss: 'eye', glossIt: 'l’occhio', glossItPl: 'gli occhi', tags: ['object'], de: { gender: 'n', plural: 'Augen' } },
  { id: 'de/noun/hand', lang: 'de', lemma: 'Hand', gloss: 'hand', glossIt: 'la mano', glossItPl: 'le mani', tags: ['object'], de: { gender: 'f', plural: 'Hände' } },
  { id: 'de/noun/fuß', lang: 'de', lemma: 'Fuß', gloss: 'foot', glossPlural: 'feet', glossIt: 'il piede', glossItPl: 'i piedi', tags: ['object'], de: { gender: 'm', plural: 'Füße' } },
  { id: 'de/noun/arm', lang: 'de', lemma: 'Arm', gloss: 'arm', glossIt: 'il braccio', glossItPl: 'le braccia', tags: ['object'], de: { gender: 'm', plural: 'Arme' } },
  { id: 'de/noun/bein', lang: 'de', lemma: 'Bein', gloss: 'leg', glossIt: 'la gamba', glossItPl: 'le gambe', tags: ['object'], de: { gender: 'n', plural: 'Beine' } },
  { id: 'de/noun/herz', lang: 'de', lemma: 'Herz', gloss: 'heart', glossIt: 'il cuore', glossItPl: 'i cuori', tags: ['object'], de: { gender: 'n', plural: 'Herzen' } },
  { id: 'de/noun/bauch', lang: 'de', lemma: 'Bauch', gloss: 'belly', glossIt: 'la pancia', glossItPl: 'le pance', tags: ['object'], de: { gender: 'm', plural: 'Bäuche' } },
  { id: 'de/noun/rücken', lang: 'de', lemma: 'Rücken', gloss: 'back', glossIt: 'la schiena', glossItPl: 'le schiene', tags: ['object'], de: { gender: 'm', plural: 'Rücken' } },
  { id: 'de/noun/zahn', lang: 'de', lemma: 'Zahn', gloss: 'tooth', glossPlural: 'teeth', glossIt: 'il dente', glossItPl: 'i denti', tags: ['object'], de: { gender: 'm', plural: 'Zähne' } },
  { id: 'de/noun/mund', lang: 'de', lemma: 'Mund', gloss: 'mouth', glossIt: 'la bocca', glossItPl: 'le bocche', tags: ['object'], de: { gender: 'm', plural: 'Münder' } },
  { id: 'de/noun/nase', lang: 'de', lemma: 'Nase', gloss: 'nose', glossIt: 'il naso', glossItPl: 'i nasi', tags: ['object'], de: { gender: 'f', plural: 'Nasen' } },
  { id: 'de/noun/ohr', lang: 'de', lemma: 'Ohr', gloss: 'ear', glossIt: 'l’orecchio', glossItPl: 'le orecchie', tags: ['object'], de: { gender: 'n', plural: 'Ohren' } },
  { id: 'de/noun/haar', lang: 'de', lemma: 'Haar', gloss: 'hair', glossIt: 'il capello', glossItPl: 'i capelli', tags: ['object'], de: { gender: 'n', plural: 'Haare' } },
  { id: 'de/noun/gesicht', lang: 'de', lemma: 'Gesicht', gloss: 'face', glossIt: 'il viso', glossItPl: 'i visi', tags: ['object'], de: { gender: 'n', plural: 'Gesichter' } },
  { id: 'de/noun/finger', lang: 'de', lemma: 'Finger', gloss: 'finger', glossIt: 'il dito', glossItPl: 'le dita', tags: ['object'], de: { gender: 'm', plural: 'Finger' } },
  { id: 'de/noun/krankenhaus', lang: 'de', lemma: 'Krankenhaus', gloss: 'hospital', glossIt: 'l’ospedale', glossItPl: 'gli ospedali', tags: ['place'], de: { gender: 'n', plural: 'Krankenhäuser' } },
  { id: 'de/noun/schmerz', lang: 'de', lemma: 'Schmerz', gloss: 'pain', glossIt: 'il dolore', glossItPl: 'i dolori', tags: ['abstract'], de: { gender: 'm', plural: 'Schmerzen' } },
  // feelings & abstract
  { id: 'de/noun/angst', lang: 'de', lemma: 'Angst', gloss: 'fear', glossIt: 'la paura', glossItPl: 'le paure', tags: ['abstract'], de: { gender: 'f', plural: 'Ängste' } },
  { id: 'de/noun/freude', lang: 'de', lemma: 'Freude', gloss: 'joy', glossIt: 'la gioia', glossItPl: 'le gioie', tags: ['abstract'], de: { gender: 'f', plural: 'Freuden' } },
  { id: 'de/noun/liebe', lang: 'de', lemma: 'Liebe', gloss: 'love', glossIt: 'l’amore', glossItPl: 'gli amori', tags: ['abstract'], de: { gender: 'f', plural: 'Lieben' } },
  { id: 'de/noun/problem', lang: 'de', lemma: 'Problem', gloss: 'problem', glossIt: 'il problema', glossItPl: 'i problemi', tags: ['abstract'], de: { gender: 'n', plural: 'Probleme' } },
  { id: 'de/noun/frage', lang: 'de', lemma: 'Frage', gloss: 'question', glossIt: 'la domanda', glossItPl: 'le domande', tags: ['abstract'], de: { gender: 'f', plural: 'Fragen' } },
  { id: 'de/noun/antwort', lang: 'de', lemma: 'Antwort', gloss: 'answer', glossIt: 'la risposta', glossItPl: 'le risposte', tags: ['abstract'], de: { gender: 'f', plural: 'Antworten' } },
  { id: 'de/noun/wahrheit', lang: 'de', lemma: 'Wahrheit', gloss: 'truth', glossIt: 'la verità', glossItPl: 'le verità', tags: ['abstract'], de: { gender: 'f', plural: 'Wahrheiten' } },
  { id: 'de/noun/glück', lang: 'de', lemma: 'Glück', gloss: 'luck / happiness', glossIt: 'la fortuna', glossItPl: 'la fortuna', tags: ['abstract'], de: { gender: 'n', plural: 'Glück' } },
  { id: 'de/noun/hilfe', lang: 'de', lemma: 'Hilfe', gloss: 'help', glossIt: 'l’aiuto', glossItPl: 'gli aiuti', tags: ['abstract'], de: { gender: 'f', plural: 'Hilfen' } },
  { id: 'de/noun/idee', lang: 'de', lemma: 'Idee', gloss: 'idea', glossIt: 'l’idea', glossItPl: 'le idee', tags: ['abstract'], de: { gender: 'f', plural: 'Ideen' } },
  { id: 'de/noun/grund', lang: 'de', lemma: 'Grund', gloss: 'reason', glossIt: 'il motivo', glossItPl: 'i motivi', tags: ['abstract'], de: { gender: 'm', plural: 'Gründe' } },
  { id: 'de/noun/traum', lang: 'de', lemma: 'Traum', gloss: 'dream', glossIt: 'il sogno', glossItPl: 'i sogni', tags: ['abstract'], de: { gender: 'm', plural: 'Träume' } },
  // weather & nature
  { id: 'de/noun/himmel', lang: 'de', lemma: 'Himmel', gloss: 'sky', glossIt: 'il cielo', glossItPl: 'i cieli', tags: ['nature'], de: { gender: 'm', plural: 'Himmel' } },
  { id: 'de/noun/stern', lang: 'de', lemma: 'Stern', gloss: 'star', glossIt: 'la stella', glossItPl: 'le stelle', tags: ['nature'], de: { gender: 'm', plural: 'Sterne' } },
  { id: 'de/noun/mond', lang: 'de', lemma: 'Mond', gloss: 'moon', glossIt: 'la luna', glossItPl: 'le lune', tags: ['nature'], de: { gender: 'm', plural: 'Monde' } },
  { id: 'de/noun/regen', lang: 'de', lemma: 'Regen', gloss: 'rain', glossIt: 'la pioggia', glossItPl: 'la pioggia', tags: ['nature'], de: { gender: 'm', plural: 'Regen' } },
  { id: 'de/noun/schnee', lang: 'de', lemma: 'Schnee', gloss: 'snow', glossIt: 'la neve', glossItPl: 'la neve', tags: ['nature'], de: { gender: 'm', plural: 'Schnee' } },
  { id: 'de/noun/wind', lang: 'de', lemma: 'Wind', gloss: 'wind', glossIt: 'il vento', glossItPl: 'i venti', tags: ['nature'], de: { gender: 'm', plural: 'Winde' } },
  { id: 'de/noun/wolke', lang: 'de', lemma: 'Wolke', gloss: 'cloud', glossIt: 'la nuvola', glossItPl: 'le nuvole', tags: ['nature'], de: { gender: 'f', plural: 'Wolken' } },
  { id: 'de/noun/baum', lang: 'de', lemma: 'Baum', gloss: 'tree', glossIt: 'l’albero', glossItPl: 'gli alberi', tags: ['nature'], de: { gender: 'm', plural: 'Bäume' } },
  { id: 'de/noun/blume', lang: 'de', lemma: 'Blume', gloss: 'flower', glossIt: 'il fiore', glossItPl: 'i fiori', tags: ['nature'], de: { gender: 'f', plural: 'Blumen' } },
  { id: 'de/noun/fluss', lang: 'de', lemma: 'Fluss', gloss: 'river', glossIt: 'il fiume', glossItPl: 'i fiumi', tags: ['nature', 'place'], de: { gender: 'm', plural: 'Flüsse' } },
  { id: 'de/noun/wald', lang: 'de', lemma: 'Wald', gloss: 'forest', glossIt: 'il bosco', glossItPl: 'i boschi', tags: ['nature', 'place'], de: { gender: 'm', plural: 'Wälder' } },
  { id: 'de/noun/wetter', lang: 'de', lemma: 'Wetter', gloss: 'weather', glossIt: 'il tempo', glossItPl: 'il tempo', tags: ['nature'], de: { gender: 'n', plural: 'Wetter' } },
  { id: 'de/noun/feld', lang: 'de', lemma: 'Feld', gloss: 'field', glossIt: 'il campo', glossItPl: 'i campi', tags: ['nature', 'place'], de: { gender: 'n', plural: 'Felder' } },
  { id: 'de/noun/see', lang: 'de', lemma: 'See', gloss: 'lake', glossIt: 'il lago', glossItPl: 'i laghi', tags: ['nature', 'place'], de: { gender: 'm', plural: 'Seen' } },
  // work & school
  { id: 'de/noun/büro', lang: 'de', lemma: 'Büro', gloss: 'office', glossIt: 'l’ufficio', glossItPl: 'gli uffici', tags: ['place'], de: { gender: 'n', plural: 'Büros' } },
  { id: 'de/noun/firma', lang: 'de', lemma: 'Firma', gloss: 'company', glossIt: 'la ditta', glossItPl: 'le ditte', tags: ['place'], de: { gender: 'f', plural: 'Firmen' } },
  { id: 'de/noun/chef', lang: 'de', lemma: 'Chef', gloss: 'boss (male)', glossIt: 'il capo', glossItPl: 'i capi', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Chefs' } },
  { id: 'de/noun/chefin', lang: 'de', lemma: 'Chefin', gloss: 'boss (female)', glossIt: 'la capa', glossItPl: 'le cape', tags: ['human', 'profession'], de: { gender: 'f', plural: 'Chefinnen' } },
  { id: 'de/noun/besprechung', lang: 'de', lemma: 'Besprechung', gloss: 'meeting', glossIt: 'la riunione', glossItPl: 'le riunioni', tags: ['abstract'], de: { gender: 'f', plural: 'Besprechungen' } },
  { id: 'de/noun/email', lang: 'de', lemma: 'E-Mail', gloss: 'e-mail', glossIt: 'l’e-mail', glossItPl: 'le e-mail', tags: ['object'], de: { gender: 'f', plural: 'E-Mails' } },
  { id: 'de/noun/brief', lang: 'de', lemma: 'Brief', gloss: 'letter', glossIt: 'la lettera', glossItPl: 'le lettere', tags: ['object'], de: { gender: 'm', plural: 'Briefe' } },
  { id: 'de/noun/papier', lang: 'de', lemma: 'Papier', gloss: 'paper', glossIt: 'la carta', glossItPl: 'le carte', tags: ['object'], de: { gender: 'n', plural: 'Papiere' } },
  { id: 'de/noun/prüfung', lang: 'de', lemma: 'Prüfung', gloss: 'exam', glossIt: 'l’esame', glossItPl: 'gli esami', tags: ['abstract'], de: { gender: 'f', plural: 'Prüfungen' } },
  { id: 'de/noun/klasse', lang: 'de', lemma: 'Klasse', gloss: 'class', glossIt: 'la classe', glossItPl: 'le classi', tags: ['place'], de: { gender: 'f', plural: 'Klassen' } },
  { id: 'de/noun/universität', lang: 'de', lemma: 'Universität', gloss: 'university', glossIt: 'l’università', glossItPl: 'le università', tags: ['place'], de: { gender: 'f', plural: 'Universitäten' } },
  { id: 'de/noun/wort', lang: 'de', lemma: 'Wort', gloss: 'word', glossIt: 'la parola', glossItPl: 'le parole', tags: ['abstract'], de: { gender: 'n', plural: 'Wörter' } },
  { id: 'de/noun/satz', lang: 'de', lemma: 'Satz', gloss: 'sentence', glossIt: 'la frase', glossItPl: 'le frasi', tags: ['abstract'], de: { gender: 'm', plural: 'Sätze' } },
  { id: 'de/noun/hausaufgabe', lang: 'de', lemma: 'Hausaufgabe', gloss: 'homework', glossIt: 'il compito', glossItPl: 'i compiti', tags: ['abstract'], de: { gender: 'f', plural: 'Hausaufgaben' } },
  { id: 'de/noun/beruf', lang: 'de', lemma: 'Beruf', gloss: 'profession', glossIt: 'la professione', glossItPl: 'le professioni', tags: ['profession', 'abstract'], de: { gender: 'm', plural: 'Berufe' } },
  // tech & media
  { id: 'de/noun/internet', lang: 'de', lemma: 'Internet', gloss: 'internet', glossIt: 'internet', glossItPl: 'internet', tags: ['abstract'], de: { gender: 'n', plural: 'Internet' } },
  { id: 'de/noun/film', lang: 'de', lemma: 'Film', gloss: 'film', glossIt: 'il film', glossItPl: 'i film', tags: ['object'], de: { gender: 'm', plural: 'Filme' } },
  { id: 'de/noun/musik', lang: 'de', lemma: 'Musik', gloss: 'music', glossIt: 'la musica', glossItPl: 'la musica', tags: ['abstract'], de: { gender: 'f', plural: 'Musik' } },
  { id: 'de/noun/lied', lang: 'de', lemma: 'Lied', gloss: 'song', glossIt: 'la canzone', glossItPl: 'le canzoni', tags: ['abstract'], de: { gender: 'n', plural: 'Lieder' } },
  { id: 'de/noun/radio', lang: 'de', lemma: 'Radio', gloss: 'radio', glossIt: 'la radio', glossItPl: 'le radio', tags: ['object'], de: { gender: 'n', plural: 'Radios' } },
  { id: 'de/noun/fernsehen', lang: 'de', lemma: 'Fernsehen', gloss: 'television', glossIt: 'la televisione', glossItPl: 'la televisione', tags: ['object'], de: { gender: 'n', plural: 'Fernsehen' } },
  { id: 'de/noun/foto', lang: 'de', lemma: 'Foto', gloss: 'photo', glossIt: 'la foto', glossItPl: 'le foto', tags: ['object'], de: { gender: 'n', plural: 'Fotos' } },
  { id: 'de/noun/nachricht', lang: 'de', lemma: 'Nachricht', gloss: 'message', glossIt: 'il messaggio', glossItPl: 'i messaggi', tags: ['object', 'abstract'], de: { gender: 'f', plural: 'Nachrichten' } },
  { id: 'de/noun/spiel', lang: 'de', lemma: 'Spiel', gloss: 'game', glossIt: 'il gioco', glossItPl: 'i giochi', tags: ['object'], de: { gender: 'n', plural: 'Spiele' } },
  { id: 'de/noun/netz', lang: 'de', lemma: 'Netz', gloss: 'net / network', glossIt: 'la rete', glossItPl: 'le reti', tags: ['object'], de: { gender: 'n', plural: 'Netze' } },
  // city
  { id: 'de/noun/platz', lang: 'de', lemma: 'Platz', gloss: 'square', glossIt: 'la piazza', glossItPl: 'le piazze', tags: ['place'], de: { gender: 'm', plural: 'Plätze' } },
  { id: 'de/noun/kirche', lang: 'de', lemma: 'Kirche', gloss: 'church', glossIt: 'la chiesa', glossItPl: 'le chiese', tags: ['place'], de: { gender: 'f', plural: 'Kirchen' } },
  { id: 'de/noun/museum', lang: 'de', lemma: 'Museum', gloss: 'museum', glossIt: 'il museo', glossItPl: 'i musei', tags: ['place'], de: { gender: 'n', plural: 'Museen' } },
  { id: 'de/noun/bank', lang: 'de', lemma: 'Bank', gloss: 'bank', glossIt: 'la banca', glossItPl: 'le banche', tags: ['place'], de: { gender: 'f', plural: 'Banken' } },
  { id: 'de/noun/brücke', lang: 'de', lemma: 'Brücke', gloss: 'bridge', glossIt: 'il ponte', glossItPl: 'i ponti', tags: ['place'], de: { gender: 'f', plural: 'Brücken' } },
  { id: 'de/noun/ecke', lang: 'de', lemma: 'Ecke', gloss: 'corner', glossIt: 'l’angolo', glossItPl: 'gli angoli', tags: ['place'], de: { gender: 'f', plural: 'Ecken' } },
  { id: 'de/noun/eingang', lang: 'de', lemma: 'Eingang', gloss: 'entrance', glossIt: 'l’entrata', glossItPl: 'le entrate', tags: ['place'], de: { gender: 'm', plural: 'Eingänge' } },
  { id: 'de/noun/ausgang', lang: 'de', lemma: 'Ausgang', gloss: 'exit', glossIt: 'l’uscita', glossItPl: 'le uscite', tags: ['place'], de: { gender: 'm', plural: 'Ausgänge' } },
  { id: 'de/noun/ticket', lang: 'de', lemma: 'Ticket', gloss: 'ticket', glossIt: 'il biglietto', glossItPl: 'i biglietti', tags: ['object'], de: { gender: 'n', plural: 'Tickets' } },
  { id: 'de/noun/ubahn', lang: 'de', lemma: 'U-Bahn', gloss: 'underground / subway', glossIt: 'la metropolitana', glossItPl: 'le metropolitane', tags: ['vehicle'], de: { gender: 'f', plural: 'U-Bahnen' } },
  // more food
  { id: 'de/noun/suppe', lang: 'de', lemma: 'Suppe', gloss: 'soup', glossIt: 'la zuppa', glossItPl: 'le zuppe', tags: ['food'], de: { gender: 'f', plural: 'Suppen' } },
  { id: 'de/noun/salat', lang: 'de', lemma: 'Salat', gloss: 'salad', glossIt: 'l’insalata', glossItPl: 'le insalate', tags: ['food'], de: { gender: 'm', plural: 'Salate' } },
  { id: 'de/noun/hähnchen', lang: 'de', lemma: 'Hähnchen', gloss: 'chicken', glossIt: 'il pollo', glossItPl: 'i polli', tags: ['food'], de: { gender: 'n', plural: 'Hähnchen' } },
  { id: 'de/noun/tomate', lang: 'de', lemma: 'Tomate', gloss: 'tomato', glossIt: 'il pomodoro', glossItPl: 'i pomodori', tags: ['food'], de: { gender: 'f', plural: 'Tomaten' } },
  { id: 'de/noun/kartoffel', lang: 'de', lemma: 'Kartoffel', gloss: 'potato', glossIt: 'la patata', glossItPl: 'le patate', tags: ['food'], de: { gender: 'f', plural: 'Kartoffeln' } },
  { id: 'de/noun/zucker', lang: 'de', lemma: 'Zucker', gloss: 'sugar', glossIt: 'lo zucchero', glossItPl: 'lo zucchero', tags: ['food'], de: { gender: 'm', plural: 'Zucker' } },
  { id: 'de/noun/salz', lang: 'de', lemma: 'Salz', gloss: 'salt', glossIt: 'il sale', glossItPl: 'il sale', tags: ['food'], de: { gender: 'n', plural: 'Salz' } },
  { id: 'de/noun/öl', lang: 'de', lemma: 'Öl', gloss: 'oil', glossIt: 'l’olio', glossItPl: 'gli oli', tags: ['food'], de: { gender: 'n', plural: 'Öle' } },
  { id: 'de/noun/nachtisch', lang: 'de', lemma: 'Nachtisch', gloss: 'dessert', glossIt: 'il dolce', glossItPl: 'i dolci', tags: ['food'], de: { gender: 'm', plural: 'Nachtische' } },
  { id: 'de/noun/eis', lang: 'de', lemma: 'Eis', gloss: 'ice cream', glossIt: 'il gelato', glossItPl: 'il gelato', tags: ['food'], de: { gender: 'n', plural: 'Eis' } },
  { id: 'de/noun/kuchen', lang: 'de', lemma: 'Kuchen', gloss: 'cake', glossIt: 'la torta', glossItPl: 'le torte', tags: ['food'], de: { gender: 'm', plural: 'Kuchen' } },
  { id: 'de/noun/butter', lang: 'de', lemma: 'Butter', gloss: 'butter', glossIt: 'il burro', glossItPl: 'il burro', tags: ['food'], de: { gender: 'f', plural: 'Butter' } },
  // days & seasons
  { id: 'de/noun/montag', lang: 'de', lemma: 'Montag', gloss: 'Monday', glossIt: 'il lunedì', glossItPl: 'i lunedì', tags: ['time'], de: { gender: 'm', plural: 'Montage' } },
  { id: 'de/noun/dienstag', lang: 'de', lemma: 'Dienstag', gloss: 'Tuesday', glossIt: 'il martedì', glossItPl: 'i martedì', tags: ['time'], de: { gender: 'm', plural: 'Dienstage' } },
  { id: 'de/noun/mittwoch', lang: 'de', lemma: 'Mittwoch', gloss: 'Wednesday', glossIt: 'il mercoledì', glossItPl: 'i mercoledì', tags: ['time'], de: { gender: 'm', plural: 'Mittwoche' } },
  { id: 'de/noun/donnerstag', lang: 'de', lemma: 'Donnerstag', gloss: 'Thursday', glossIt: 'il giovedì', glossItPl: 'i giovedì', tags: ['time'], de: { gender: 'm', plural: 'Donnerstage' } },
  { id: 'de/noun/freitag', lang: 'de', lemma: 'Freitag', gloss: 'Friday', glossIt: 'il venerdì', glossItPl: 'i venerdì', tags: ['time'], de: { gender: 'm', plural: 'Freitage' } },
  { id: 'de/noun/samstag', lang: 'de', lemma: 'Samstag', gloss: 'Saturday', glossIt: 'il sabato', glossItPl: 'i sabati', tags: ['time'], de: { gender: 'm', plural: 'Samstage' } },
  { id: 'de/noun/sonntag', lang: 'de', lemma: 'Sonntag', gloss: 'Sunday', glossIt: 'la domenica', glossItPl: 'le domeniche', tags: ['time'], de: { gender: 'm', plural: 'Sonntage' } },
  { id: 'de/noun/monat', lang: 'de', lemma: 'Monat', gloss: 'month', glossIt: 'il mese', glossItPl: 'i mesi', tags: ['time'], de: { gender: 'm', plural: 'Monate' } },
  { id: 'de/noun/wochenende', lang: 'de', lemma: 'Wochenende', gloss: 'weekend', glossIt: 'il fine settimana', glossItPl: 'i fine settimana', tags: ['time'], de: { gender: 'n', plural: 'Wochenenden' } },
  { id: 'de/noun/frühling', lang: 'de', lemma: 'Frühling', gloss: 'spring', glossIt: 'la primavera', glossItPl: 'le primavere', tags: ['time'], de: { gender: 'm', plural: 'Frühlinge' } },
  { id: 'de/noun/sommer', lang: 'de', lemma: 'Sommer', gloss: 'summer', glossIt: 'l’estate', glossItPl: 'le estati', tags: ['time'], de: { gender: 'm', plural: 'Sommer' } },
  { id: 'de/noun/herbst', lang: 'de', lemma: 'Herbst', gloss: 'autumn', glossIt: 'l’autunno', glossItPl: 'gli autunni', tags: ['time'], de: { gender: 'm', plural: 'Herbste' } },
  { id: 'de/noun/winter', lang: 'de', lemma: 'Winter', gloss: 'winter', glossIt: 'l’inverno', glossItPl: 'gli inverni', tags: ['time'], de: { gender: 'm', plural: 'Winter' } },
  { id: 'de/noun/datum', lang: 'de', lemma: 'Datum', gloss: 'date', glossIt: 'la data', glossItPl: 'le date', tags: ['time'], de: { gender: 'n', plural: 'Daten' } },
  { id: 'de/noun/geburtstag', lang: 'de', lemma: 'Geburtstag', gloss: 'birthday', glossIt: 'il compleanno', glossItPl: 'i compleanni', tags: ['time'], de: { gender: 'm', plural: 'Geburtstage' } },
  { id: 'de/noun/urlaub', lang: 'de', lemma: 'Urlaub', gloss: 'vacation', glossIt: 'la vacanza', glossItPl: 'le vacanze', tags: ['time'], de: { gender: 'm', plural: 'Urlaube' } },
  { id: 'de/noun/sekunde', lang: 'de', lemma: 'Sekunde', gloss: 'second', glossIt: 'il secondo', glossItPl: 'i secondi', tags: ['time'], de: { gender: 'f', plural: 'Sekunden' } },
  { id: 'de/noun/kalender', lang: 'de', lemma: 'Kalender', gloss: 'calendar', glossIt: 'il calendario', glossItPl: 'i calendari', tags: ['object', 'time'], de: { gender: 'm', plural: 'Kalender' } },
  { id: 'de/noun/jahreszeit', lang: 'de', lemma: 'Jahreszeit', gloss: 'season', glossIt: 'la stagione', glossItPl: 'le stagioni', tags: ['time'], de: { gender: 'f', plural: 'Jahreszeiten' } },
  // people
  { id: 'de/noun/nachbar', lang: 'de', lemma: 'Nachbar', gloss: 'neighbor (male)', glossIt: 'il vicino', glossItPl: 'i vicini', tags: ['human'], de: { gender: 'm', plural: 'Nachbarn', nDeclension: true } },
  { id: 'de/noun/nachbarin', lang: 'de', lemma: 'Nachbarin', gloss: 'neighbor (female)', glossIt: 'la vicina', glossItPl: 'le vicine', tags: ['human'], de: { gender: 'f', plural: 'Nachbarinnen' } },
  { id: 'de/noun/gast', lang: 'de', lemma: 'Gast', gloss: 'guest', glossIt: 'l’ospite', glossItPl: 'gli ospiti', tags: ['human'], de: { gender: 'm', plural: 'Gäste' } },
  { id: 'de/noun/tourist', lang: 'de', lemma: 'Tourist', gloss: 'tourist', glossIt: 'il turista', glossItPl: 'i turisti', tags: ['human'], de: { gender: 'm', plural: 'Touristen', nDeclension: true } },
  { id: 'de/noun/person', lang: 'de', lemma: 'Person', gloss: 'person', glossPlural: 'people', glossIt: 'la persona', glossItPl: 'le persone', tags: ['human'], de: { gender: 'f', plural: 'Personen' } },
  // plural-only: "die Leute" — the f article yields "die" in both numbers
  { id: 'de/noun/leute', lang: 'de', lemma: 'Leute', gloss: 'people', glossIt: 'la gente', glossItPl: 'la gente', tags: ['human'], de: { gender: 'f', plural: 'Leute' } },
  { id: 'de/noun/herr', lang: 'de', lemma: 'Herr', gloss: 'gentleman / Mr.', glossIt: 'il signore', glossItPl: 'i signori', tags: ['human'], de: { gender: 'm', plural: 'Herren', nDeclension: true } },
  { id: 'de/noun/dame', lang: 'de', lemma: 'Dame', gloss: 'lady', glossIt: 'la signora', glossItPl: 'le signore', tags: ['human'], de: { gender: 'f', plural: 'Damen' } },
  { id: 'de/noun/paar', lang: 'de', lemma: 'Paar', gloss: 'couple / pair', glossIt: 'la coppia', glossItPl: 'le coppie', tags: ['human'], de: { gender: 'n', plural: 'Paare' } },
  // house 2
  { id: 'de/noun/schlüssel', lang: 'de', lemma: 'Schlüssel', gloss: 'key', glossIt: 'la chiave', glossItPl: 'le chiavi', tags: ['object'], de: { gender: 'm', plural: 'Schlüssel' } },
  { id: 'de/noun/treppe', lang: 'de', lemma: 'Treppe', gloss: 'staircase', glossIt: 'la scala', glossItPl: 'le scale', tags: ['place'], de: { gender: 'f', plural: 'Treppen' } },
  { id: 'de/noun/aufzug', lang: 'de', lemma: 'Aufzug', gloss: 'elevator', glossIt: 'l’ascensore', glossItPl: 'gli ascensori', tags: ['object'], de: { gender: 'm', plural: 'Aufzüge' } },
  { id: 'de/noun/wand', lang: 'de', lemma: 'Wand', gloss: 'wall', glossIt: 'la parete', glossItPl: 'le pareti', tags: ['object'], de: { gender: 'f', plural: 'Wände' } },
  { id: 'de/noun/boden', lang: 'de', lemma: 'Boden', gloss: 'floor / ground', glossIt: 'il pavimento', glossItPl: 'i pavimenti', tags: ['object'], de: { gender: 'm', plural: 'Böden' } },
  { id: 'de/noun/decke', lang: 'de', lemma: 'Decke', gloss: 'blanket / ceiling', glossIt: 'la coperta', glossItPl: 'le coperte', tags: ['object'], de: { gender: 'f', plural: 'Decken' } },
  { id: 'de/noun/ofen', lang: 'de', lemma: 'Ofen', gloss: 'oven', glossIt: 'il forno', glossItPl: 'i forni', tags: ['object'], de: { gender: 'm', plural: 'Öfen' } },
  { id: 'de/noun/kühlschrank', lang: 'de', lemma: 'Kühlschrank', gloss: 'fridge', glossIt: 'il frigorifero', glossItPl: 'i frigoriferi', tags: ['object'], de: { gender: 'm', plural: 'Kühlschränke' } },
  { id: 'de/noun/waschmaschine', lang: 'de', lemma: 'Waschmaschine', gloss: 'washing machine', glossIt: 'la lavatrice', glossItPl: 'le lavatrici', tags: ['object'], de: { gender: 'f', plural: 'Waschmaschinen' } },
  { id: 'de/noun/handtuch', lang: 'de', lemma: 'Handtuch', gloss: 'towel', glossIt: 'l’asciugamano', glossItPl: 'gli asciugamani', tags: ['object'], de: { gender: 'n', plural: 'Handtücher' } },
  { id: 'de/noun/seife', lang: 'de', lemma: 'Seife', gloss: 'soap', glossIt: 'il sapone', glossItPl: 'i saponi', tags: ['object'], de: { gender: 'f', plural: 'Seifen' } },
  { id: 'de/noun/kissen', lang: 'de', lemma: 'Kissen', gloss: 'pillow', glossIt: 'il cuscino', glossItPl: 'i cuscini', tags: ['object'], de: { gender: 'n', plural: 'Kissen' } },
  // restaurant & shopping
  { id: 'de/noun/kellner', lang: 'de', lemma: 'Kellner', gloss: 'waiter', glossIt: 'il cameriere', glossItPl: 'i camerieri', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Kellner' } },
  { id: 'de/noun/kellnerin', lang: 'de', lemma: 'Kellnerin', gloss: 'waitress', glossIt: 'la cameriera', glossItPl: 'le cameriere', tags: ['human', 'profession'], de: { gender: 'f', plural: 'Kellnerinnen' } },
  { id: 'de/noun/rechnung', lang: 'de', lemma: 'Rechnung', gloss: 'bill', glossIt: 'il conto', glossItPl: 'i conti', tags: ['object'], de: { gender: 'f', plural: 'Rechnungen' } },
  { id: 'de/noun/trinkgeld', lang: 'de', lemma: 'Trinkgeld', gloss: 'tip', glossIt: 'la mancia', glossItPl: 'le mance', tags: ['object'], de: { gender: 'n', plural: 'Trinkgelder' } },
  { id: 'de/noun/speisekarte', lang: 'de', lemma: 'Speisekarte', gloss: 'menu', glossIt: 'il menù', glossItPl: 'i menù', tags: ['object'], de: { gender: 'f', plural: 'Speisekarten' } },
  { id: 'de/noun/bäckerei', lang: 'de', lemma: 'Bäckerei', gloss: 'bakery', glossIt: 'la panetteria', glossItPl: 'le panetterie', tags: ['place'], de: { gender: 'f', plural: 'Bäckereien' } },
  { id: 'de/noun/metzgerei', lang: 'de', lemma: 'Metzgerei', gloss: 'butcher shop', glossIt: 'la macelleria', glossItPl: 'le macellerie', tags: ['place'], de: { gender: 'f', plural: 'Metzgereien' } },
  { id: 'de/noun/ausverkauf', lang: 'de', lemma: 'Ausverkauf', gloss: 'sale / clearance', glossIt: 'i saldi', glossItPl: 'i saldi', tags: ['abstract'], de: { gender: 'm', plural: 'Ausverkäufe' } },
  { id: 'de/noun/größe', lang: 'de', lemma: 'Größe', gloss: 'size', glossIt: 'la taglia', glossItPl: 'le taglie', tags: ['abstract'], de: { gender: 'f', plural: 'Größen' } },
  { id: 'de/noun/tüte', lang: 'de', lemma: 'Tüte', gloss: 'bag (paper/plastic)', glossIt: 'il sacchetto', glossItPl: 'i sacchetti', tags: ['object'], de: { gender: 'f', plural: 'Tüten' } },
  { id: 'de/noun/kasse', lang: 'de', lemma: 'Kasse', gloss: 'checkout / till', glossIt: 'la cassa', glossItPl: 'le casse', tags: ['object'], de: { gender: 'f', plural: 'Kassen' } },
  { id: 'de/noun/karte', lang: 'de', lemma: 'Karte', gloss: 'card', glossIt: 'la carta', glossItPl: 'le carte', tags: ['object'], de: { gender: 'f', plural: 'Karten' } },
  { id: 'de/noun/bargeld', lang: 'de', lemma: 'Bargeld', gloss: 'cash', glossIt: 'i contanti', glossItPl: 'i contanti', tags: ['object'], de: { gender: 'n', plural: 'Bargeld' } },
  // education
  { id: 'de/noun/grammatik', lang: 'de', lemma: 'Grammatik', gloss: 'grammar', glossIt: 'la grammatica', glossItPl: 'le grammatiche', tags: ['abstract'], de: { gender: 'f', plural: 'Grammatiken' } },
  { id: 'de/noun/übung', lang: 'de', lemma: 'Übung', gloss: 'exercise', glossIt: 'l’esercizio', glossItPl: 'gli esercizi', tags: ['abstract'], de: { gender: 'f', plural: 'Übungen' } },
  { id: 'de/noun/fehler', lang: 'de', lemma: 'Fehler', gloss: 'mistake', glossIt: 'l’errore', glossItPl: 'gli errori', tags: ['abstract'], de: { gender: 'm', plural: 'Fehler' } },
  { id: 'de/noun/niveau', lang: 'de', lemma: 'Niveau', gloss: 'level', glossIt: 'il livello', glossItPl: 'i livelli', tags: ['abstract'], de: { gender: 'n', plural: 'Niveaus' } },
  { id: 'de/noun/kurs', lang: 'de', lemma: 'Kurs', gloss: 'course', glossIt: 'il corso', glossItPl: 'i corsi', tags: ['abstract'], de: { gender: 'm', plural: 'Kurse' } },
  { id: 'de/noun/seite', lang: 'de', lemma: 'Seite', gloss: 'page / side', glossIt: 'la pagina', glossItPl: 'le pagine', tags: ['object'], de: { gender: 'f', plural: 'Seiten' } },
  { id: 'de/noun/heft', lang: 'de', lemma: 'Heft', gloss: 'notebook', glossIt: 'il quaderno', glossItPl: 'i quaderni', tags: ['object'], de: { gender: 'n', plural: 'Hefte' } },
  { id: 'de/noun/kuli', lang: 'de', lemma: 'Kuli', gloss: 'ballpoint pen', glossIt: 'la penna', glossItPl: 'le penne', tags: ['object'], de: { gender: 'm', plural: 'Kulis' } },
  { id: 'de/noun/bleistift', lang: 'de', lemma: 'Bleistift', gloss: 'pencil', glossIt: 'la matita', glossItPl: 'le matite', tags: ['object'], de: { gender: 'm', plural: 'Bleistifte' } },
  { id: 'de/noun/bedeutung', lang: 'de', lemma: 'Bedeutung', gloss: 'meaning', glossIt: 'il significato', glossItPl: 'i significati', tags: ['abstract'], de: { gender: 'f', plural: 'Bedeutungen' } },
  // travel 2
  { id: 'de/noun/pass', lang: 'de', lemma: 'Pass', gloss: 'passport', glossIt: 'il passaporto', glossItPl: 'i passaporti', tags: ['object'], de: { gender: 'm', plural: 'Pässe' } },
  { id: 'de/noun/grenze', lang: 'de', lemma: 'Grenze', gloss: 'border', glossIt: 'il confine', glossItPl: 'i confini', tags: ['place'], de: { gender: 'f', plural: 'Grenzen' } },
  { id: 'de/noun/reservierung', lang: 'de', lemma: 'Reservierung', gloss: 'reservation', glossIt: 'la prenotazione', glossItPl: 'le prenotazioni', tags: ['abstract'], de: { gender: 'f', plural: 'Reservierungen' } },
  { id: 'de/noun/zimmer', lang: 'de', lemma: 'Zimmer', gloss: 'room', glossIt: 'la stanza', glossItPl: 'le stanze', tags: ['place'], de: { gender: 'n', plural: 'Zimmer' } },
  { id: 'de/noun/ankunft', lang: 'de', lemma: 'Ankunft', gloss: 'arrival', glossIt: 'l’arrivo', glossItPl: 'gli arrivi', tags: ['abstract'], de: { gender: 'f', plural: 'Ankünfte' } },
  { id: 'de/noun/verspätung', lang: 'de', lemma: 'Verspätung', gloss: 'delay', glossIt: 'il ritardo', glossItPl: 'i ritardi', tags: ['abstract'], de: { gender: 'f', plural: 'Verspätungen' } },
  { id: 'de/noun/gleis', lang: 'de', lemma: 'Gleis', gloss: 'platform / track', glossIt: 'il binario', glossItPl: 'i binari', tags: ['place'], de: { gender: 'n', plural: 'Gleise' } },
  { id: 'de/noun/flug', lang: 'de', lemma: 'Flug', gloss: 'flight', glossIt: 'il volo', glossItPl: 'i voli', tags: ['abstract'], de: { gender: 'm', plural: 'Flüge' } },
  { id: 'de/noun/gepäck', lang: 'de', lemma: 'Gepäck', gloss: 'luggage', glossIt: 'il bagaglio', glossItPl: 'i bagagli', tags: ['object'], de: { gender: 'n', plural: 'Gepäck' } },
  { id: 'de/noun/reiseführer', lang: 'de', lemma: 'Reiseführer', gloss: 'travel guide', glossIt: 'la guida', glossItPl: 'le guide', tags: ['object'], de: { gender: 'm', plural: 'Reiseführer' } },
  { id: 'de/noun/landkarte', lang: 'de', lemma: 'Landkarte', gloss: 'map', glossIt: 'la mappa', glossItPl: 'le mappe', tags: ['object'], de: { gender: 'f', plural: 'Landkarten' } },
  // nature 2 & animals
  { id: 'de/noun/insel', lang: 'de', lemma: 'Insel', gloss: 'island', glossIt: 'l’isola', glossItPl: 'le isole', tags: ['nature', 'place'], de: { gender: 'f', plural: 'Inseln' } },
  { id: 'de/noun/stein', lang: 'de', lemma: 'Stein', gloss: 'stone', glossIt: 'la pietra', glossItPl: 'le pietre', tags: ['nature', 'object'], de: { gender: 'm', plural: 'Steine' } },
  { id: 'de/noun/gras', lang: 'de', lemma: 'Gras', gloss: 'grass', glossIt: 'l’erba', glossItPl: 'le erbe', tags: ['nature'], de: { gender: 'n', plural: 'Gräser' } },
  { id: 'de/noun/blatt', lang: 'de', lemma: 'Blatt', gloss: 'leaf', glossPlural: 'leaves', glossIt: 'la foglia', glossItPl: 'le foglie', tags: ['nature'], de: { gender: 'n', plural: 'Blätter' } },
  { id: 'de/noun/tier', lang: 'de', lemma: 'Tier', gloss: 'animal', glossIt: 'l’animale', glossItPl: 'gli animali', tags: ['animal'], de: { gender: 'n', plural: 'Tiere' } },
  { id: 'de/noun/vogel', lang: 'de', lemma: 'Vogel', gloss: 'bird', glossIt: 'l’uccello', glossItPl: 'gli uccelli', tags: ['animal'], de: { gender: 'm', plural: 'Vögel' } },
  { id: 'de/noun/hund', lang: 'de', lemma: 'Hund', gloss: 'dog', glossIt: 'il cane', glossItPl: 'i cani', tags: ['animal'], de: { gender: 'm', plural: 'Hunde' } },
  { id: 'de/noun/katze', lang: 'de', lemma: 'Katze', gloss: 'cat', glossIt: 'il gatto', glossItPl: 'i gatti', tags: ['animal'], de: { gender: 'f', plural: 'Katzen' } },
  { id: 'de/noun/pferd', lang: 'de', lemma: 'Pferd', gloss: 'horse', glossIt: 'il cavallo', glossItPl: 'i cavalli', tags: ['animal'], de: { gender: 'n', plural: 'Pferde' } },
  { id: 'de/noun/fisch', lang: 'de', lemma: 'Fisch', gloss: 'fish', glossIt: 'il pesce', glossItPl: 'i pesci', tags: ['animal', 'food'], de: { gender: 'm', plural: 'Fische' } },
  { id: 'de/noun/kuh', lang: 'de', lemma: 'Kuh', gloss: 'cow', glossIt: 'la mucca', glossItPl: 'le mucche', tags: ['animal'], de: { gender: 'f', plural: 'Kühe' } },
  { id: 'de/noun/strand', lang: 'de', lemma: 'Strand', gloss: 'beach', glossIt: 'la spiaggia', glossItPl: 'le spiagge', tags: ['nature', 'place'], de: { gender: 'm', plural: 'Strände' } },
  // high-frequency essentials
  { id: 'de/noun/sache', lang: 'de', lemma: 'Sache', gloss: 'thing', glossIt: 'la cosa', glossItPl: 'le cose', tags: ['object', 'abstract'], de: { gender: 'f', plural: 'Sachen' } },
  { id: 'de/noun/mal', lang: 'de', lemma: 'Mal', gloss: 'time (occasion)', glossIt: 'la volta', glossItPl: 'le volte', tags: ['abstract', 'time'], de: { gender: 'n', plural: 'Male' } },
  { id: 'de/noun/leben', lang: 'de', lemma: 'Leben', gloss: 'life', glossPlural: 'lives', glossIt: 'la vita', glossItPl: 'le vite', tags: ['abstract'], de: { gender: 'n', plural: 'Leben' } },
  { id: 'de/noun/welt', lang: 'de', lemma: 'Welt', gloss: 'world', glossIt: 'il mondo', glossItPl: 'i mondi', tags: ['place'], de: { gender: 'f', plural: 'Welten' } },
  { id: 'de/noun/geschichte', lang: 'de', lemma: 'Geschichte', gloss: 'story / history', glossIt: 'la storia', glossItPl: 'le storie', tags: ['abstract'], de: { gender: 'f', plural: 'Geschichten' } },
  { id: 'de/noun/licht', lang: 'de', lemma: 'Licht', gloss: 'light', glossIt: 'la luce', glossItPl: 'le luci', tags: ['object'], de: { gender: 'n', plural: 'Lichter' } },
  { id: 'de/noun/feuer', lang: 'de', lemma: 'Feuer', gloss: 'fire', glossIt: 'il fuoco', glossItPl: 'i fuochi', tags: ['nature'], de: { gender: 'n', plural: 'Feuer' } },
  { id: 'de/noun/luft', lang: 'de', lemma: 'Luft', gloss: 'air', glossIt: 'l’aria', glossItPl: 'l’aria', tags: ['nature'], de: { gender: 'f', plural: 'Lüfte' } },
  { id: 'de/noun/lärm', lang: 'de', lemma: 'Lärm', gloss: 'noise', glossIt: 'il rumore', glossItPl: 'il rumore', tags: ['abstract'], de: { gender: 'm', plural: 'Lärm' } },
  { id: 'de/noun/geruch', lang: 'de', lemma: 'Geruch', gloss: 'smell', glossIt: 'l’odore', glossItPl: 'gli odori', tags: ['abstract'], de: { gender: 'm', plural: 'Gerüche' } },
  { id: 'de/noun/farbe', lang: 'de', lemma: 'Farbe', gloss: 'color', glossIt: 'il colore', glossItPl: 'i colori', tags: ['abstract'], de: { gender: 'f', plural: 'Farben' } },
  { id: 'de/noun/form', lang: 'de', lemma: 'Form', gloss: 'shape / form', glossIt: 'la forma', glossItPl: 'le forme', tags: ['abstract'], de: { gender: 'f', plural: 'Formen' } },
  { id: 'de/noun/teil', lang: 'de', lemma: 'Teil', gloss: 'part', glossIt: 'la parte', glossItPl: 'le parti', tags: ['abstract'], de: { gender: 'm', plural: 'Teile' } },
  { id: 'de/noun/mitte', lang: 'de', lemma: 'Mitte', gloss: 'middle', glossIt: 'il centro', glossItPl: 'i centri', tags: ['place'], de: { gender: 'f', plural: 'Mitten' } },
  { id: 'de/noun/ende', lang: 'de', lemma: 'Ende', gloss: 'end', glossIt: 'la fine', glossItPl: 'le fini', tags: ['abstract'], de: { gender: 'n', plural: 'Enden' } },
  { id: 'de/noun/anfang', lang: 'de', lemma: 'Anfang', gloss: 'beginning', glossIt: 'l’inizio', glossItPl: 'gli inizi', tags: ['abstract'], de: { gender: 'm', plural: 'Anfänge' } },
]

export const DE_NOUN_BY_ID = new Map(DE_NOUNS.map((n) => [n.id, n]))
