import type { NounEntry } from '../../types'

// Starter German nouns (M5). Gender is part of the word — always taught with the article.
export const DE_NOUNS: NounEntry[] = [
  { id: 'de/noun/mann', lang: 'de', lemma: 'Mann', gloss: 'man', glossPlural: 'men', glossIt: 'l’uomo', glossItPl: 'gli uomini', tags: ['human'], de: { gender: 'm', plural: 'Männer' } },
  { id: 'de/noun/frau', lang: 'de', lemma: 'Frau', gloss: 'woman', glossPlural: 'women', glossIt: 'la donna', glossItPl: 'le donne', tags: ['human'], de: { gender: 'f', plural: 'Frauen' } },
  { id: 'de/noun/kind', lang: 'de', lemma: 'Kind', gloss: 'child', glossPlural: 'children', glossIt: 'il bambino', glossItPl: 'i bambini', tags: ['human', 'family'], de: { gender: 'n', plural: 'Kinder' } },
  { id: 'de/noun/tisch', lang: 'de', lemma: 'Tisch', gloss: 'table', glossIt: 'il tavolo', glossItPl: 'i tavoli', tags: ['object'], de: { gender: 'm', plural: 'Tische' } },
  { id: 'de/noun/tür', lang: 'de', lemma: 'Tür', gloss: 'door', glossIt: 'la porta', glossItPl: 'le porte', tags: ['object'], de: { gender: 'f', plural: 'Türen' } },
  { id: 'de/noun/buch', lang: 'de', lemma: 'Buch', gloss: 'book', glossIt: 'il libro', glossItPl: 'i libri', tags: ['object'], de: { gender: 'n', plural: 'Bücher' } },
  { id: 'de/noun/haus', lang: 'de', lemma: 'Haus', gloss: 'house', glossIt: 'la casa', glossItPl: 'le case', tags: ['place'], de: { gender: 'n', plural: 'Häuser' } },
  { id: 'de/noun/stadt', lang: 'de', lemma: 'Stadt', gloss: 'city', glossIt: 'la città', glossItPl: 'le città', tags: ['place'], de: { gender: 'f', plural: 'Städte' } },
  { id: 'de/noun/wasser', lang: 'de', lemma: 'Wasser', gloss: 'water', glossIt: 'l’acqua', glossItPl: 'le acque', tags: ['drink'], de: { gender: 'n', plural: 'Wasser' } },
  { id: 'de/noun/kaffee', lang: 'de', lemma: 'Kaffee', gloss: 'coffee', glossIt: 'il caffè', glossItPl: 'i caffè', tags: ['drink'], de: { gender: 'm', plural: 'Kaffees' } },
  { id: 'de/noun/brot', lang: 'de', lemma: 'Brot', gloss: 'bread', glossIt: 'il pane', glossItPl: 'i pani', tags: ['food'], de: { gender: 'n', plural: 'Brote' } },
  { id: 'de/noun/apfel', lang: 'de', lemma: 'Apfel', gloss: 'apple', glossIt: 'la mela', glossItPl: 'le mele', tags: ['food'], de: { gender: 'm', plural: 'Äpfel' } },
  { id: 'de/noun/student', lang: 'de', lemma: 'Student', gloss: 'student', glossIt: 'lo studente', glossItPl: 'gli studenti', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Studenten', nDeclension: true } },
  { id: 'de/noun/freund', lang: 'de', lemma: 'Freund', gloss: 'friend', glossIt: 'l’amico', glossItPl: 'gli amici', tags: ['human'], de: { gender: 'm', plural: 'Freunde' } },
  // family
  { id: 'de/noun/vater', lang: 'de', lemma: 'Vater', gloss: 'father', glossIt: 'il padre', glossItPl: 'i padri', tags: ['family', 'human'], de: { gender: 'm', plural: 'Väter' } },
  { id: 'de/noun/mutter', lang: 'de', lemma: 'Mutter', gloss: 'mother', glossIt: 'la madre', glossItPl: 'le madri', tags: ['family', 'human'], de: { gender: 'f', plural: 'Mütter' } },
  { id: 'de/noun/bruder', lang: 'de', lemma: 'Bruder', gloss: 'brother', glossIt: 'il fratello', glossItPl: 'i fratelli', tags: ['family', 'human'], de: { gender: 'm', plural: 'Brüder' } },
  { id: 'de/noun/schwester', lang: 'de', lemma: 'Schwester', gloss: 'sister', glossIt: 'la sorella', glossItPl: 'le sorelle', tags: ['family', 'human'], de: { gender: 'f', plural: 'Schwestern' } },
  { id: 'de/noun/sohn', lang: 'de', lemma: 'Sohn', gloss: 'son', glossIt: 'il figlio', glossItPl: 'i figli', tags: ['family', 'human'], de: { gender: 'm', plural: 'Söhne' } },
  { id: 'de/noun/tochter', lang: 'de', lemma: 'Tochter', gloss: 'daughter', glossIt: 'la figlia', glossItPl: 'le figlie', tags: ['family', 'human'], de: { gender: 'f', plural: 'Töchter' } },
  { id: 'de/noun/familie', lang: 'de', lemma: 'Familie', gloss: 'family', glossIt: 'la famiglia', glossItPl: 'le famiglie', tags: ['family'], de: { gender: 'f', plural: 'Familien' } },
  // people & professions
  { id: 'de/noun/lehrer', lang: 'de', lemma: 'Lehrer', gloss: 'teacher (male)', glossIt: 'il professore', glossItPl: 'i professori', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Lehrer' } },
  { id: 'de/noun/lehrerin', lang: 'de', lemma: 'Lehrerin', gloss: 'teacher (female)', glossIt: 'la professoressa', glossItPl: 'le professoresse', tags: ['human', 'profession'], de: { gender: 'f', plural: 'Lehrerinnen' } },
  { id: 'de/noun/junge', lang: 'de', lemma: 'Junge', gloss: 'boy', glossIt: 'il ragazzo', glossItPl: 'i ragazzi', tags: ['human'], de: { gender: 'm', plural: 'Jungen', nDeclension: true } },
  { id: 'de/noun/mädchen', lang: 'de', lemma: 'Mädchen', gloss: 'girl', glossIt: 'la ragazza', glossItPl: 'le ragazze', tags: ['human'], de: { gender: 'n', plural: 'Mädchen' } },
  { id: 'de/noun/arzt', lang: 'de', lemma: 'Arzt', gloss: 'doctor (male)', glossIt: 'il medico', glossItPl: 'i medici', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Ärzte' } },
  { id: 'de/noun/ärztin', lang: 'de', lemma: 'Ärztin', gloss: 'doctor (female)', glossIt: 'la dottoressa', glossItPl: 'le dottoresse', tags: ['human', 'profession'], de: { gender: 'f', plural: 'Ärztinnen' } },
  // food & drink
  { id: 'de/noun/milch', lang: 'de', lemma: 'Milch', gloss: 'milk', glossIt: 'il latte', glossItPl: 'il latte', tags: ['drink'], de: { gender: 'f', plural: 'Milch' } },
  { id: 'de/noun/käse', lang: 'de', lemma: 'Käse', gloss: 'cheese', glossIt: 'il formaggio', glossItPl: 'i formaggi', tags: ['food'], de: { gender: 'm', plural: 'Käse' } },
  { id: 'de/noun/ei', lang: 'de', lemma: 'Ei', gloss: 'egg', glossIt: 'l’uovo', glossItPl: 'le uova', tags: ['food'], de: { gender: 'n', plural: 'Eier' } },
  { id: 'de/noun/fleisch', lang: 'de', lemma: 'Fleisch', gloss: 'meat', glossIt: 'la carne', glossItPl: 'la carne', tags: ['food'], de: { gender: 'n', plural: 'Fleisch' } },
  { id: 'de/noun/reis', lang: 'de', lemma: 'Reis', gloss: 'rice', glossIt: 'il riso', glossItPl: 'il riso', tags: ['food'], de: { gender: 'm', plural: 'Reis' } },
  { id: 'de/noun/obst', lang: 'de', lemma: 'Obst', gloss: 'fruit', glossIt: 'la frutta', glossItPl: 'la frutta', tags: ['food'], de: { gender: 'n', plural: 'Obst' } },
  { id: 'de/noun/bier', lang: 'de', lemma: 'Bier', gloss: 'beer', glossIt: 'la birra', glossItPl: 'le birre', tags: ['drink'], de: { gender: 'n', plural: 'Biere' } },
  { id: 'de/noun/wein', lang: 'de', lemma: 'Wein', gloss: 'wine', glossIt: 'il vino', glossItPl: 'i vini', tags: ['drink'], de: { gender: 'm', plural: 'Weine' } },
  { id: 'de/noun/tee', lang: 'de', lemma: 'Tee', gloss: 'tea', glossIt: 'il tè', glossItPl: 'i tè', tags: ['drink'], de: { gender: 'm', plural: 'Tees' } },
  { id: 'de/noun/saft', lang: 'de', lemma: 'Saft', gloss: 'juice', glossIt: 'il succo', glossItPl: 'i succhi', tags: ['drink'], de: { gender: 'm', plural: 'Säfte' } },
  // places
  { id: 'de/noun/schule', lang: 'de', lemma: 'Schule', gloss: 'school', glossIt: 'la scuola', glossItPl: 'le scuole', tags: ['place'], de: { gender: 'f', plural: 'Schulen' } },
  { id: 'de/noun/straße', lang: 'de', lemma: 'Straße', gloss: 'street', glossIt: 'la strada', glossItPl: 'le strade', tags: ['place'], de: { gender: 'f', plural: 'Straßen' } },
  { id: 'de/noun/park', lang: 'de', lemma: 'Park', gloss: 'park', glossIt: 'il parco', glossItPl: 'i parchi', tags: ['place'], de: { gender: 'm', plural: 'Parks' } },
  { id: 'de/noun/land', lang: 'de', lemma: 'Land', gloss: 'country', glossPlural: 'countries', glossIt: 'il paese', glossItPl: 'i paesi', tags: ['place'], de: { gender: 'n', plural: 'Länder' } },
  { id: 'de/noun/dorf', lang: 'de', lemma: 'Dorf', gloss: 'village', glossIt: 'il villaggio', glossItPl: 'i villaggi', tags: ['place'], de: { gender: 'n', plural: 'Dörfer' } },
  { id: 'de/noun/bahnhof', lang: 'de', lemma: 'Bahnhof', gloss: 'train station', glossIt: 'la stazione', glossItPl: 'le stazioni', tags: ['place'], de: { gender: 'm', plural: 'Bahnhöfe' } },
  { id: 'de/noun/supermarkt', lang: 'de', lemma: 'Supermarkt', gloss: 'supermarket', glossIt: 'il supermercato', glossItPl: 'i supermercati', tags: ['place'], de: { gender: 'm', plural: 'Supermärkte' } },
  { id: 'de/noun/restaurant', lang: 'de', lemma: 'Restaurant', gloss: 'restaurant', glossIt: 'il ristorante', glossItPl: 'i ristoranti', tags: ['place'], de: { gender: 'n', plural: 'Restaurants' } },
  // everyday objects
  { id: 'de/noun/stuhl', lang: 'de', lemma: 'Stuhl', gloss: 'chair', glossIt: 'la sedia', glossItPl: 'le sedie', tags: ['object'], de: { gender: 'm', plural: 'Stühle' } },
  { id: 'de/noun/fenster', lang: 'de', lemma: 'Fenster', gloss: 'window', glossIt: 'la finestra', glossItPl: 'le finestre', tags: ['object'], de: { gender: 'n', plural: 'Fenster' } },
  { id: 'de/noun/auto', lang: 'de', lemma: 'Auto', gloss: 'car', glossIt: 'la macchina', glossItPl: 'le macchine', tags: ['vehicle'], de: { gender: 'n', plural: 'Autos' } },
  { id: 'de/noun/telefon', lang: 'de', lemma: 'Telefon', gloss: 'telephone', glossIt: 'il telefono', glossItPl: 'i telefoni', tags: ['object'], de: { gender: 'n', plural: 'Telefone' } },
  { id: 'de/noun/computer', lang: 'de', lemma: 'Computer', gloss: 'computer', glossIt: 'il computer', glossItPl: 'i computer', tags: ['object'], de: { gender: 'm', plural: 'Computer' } },
  { id: 'de/noun/handy', lang: 'de', lemma: 'Handy', gloss: 'mobile phone', glossIt: 'il cellulare', glossItPl: 'i cellulari', tags: ['object'], de: { gender: 'n', plural: 'Handys' } },
  { id: 'de/noun/tasche', lang: 'de', lemma: 'Tasche', gloss: 'bag', glossIt: 'la borsa', glossItPl: 'le borse', tags: ['object'], de: { gender: 'f', plural: 'Taschen' } },
  { id: 'de/noun/schuh', lang: 'de', lemma: 'Schuh', gloss: 'shoe', glossIt: 'la scarpa', glossItPl: 'le scarpe', tags: ['clothing'], de: { gender: 'm', plural: 'Schuhe' } },
  { id: 'de/noun/zeitung', lang: 'de', lemma: 'Zeitung', gloss: 'newspaper', glossIt: 'il giornale', glossItPl: 'i giornali', tags: ['object'], de: { gender: 'f', plural: 'Zeitungen' } },
  // time & abstract
  { id: 'de/noun/tag', lang: 'de', lemma: 'Tag', gloss: 'day', glossIt: 'il giorno', glossItPl: 'i giorni', tags: ['time'], de: { gender: 'm', plural: 'Tage' } },
  { id: 'de/noun/nacht', lang: 'de', lemma: 'Nacht', gloss: 'night', glossIt: 'la notte', glossItPl: 'le notti', tags: ['time'], de: { gender: 'f', plural: 'Nächte' } },
  { id: 'de/noun/woche', lang: 'de', lemma: 'Woche', gloss: 'week', glossIt: 'la settimana', glossItPl: 'le settimane', tags: ['time'], de: { gender: 'f', plural: 'Wochen' } },
  { id: 'de/noun/jahr', lang: 'de', lemma: 'Jahr', gloss: 'year', glossIt: 'l’anno', glossItPl: 'gli anni', tags: ['time'], de: { gender: 'n', plural: 'Jahre' } },
  { id: 'de/noun/zeit', lang: 'de', lemma: 'Zeit', gloss: 'time', glossIt: 'il tempo', glossItPl: 'i tempi', tags: ['time'], de: { gender: 'f', plural: 'Zeiten' } },
  { id: 'de/noun/sprache', lang: 'de', lemma: 'Sprache', gloss: 'language', glossIt: 'la lingua', glossItPl: 'le lingue', tags: ['abstract'], de: { gender: 'f', plural: 'Sprachen' } },
]

export const DE_NOUN_BY_ID = new Map(DE_NOUNS.map((n) => [n.id, n]))
