import type { NounEntry } from '../../types'

// Starter German nouns (M5). Gender is part of the word — always taught with the article.
export const DE_NOUNS: NounEntry[] = [
  { id: 'de/noun/mann', lang: 'de', lemma: 'Mann', gloss: 'man', glossPlural: 'men', glossIt: 'l’uomo', glossItPl: 'gli uomini', tags: ['human'], de: { gender: 'm', plural: 'Männer' } },
  { id: 'de/noun/frau', lang: 'de', lemma: 'Frau', gloss: 'woman', glossPlural: 'women', glossIt: 'la donna', glossItPl: 'le donne', tags: ['human'], de: { gender: 'f', plural: 'Frauen' } },
  { id: 'de/noun/kind', lang: 'de', lemma: 'Kind', gloss: 'child', glossPlural: 'children', glossIt: 'il bambino', glossItPl: 'i bambini', tags: ['human', 'family'], de: { gender: 'n', plural: 'Kinder' } },
  { id: 'de/noun/tisch', lang: 'de', lemma: 'Tisch', gloss: 'table', glossIt: 'il tavolo', glossItPl: 'i tavoli', tags: ['object'], de: { gender: 'm', plural: 'Tische' } },
  { id: 'de/noun/tür', lang: 'de', lemma: 'Tür', gloss: 'door', glossIt: 'la porta', glossItPl: 'le porte', tags: ['object'], de: { gender: 'f', plural: 'Türen' } },
  { id: 'de/noun/buch', lang: 'de', lemma: 'Buch', gloss: 'book', glossIt: 'il libro', glossItPl: 'i libri', tags: ['object'], de: { gender: 'n', plural: 'Bücher' } },
  { id: 'de/noun/haus', lang: 'de', lemma: 'Haus', gloss: 'house', glossIt: 'la casa', glossItPl: 'le case', tags: ['place'], de: { gender: 'n', plural: 'Häuser' } },
  { id: 'de/noun/stadt', lang: 'de', lemma: 'Stadt', gloss: 'city', glossIt: 'la città', glossItPl: 'le città', tags: ['place'], de: { gender: 'f', plural: 'Städte' } },
  { id: 'de/noun/wasser', lang: 'de', lemma: 'Wasser', gloss: 'water', glossIt: 'l’acqua', glossItPl: 'le acque', tags: ['drink'], de: { gender: 'n', plural: 'Wasser' } },
  { id: 'de/noun/kaffee', lang: 'de', lemma: 'Kaffee', gloss: 'coffee', glossIt: 'il caffè', glossItPl: 'i caffè', tags: ['drink'], de: { gender: 'm', plural: 'Kaffees' } },
  { id: 'de/noun/brot', lang: 'de', lemma: 'Brot', gloss: 'bread', glossIt: 'il pane', glossItPl: 'i pani', tags: ['food'], de: { gender: 'n', plural: 'Brote' } },
  { id: 'de/noun/apfel', lang: 'de', lemma: 'Apfel', gloss: 'apple', glossIt: 'la mela', glossItPl: 'le mele', tags: ['food'], de: { gender: 'm', plural: 'Äpfel' } },
  { id: 'de/noun/student', lang: 'de', lemma: 'Student', gloss: 'student', glossIt: 'lo studente', glossItPl: 'gli studenti', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Studenten', nDeclension: true } },
  { id: 'de/noun/freund', lang: 'de', lemma: 'Freund', gloss: 'friend', glossIt: 'l’amico', glossItPl: 'gli amici', tags: ['human'], de: { gender: 'm', plural: 'Freunde' } },
  // family
  { id: 'de/noun/vater', lang: 'de', lemma: 'Vater', gloss: 'father', glossIt: 'il padre', glossItPl: 'i padri', tags: ['family', 'human'], de: { gender: 'm', plural: 'Väter' } },
  { id: 'de/noun/mutter', lang: 'de', lemma: 'Mutter', gloss: 'mother', glossIt: 'la madre', glossItPl: 'le madri', tags: ['family', 'human'], de: { gender: 'f', plural: 'Mütter' } },
  { id: 'de/noun/bruder', lang: 'de', lemma: 'Bruder', gloss: 'brother', glossIt: 'il fratello', glossItPl: 'i fratelli', tags: ['family', 'human'], de: { gender: 'm', plural: 'Brüder' } },
  { id: 'de/noun/schwester', lang: 'de', lemma: 'Schwester', gloss: 'sister', glossIt: 'la sorella', glossItPl: 'le sorelle', tags: ['family', 'human'], de: { gender: 'f', plural: 'Schwestern' } },
  { id: 'de/noun/sohn', lang: 'de', lemma: 'Sohn', gloss: 'son', glossIt: 'il figlio', glossItPl: 'i figli', tags: ['family', 'human'], de: { gender: 'm', plural: 'Söhne' } },
  { id: 'de/noun/tochter', lang: 'de', lemma: 'Tochter', gloss: 'daughter', glossIt: 'la figlia', glossItPl: 'le figlie', tags: ['family', 'human'], de: { gender: 'f', plural: 'Töchter' } },
  { id: 'de/noun/familie', lang: 'de', lemma: 'Familie', gloss: 'family', glossIt: 'la famiglia', glossItPl: 'le famiglie', tags: ['family'], de: { gender: 'f', plural: 'Familien' } },
  // people & professions
  { id: 'de/noun/lehrer', lang: 'de', lemma: 'Lehrer', gloss: 'teacher (male)', glossIt: 'il professore', glossItPl: 'i professori', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Lehrer' } },
  { id: 'de/noun/lehrerin', lang: 'de', lemma: 'Lehrerin', gloss: 'teacher (female)', glossIt: 'la professoressa', glossItPl: 'le professoresse', tags: ['human', 'profession'], de: { gender: 'f', plural: 'Lehrerinnen' } },
  { id: 'de/noun/junge', lang: 'de', lemma: 'Junge', gloss: 'boy', glossIt: 'il ragazzo', glossItPl: 'i ragazzi', tags: ['human'], de: { gender: 'm', plural: 'Jungen', nDeclension: true } },
  { id: 'de/noun/mädchen', lang: 'de', lemma: 'Mädchen', gloss: 'girl', glossIt: 'la ragazza', glossItPl: 'le ragazze', tags: ['human'], de: { gender: 'n', plural: 'Mädchen' } },
  { id: 'de/noun/arzt', lang: 'de', lemma: 'Arzt', gloss: 'doctor (male)', glossIt: 'il medico', glossItPl: 'i medici', tags: ['human', 'profession'], de: { gender: 'm', plural: 'Ärzte' } },
  { id: 'de/noun/ärztin', lang: 'de', lemma: 'Ärztin', gloss: 'doctor (female)', glossIt: 'la dottoressa', glossItPl: 'le dottoresse', tags: ['human', 'profession'], de: { gender: 'f', plural: 'Ärztinnen' } },
  // food & drink
  { id: 'de/noun/milch', lang: 'de', lemma: 'Milch', gloss: 'milk', glossIt: 'il latte', glossItPl: 'il latte', tags: ['drink'], de: { gender: 'f', plural: 'Milch' } },
  { id: 'de/noun/käse', lang: 'de', lemma: 'Käse', gloss: 'cheese', glossIt: 'il formaggio', glossItPl: 'i formaggi', tags: ['food'], de: { gender: 'm', plural: 'Käse' } },
  { id: 'de/noun/ei', lang: 'de', lemma: 'Ei', gloss: 'egg', glossIt: 'l’uovo', glossItPl: 'le uova', tags: ['food'], de: { gender: 'n', plural: 'Eier' } },
  { id: 'de/noun/fleisch', lang: 'de', lemma: 'Fleisch', gloss: 'meat', glossIt: 'la carne', glossItPl: 'la carne', tags: ['food'], de: { gender: 'n', plural: 'Fleisch' } },
  { id: 'de/noun/reis', lang: 'de', lemma: 'Reis', gloss: 'rice', glossIt: 'il riso', glossItPl: 'il riso', tags: ['food'], de: { gender: 'm', plural: 'Reis' } },
  { id: 'de/noun/obst', lang: 'de', lemma: 'Obst', gloss: 'fruit', glossIt: 'la frutta', glossItPl: 'la frutta', tags: ['food'], de: { gender: 'n', plural: 'Obst' } },
  { id: 'de/noun/bier', lang: 'de', lemma: 'Bier', gloss: 'beer', glossIt: 'la birra', glossItPl: 'le birre', tags: ['drink'], de: { gender: 'n', plural: 'Biere' } },
  { id: 'de/noun/wein', lang: 'de', lemma: 'Wein', gloss: 'wine', glossIt: 'il vino', glossItPl: 'i vini', tags: ['drink'], de: { gender: 'm', plural: 'Weine' } },
  { id: 'de/noun/tee', lang: 'de', lemma: 'Tee', gloss: 'tea', glossIt: 'il tè', glossItPl: 'i tè', tags: ['drink'], de: { gender: 'm', plural: 'Tees' } },
  { id: 'de/noun/saft', lang: 'de', lemma: 'Saft', gloss: 'juice', glossIt: 'il succo', glossItPl: 'i succhi', tags: ['drink'], de: { gender: 'm', plural: 'Säfte' } },
  // places
  { id: 'de/noun/schule', lang: 'de', lemma: 'Schule', gloss: 'school', glossIt: 'la scuola', glossItPl: 'le scuole', tags: ['place'], de: { gender: 'f', plural: 'Schulen' } },
  { id: 'de/noun/straße', lang: 'de', lemma: 'Straße', gloss: 'street', glossIt: 'la strada', glossItPl: 'le strade', tags: ['place'], de: { gender: 'f', plural: 'Straßen' } },
  { id: 'de/noun/park', lang: 'de', lemma: 'Park', gloss: 'park', glossIt: 'il parco', glossItPl: 'i parchi', tags: ['place'], de: { gender: 'm', plural: 'Parks' } },
  { id: 'de/noun/land', lang: 'de', lemma: 'Land', gloss: 'country', glossPlural: 'countries', glossIt: 'il paese', glossItPl: 'i paesi', tags: ['place'], de: { gender: 'n', plural: 'Länder' } },
  { id: 'de/noun/dorf', lang: 'de', lemma: 'Dorf', gloss: 'village', glossIt: 'il villaggio', glossItPl: 'i villaggi', tags: ['place'], de: { gender: 'n', plural: 'Dörfer' } },
  { id: 'de/noun/bahnhof', lang: 'de', lemma: 'Bahnhof', gloss: 'train station', glossIt: 'la stazione', glossItPl: 'le stazioni', tags: ['place'], de: { gender: 'm', plural: 'Bahnhöfe' } },
  { id: 'de/noun/supermarkt', lang: 'de', lemma: 'Supermarkt', gloss: 'supermarket', glossIt: 'il supermercato', glossItPl: 'i supermercati', tags: ['place'], de: { gender: 'm', plural: 'Supermärkte' } },
  { id: 'de/noun/restaurant', lang: 'de', lemma: 'Restaurant', gloss: 'restaurant', glossIt: 'il ristorante', glossItPl: 'i ristoranti', tags: ['place'], de: { gender: 'n', plural: 'Restaurants' } },
  // everyday objects
  { id: 'de/noun/stuhl', lang: 'de', lemma: 'Stuhl', gloss: 'chair', glossIt: 'la sedia', glossItPl: 'le sedie', tags: ['object'], de: { gender: 'm', plural: 'Stühle' } },
  { id: 'de/noun/fenster', lang: 'de', lemma: 'Fenster', gloss: 'window', glossIt: 'la finestra', glossItPl: 'le finestre', tags: ['object'], de: { gender: 'n', plural: 'Fenster' } },
  { id: 'de/noun/auto', lang: 'de', lemma: 'Auto', gloss: 'car', glossIt: 'la macchina', glossItPl: 'le macchine', tags: ['vehicle'], de: { gender: 'n', plural: 'Autos' } },
  { id: 'de/noun/telefon', lang: 'de', lemma: 'Telefon', gloss: 'telephone', glossIt: 'il telefono', glossItPl: 'i telefoni', tags: ['object'], de: { gender: 'n', plural: 'Telefone' } },
  { id: 'de/noun/computer', lang: 'de', lemma: 'Computer', gloss: 'computer', glossIt: 'il computer', glossItPl: 'i computer', tags: ['object'], de: { gender: 'm', plural: 'Computer' } },
  { id: 'de/noun/handy', lang: 'de', lemma: 'Handy', gloss: 'mobile phone', glossIt: 'il cellulare', glossItPl: 'i cellulari', tags: ['object'], de: { gender: 'n', plural: 'Handys' } },
  { id: 'de/noun/tasche', lang: 'de', lemma: 'Tasche', gloss: 'bag', glossIt: 'la borsa', glossItPl: 'le borse', tags: ['object'], de: { gender: 'f', plural: 'Taschen' } },
  { id: 'de/noun/schuh', lang: 'de', lemma: 'Schuh', gloss: 'shoe', glossIt: 'la scarpa', glossItPl: 'le scarpe', tags: ['clothing'], de: { gender: 'm', plural: 'Schuhe' } },
  { id: 'de/noun/zeitung', lang: 'de', lemma: 'Zeitung', gloss: 'newspaper', glossIt: 'il giornale', glossItPl: 'i giornali', tags: ['object'], de: { gender: 'f', plural: 'Zeitungen' } },
  // time & abstract
  { id: 'de/noun/tag', lang: 'de', lemma: 'Tag', gloss: 'day', glossIt: 'il giorno', glossItPl: 'i giorni', tags: ['time'], de: { gender: 'm', plural: 'Tage' } },
  { id: 'de/noun/nacht', lang: 'de', lemma: 'Nacht', gloss: 'night', glossIt: 'la notte', glossItPl: 'le notti', tags: ['time'], de: { gender: 'f', plural: 'Nächte' } },
  { id: 'de/noun/woche', lang: 'de', lemma: 'Woche', gloss: 'week', glossIt: 'la settimana', glossItPl: 'le settimane', tags: ['time'], de: { gender: 'f', plural: 'Wochen' } },
  { id: 'de/noun/jahr', lang: 'de', lemma: 'Jahr', gloss: 'year', glossIt: 'l’anno', glossItPl: 'gli anni', tags: ['time'], de: { gender: 'n', plural: 'Jahre' } },
  { id: 'de/noun/zeit', lang: 'de', lemma: 'Zeit', gloss: 'time', glossIt: 'il tempo', glossItPl: 'i tempi', tags: ['time'], de: { gender: 'f', plural: 'Zeiten' } },
  { id: 'de/noun/sprache', lang: 'de', lemma: 'Sprache', gloss: 'language', glossIt: 'la lingua', glossItPl: 'le lingue', tags: ['abstract'], de: { gender: 'f', plural: 'Sprachen' } },
  // house & rooms
  { id: 'de/noun/küche', lang: 'de', lemma: 'Küche', gloss: 'kitchen', glossIt: 'la cucina', glossItPl: 'le cucine', tags: ['place'], de: { gender: 'f', plural: 'Küchen' } },
  { id: 'de/noun/bad', lang: 'de', lemma: 'Bad', gloss: 'bathroom', glossIt: 'il bagno', glossItPl: 'i bagni', tags: ['place'], de: { gender: 'n', plural: 'Bäder' } },
  { id: 'de/noun/schlafzimmer', lang: 'de', lemma: 'Schlafzimmer', gloss: 'bedroom', glossIt: 'la camera da letto', glossItPl: 'le camere da letto', tags: ['place'], de: { gender: 'n', plural: 'Schlafzimmer' } },
  { id: 'de/noun/wohnzimmer', lang: 'de', lemma: 'Wohnzimmer', gloss: 'living room', glossIt: 'il soggiorno', glossItPl: 'i soggiorni', tags: ['place'], de: { gender: 'n', plural: 'Wohnzimmer' } },
  { id: 'de/noun/bett', lang: 'de', lemma: 'Bett', gloss: 'bed', glossIt: 'il letto', glossItPl: 'i letti', tags: ['object'], de: { gender: 'n', plural: 'Betten' } },
  { id: 'de/noun/garten', lang: 'de', lemma: 'Garten', gloss: 'garden', glossIt: 'il giardino', glossItPl: 'i giardini', tags: ['place', 'nature'], de: { gender: 'm', plural: 'Gärten' } },
  { id: 'de/noun/spiegel', lang: 'de', lemma: 'Spiegel', gloss: 'mirror', glossIt: 'lo specchio', glossItPl: 'gli specchi', tags: ['object'], de: { gender: 'm', plural: 'Spiegel' } },
  { id: 'de/noun/lampe', lang: 'de', lemma: 'Lampe', gloss: 'lamp', glossIt: 'la lampada', glossItPl: 'le lampade', tags: ['object'], de: { gender: 'f', plural: 'Lampen' } },
  // clothes & shopping
  { id: 'de/noun/hemd', lang: 'de', lemma: 'Hemd', gloss: 'shirt', glossIt: 'la camicia', glossItPl: 'le camicie', tags: ['clothing'], de: { gender: 'n', plural: 'Hemden' } },
  { id: 'de/noun/hose', lang: 'de', lemma: 'Hose', gloss: 'trousers', glossIt: 'i pantaloni', glossItPl: 'i pantaloni', tags: ['clothing'], de: { gender: 'f', plural: 'Hosen' } },
  { id: 'de/noun/kleid', lang: 'de', lemma: 'Kleid', gloss: 'dress', glossIt: 'il vestito', glossItPl: 'i vestiti', tags: ['clothing'], de: { gender: 'n', plural: 'Kleider' } },
  { id: 'de/noun/rock', lang: 'de', lemma: 'Rock', gloss: 'skirt', glossIt: 'la gonna', glossItPl: 'le gonne', tags: ['clothing'], de: { gender: 'm', plural: 'Röcke' } },
  { id: 'de/noun/mantel', lang: 'de', lemma: 'Mantel', gloss: 'coat', glossIt: 'il cappotto', glossItPl: 'i cappotti', tags: ['clothing'], de: { gender: 'm', plural: 'Mäntel' } },
  { id: 'de/noun/jacke', lang: 'de', lemma: 'Jacke', gloss: 'jacket', glossIt: 'la giacca', glossItPl: 'le giacche', tags: ['clothing'], de: { gender: 'f', plural: 'Jacken' } },
  { id: 'de/noun/geld', lang: 'de', lemma: 'Geld', gloss: 'money', glossIt: 'i soldi', glossItPl: 'i soldi', tags: ['object'], de: { gender: 'n', plural: 'Geld' } },
  { id: 'de/noun/preis', lang: 'de', lemma: 'Preis', gloss: 'price', glossIt: 'il prezzo', glossItPl: 'i prezzi', tags: ['abstract'], de: { gender: 'm', plural: 'Preise' } },
  { id: 'de/noun/geschenk', lang: 'de', lemma: 'Geschenk', gloss: 'gift', glossIt: 'il regalo', glossItPl: 'i regali', tags: ['object'], de: { gender: 'n', plural: 'Geschenke' } },
  // travel
  { id: 'de/noun/reise', lang: 'de', lemma: 'Reise', gloss: 'trip', glossIt: 'il viaggio', glossItPl: 'i viaggi', tags: ['abstract'], de: { gender: 'f', plural: 'Reisen' } },
  { id: 'de/noun/zug', lang: 'de', lemma: 'Zug', gloss: 'train', glossIt: 'il treno', glossItPl: 'i treni', tags: ['vehicle'], de: { gender: 'm', plural: 'Züge' } },
  { id: 'de/noun/flugzeug', lang: 'de', lemma: 'Flugzeug', gloss: 'airplane', glossIt: 'l’aereo', glossItPl: 'gli aerei', tags: ['vehicle'], de: { gender: 'n', plural: 'Flugzeuge' } },
  { id: 'de/noun/flughafen', lang: 'de', lemma: 'Flughafen', gloss: 'airport', glossIt: 'l’aeroporto', glossItPl: 'gli aeroporti', tags: ['place'], de: { gender: 'm', plural: 'Flughäfen' } },
  { id: 'de/noun/hotel', lang: 'de', lemma: 'Hotel', gloss: 'hotel', glossIt: 'l’albergo', glossItPl: 'gli alberghi', tags: ['place'], de: { gender: 'n', plural: 'Hotels' } },
  { id: 'de/noun/koffer', lang: 'de', lemma: 'Koffer', gloss: 'suitcase', glossIt: 'la valigia', glossItPl: 'le valigie', tags: ['object'], de: { gender: 'm', plural: 'Koffer' } },
  { id: 'de/noun/fahrkarte', lang: 'de', lemma: 'Fahrkarte', gloss: 'ticket', glossIt: 'il biglietto', glossItPl: 'i biglietti', tags: ['object'], de: { gender: 'f', plural: 'Fahrkarten' } },
  { id: 'de/noun/meer', lang: 'de', lemma: 'Meer', gloss: 'sea', glossIt: 'il mare', glossItPl: 'i mari', tags: ['nature', 'place'], de: { gender: 'n', plural: 'Meere' } },
  { id: 'de/noun/berg', lang: 'de', lemma: 'Berg', gloss: 'mountain', glossIt: 'la montagna', glossItPl: 'le montagne', tags: ['nature', 'place'], de: { gender: 'm', plural: 'Berge' } },
  { id: 'de/noun/sonne', lang: 'de', lemma: 'Sonne', gloss: 'sun', glossIt: 'il sole', glossItPl: 'i soli', tags: ['nature'], de: { gender: 'f', plural: 'Sonnen' } },
  // daily routine & time
  { id: 'de/noun/frühstück', lang: 'de', lemma: 'Frühstück', gloss: 'breakfast', glossIt: 'la colazione', glossItPl: 'le colazioni', tags: ['food', 'daily-routine'], de: { gender: 'n', plural: 'Frühstücke' } },
  { id: 'de/noun/abendessen', lang: 'de', lemma: 'Abendessen', gloss: 'dinner', glossIt: 'la cena', glossItPl: 'le cene', tags: ['food', 'daily-routine'], de: { gender: 'n', plural: 'Abendessen' } },
  { id: 'de/noun/morgen', lang: 'de', lemma: 'Morgen', gloss: 'morning', glossIt: 'la mattina', glossItPl: 'le mattine', tags: ['time'], de: { gender: 'm', plural: 'Morgen' } },
  { id: 'de/noun/abend', lang: 'de', lemma: 'Abend', gloss: 'evening', glossIt: 'la sera', glossItPl: 'le sere', tags: ['time'], de: { gender: 'm', plural: 'Abende' } },
  { id: 'de/noun/stunde', lang: 'de', lemma: 'Stunde', gloss: 'hour', glossIt: 'l’ora', glossItPl: 'le ore', tags: ['time'], de: { gender: 'f', plural: 'Stunden' } },
  { id: 'de/noun/minute', lang: 'de', lemma: 'Minute', gloss: 'minute', glossIt: 'il minuto', glossItPl: 'i minuti', tags: ['time'], de: { gender: 'f', plural: 'Minuten' } },
]

export const DE_NOUN_BY_ID = new Map(DE_NOUNS.map((n) => [n.id, n]))
