import type { VerbEntry } from '../../types'

// Starter German lexicon (M5). Grows unit-by-unit; ids are append-only.
export const DE_VERBS: VerbEntry[] = [
  {
    id: 'de/verb/sein',
    lang: 'de',
    lemma: 'sein',
    gloss: 'to be',
    gloss3sg: 'is',
    glossIt: 'essere',
    tags: ['intransitive'],
    de: {
      aux: 'sein',
      participle: 'gewesen',
      irregular: {
        pres: { '1sg': 'bin', '2sg': 'bist', '3sg': 'ist', '1pl': 'sind', '2pl': 'seid', '3pl': 'sind' },
      },
    },
  },
  {
    id: 'de/verb/haben',
    lang: 'de',
    lemma: 'haben',
    gloss: 'to have',
    gloss3sg: 'has',
    glossIt: 'avere',
    tags: ['transitive'],
    objectTags: ['object', 'animal', 'family'],
    de: {
      aux: 'haben',
      participle: 'gehabt',
      irregular: {
        pres: { '2sg': 'hast', '3sg': 'hat' },
      },
    },
  },
  {
    id: 'de/verb/machen',
    lang: 'de',
    lemma: 'machen',
    gloss: 'to do / make',
    gloss3sg: 'does',
    glossIt: 'fare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object', 'abstract'],
    de: { aux: 'haben', participle: 'gemacht' },
  },
  {
    id: 'de/verb/wohnen',
    lang: 'de',
    lemma: 'wohnen',
    gloss: 'to live (reside)',
    gloss3sg: 'lives',
    glossIt: 'abitare',
    tags: ['intransitive', 'daily-routine'],
    de: { aux: 'haben', participle: 'gewohnt' },
  },
  {
    id: 'de/verb/kommen',
    lang: 'de',
    lemma: 'kommen',
    gloss: 'to come',
    gloss3sg: 'comes',
    glossIt: 'venire',
    tags: ['motion', 'intransitive'],
    de: { aux: 'sein', participle: 'gekommen' },
  },
  {
    id: 'de/verb/trinken',
    lang: 'de',
    lemma: 'trinken',
    gloss: 'to drink',
    gloss3sg: 'drinks',
    glossIt: 'bere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['drink'],
    de: { aux: 'haben', participle: 'getrunken' },
  },
  {
    id: 'de/verb/arbeiten',
    lang: 'de',
    lemma: 'arbeiten',
    gloss: 'to work',
    gloss3sg: 'works',
    glossIt: 'lavorare',
    tags: ['intransitive', 'daily-routine'],
    de: { aux: 'haben', participle: 'gearbeitet' },
  },
  {
    id: 'de/verb/heißen',
    lang: 'de',
    lemma: 'heißen',
    gloss: 'to be called',
    gloss3sg: 'is called',
    glossIt: 'chiamarsi',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'geheißen' },
  },
  {
    id: 'de/verb/fahren',
    lang: 'de',
    lemma: 'fahren',
    gloss: 'to drive / go (by vehicle)',
    gloss3sg: 'drives',
    glossIt: 'andare (con un mezzo)',
    tags: ['motion'],
    de: { aux: 'sein', participle: 'gefahren', vowelChange: { du: 'fährst', er: 'fährt' } },
  },
  {
    id: 'de/verb/essen',
    lang: 'de',
    lemma: 'essen',
    gloss: 'to eat',
    gloss3sg: 'eats',
    glossIt: 'mangiare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food'],
    de: { aux: 'haben', participle: 'gegessen', vowelChange: { du: 'isst', er: 'isst' } },
  },
  {
    id: 'de/verb/lesen',
    lang: 'de',
    lemma: 'lesen',
    gloss: 'to read',
    gloss3sg: 'reads',
    glossIt: 'leggere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'gelesen', vowelChange: { du: 'liest', er: 'liest' } },
  },
  {
    id: 'de/verb/schlafen',
    lang: 'de',
    lemma: 'schlafen',
    gloss: 'to sleep',
    gloss3sg: 'sleeps',
    glossIt: 'dormire',
    tags: ['intransitive', 'daily-routine'],
    de: { aux: 'haben', participle: 'geschlafen', vowelChange: { du: 'schläfst', er: 'schläft' } },
  },
  {
    id: 'de/verb/aufstehen',
    lang: 'de',
    lemma: 'aufstehen',
    gloss: 'to get up',
    gloss3sg: 'gets up',
    glossIt: 'alzarsi',
    tags: ['daily-routine', 'motion'],
    de: { aux: 'sein', participle: 'aufgestanden', separablePrefix: 'auf' },
  },
  {
    id: 'de/verb/lernen',
    lang: 'de',
    lemma: 'lernen',
    gloss: 'to learn',
    gloss3sg: 'learns',
    glossIt: 'imparare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['abstract'],
    de: { aux: 'haben', participle: 'gelernt' },
  },
  {
    id: 'de/verb/spielen',
    lang: 'de',
    lemma: 'spielen',
    gloss: 'to play',
    gloss3sg: 'plays',
    glossIt: 'giocare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'gespielt' },
  },
  {
    id: 'de/verb/kaufen',
    lang: 'de',
    lemma: 'kaufen',
    gloss: 'to buy',
    gloss3sg: 'buys',
    glossIt: 'comprare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food', 'drink', 'object', 'clothing'],
    de: { aux: 'haben', participle: 'gekauft' },
  },
  {
    id: 'de/verb/gehen',
    lang: 'de',
    lemma: 'gehen',
    gloss: 'to go / walk',
    gloss3sg: 'goes',
    glossIt: 'andare',
    tags: ['motion', 'intransitive'],
    de: { aux: 'sein', participle: 'gegangen' },
  },
  {
    id: 'de/verb/sehen',
    lang: 'de',
    lemma: 'sehen',
    gloss: 'to see',
    gloss3sg: 'sees',
    glossIt: 'vedere',
    tags: ['transitive'],
    objectTags: ['human', 'object', 'place'],
    de: { aux: 'haben', participle: 'gesehen', vowelChange: { du: 'siehst', er: 'sieht' } },
  },
  {
    id: 'de/verb/sprechen',
    lang: 'de',
    lemma: 'sprechen',
    gloss: 'to speak',
    gloss3sg: 'speaks',
    glossIt: 'parlare',
    tags: ['daily-routine'],
    objectTags: ['abstract'],
    de: { aux: 'haben', participle: 'gesprochen', vowelChange: { du: 'sprichst', er: 'spricht' } },
  },
  {
    id: 'de/verb/schreiben',
    lang: 'de',
    lemma: 'schreiben',
    gloss: 'to write',
    gloss3sg: 'writes',
    glossIt: 'scrivere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object', 'abstract'],
    de: { aux: 'haben', participle: 'geschrieben' },
  },
  {
    id: 'de/verb/hören',
    lang: 'de',
    lemma: 'hören',
    gloss: 'to hear / listen',
    gloss3sg: 'hears',
    glossIt: 'sentire',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['human', 'object'],
    de: { aux: 'haben', participle: 'gehört' },
  },
  {
    id: 'de/verb/nehmen',
    lang: 'de',
    lemma: 'nehmen',
    gloss: 'to take',
    gloss3sg: 'takes',
    glossIt: 'prendere',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    de: { aux: 'haben', participle: 'genommen', vowelChange: { du: 'nimmst', er: 'nimmt' } },
  },
  {
    id: 'de/verb/geben',
    lang: 'de',
    lemma: 'geben',
    gloss: 'to give',
    gloss3sg: 'gives',
    glossIt: 'dare',
    tags: ['transitive'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'gegeben', vowelChange: { du: 'gibst', er: 'gibt' } },
  },
  {
    id: 'de/verb/finden',
    lang: 'de',
    lemma: 'finden',
    gloss: 'to find',
    gloss3sg: 'finds',
    glossIt: 'trovare',
    tags: ['transitive'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'gefunden' },
  },
  {
    id: 'de/verb/tanzen',
    lang: 'de',
    lemma: 'tanzen',
    gloss: 'to dance',
    gloss3sg: 'dances',
    glossIt: 'ballare',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'getanzt' },
  },
  {
    id: 'de/verb/einkaufen',
    lang: 'de',
    lemma: 'einkaufen',
    gloss: 'to go shopping',
    gloss3sg: 'shops',
    glossIt: 'fare la spesa',
    tags: ['daily-routine'],
    de: { aux: 'haben', participle: 'eingekauft', separablePrefix: 'ein' },
  },
  {
    id: 'de/verb/mitkommen',
    lang: 'de',
    lemma: 'mitkommen',
    gloss: 'to come along',
    gloss3sg: 'comes along',
    glossIt: 'venire insieme',
    tags: ['motion'],
    de: { aux: 'sein', participle: 'mitgekommen', separablePrefix: 'mit' },
  },
]

export const DE_VERB_BY_ID = new Map(DE_VERBS.map((v) => [v.id, v]))
