import type { VerbEntry } from '../../types'

// Starter German lexicon (M5). Grows unit-by-unit; ids are append-only.
export const DE_VERBS: VerbEntry[] = [
  {
    id: 'de/verb/sein',
    lang: 'de',
    lemma: 'sein',
    gloss: 'to be',
    gloss3sg: 'is',
    glossIt: 'essere',
    tags: ['intransitive'],
    de: {
      aux: 'sein',
      participle: 'gewesen',
      irregular: {
        pres: { '1sg': 'bin', '2sg': 'bist', '3sg': 'ist', '1pl': 'sind', '2pl': 'seid', '3pl': 'sind' },
        praet: { '1sg': 'war', '2sg': 'warst', '3sg': 'war', '1pl': 'waren', '2pl': 'wart', '3pl': 'waren' },
      },
    },
  },
  {
    id: 'de/verb/haben',
    lang: 'de',
    lemma: 'haben',
    gloss: 'to have',
    gloss3sg: 'has',
    glossIt: 'avere',
    tags: ['transitive'],
    objectTags: ['object', 'animal', 'family'],
    de: {
      aux: 'haben',
      participle: 'gehabt',
      irregular: {
        pres: { '2sg': 'hast', '3sg': 'hat' },
        praet: { '1sg': 'hatte', '2sg': 'hattest', '3sg': 'hatte', '1pl': 'hatten', '2pl': 'hattet', '3pl': 'hatten' },
      },
    },
  },
  {
    id: 'de/verb/machen',
    lang: 'de',
    lemma: 'machen',
    gloss: 'to do / make',
    gloss3sg: 'does',
    glossIt: 'fare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object', 'abstract'],
    de: { aux: 'haben', participle: 'gemacht' },
  },
  {
    id: 'de/verb/wohnen',
    lang: 'de',
    lemma: 'wohnen',
    gloss: 'to live (reside)',
    gloss3sg: 'lives',
    glossIt: 'abitare',
    tags: ['intransitive', 'daily-routine'],
    de: { aux: 'haben', participle: 'gewohnt' },
  },
  {
    id: 'de/verb/kommen',
    lang: 'de',
    lemma: 'kommen',
    gloss: 'to come',
    gloss3sg: 'comes',
    glossIt: 'venire',
    tags: ['motion', 'intransitive'],
    de: { aux: 'sein', participle: 'gekommen' },
  },
  {
    id: 'de/verb/trinken',
    lang: 'de',
    lemma: 'trinken',
    gloss: 'to drink',
    gloss3sg: 'drinks',
    glossIt: 'bere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['drink'],
    de: { aux: 'haben', participle: 'getrunken' },
  },
  {
    id: 'de/verb/arbeiten',
    lang: 'de',
    lemma: 'arbeiten',
    gloss: 'to work',
    gloss3sg: 'works',
    glossIt: 'lavorare',
    tags: ['intransitive', 'daily-routine'],
    de: { aux: 'haben', participle: 'gearbeitet' },
  },
  {
    id: 'de/verb/heißen',
    lang: 'de',
    lemma: 'heißen',
    gloss: 'to be called',
    gloss3sg: 'is called',
    glossIt: 'chiamarsi',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'geheißen' },
  },
  {
    id: 'de/verb/fahren',
    lang: 'de',
    lemma: 'fahren',
    gloss: 'to drive / go (by vehicle)',
    gloss3sg: 'drives',
    glossIt: 'andare (con un mezzo)',
    tags: ['motion'],
    de: { aux: 'sein', participle: 'gefahren', vowelChange: { du: 'fährst', er: 'fährt' } },
  },
  {
    id: 'de/verb/essen',
    lang: 'de',
    lemma: 'essen',
    gloss: 'to eat',
    gloss3sg: 'eats',
    glossIt: 'mangiare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food'],
    de: { aux: 'haben', participle: 'gegessen', vowelChange: { du: 'isst', er: 'isst' } },
  },
  {
    id: 'de/verb/lesen',
    lang: 'de',
    lemma: 'lesen',
    gloss: 'to read',
    gloss3sg: 'reads',
    glossIt: 'leggere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'gelesen', vowelChange: { du: 'liest', er: 'liest' } },
  },
  {
    id: 'de/verb/schlafen',
    lang: 'de',
    lemma: 'schlafen',
    gloss: 'to sleep',
    gloss3sg: 'sleeps',
    glossIt: 'dormire',
    tags: ['intransitive', 'daily-routine'],
    de: { aux: 'haben', participle: 'geschlafen', vowelChange: { du: 'schläfst', er: 'schläft' } },
  },
  {
    id: 'de/verb/aufstehen',
    lang: 'de',
    lemma: 'aufstehen',
    gloss: 'to get up',
    gloss3sg: 'gets up',
    glossIt: 'alzarsi',
    tags: ['daily-routine', 'motion'],
    de: { aux: 'sein', participle: 'aufgestanden', separablePrefix: 'auf' },
  },
  {
    id: 'de/verb/lernen',
    lang: 'de',
    lemma: 'lernen',
    gloss: 'to learn',
    gloss3sg: 'learns',
    glossIt: 'imparare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['abstract'],
    de: { aux: 'haben', participle: 'gelernt' },
  },
  {
    id: 'de/verb/spielen',
    lang: 'de',
    lemma: 'spielen',
    gloss: 'to play',
    gloss3sg: 'plays',
    glossIt: 'giocare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'gespielt' },
  },
  {
    id: 'de/verb/kaufen',
    lang: 'de',
    lemma: 'kaufen',
    gloss: 'to buy',
    gloss3sg: 'buys',
    glossIt: 'comprare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food', 'drink', 'object', 'clothing'],
    de: { aux: 'haben', participle: 'gekauft' },
  },
  {
    id: 'de/verb/gehen',
    lang: 'de',
    lemma: 'gehen',
    gloss: 'to go / walk',
    gloss3sg: 'goes',
    glossIt: 'andare',
    tags: ['motion', 'intransitive'],
    de: { aux: 'sein', participle: 'gegangen' },
  },
  {
    id: 'de/verb/sehen',
    lang: 'de',
    lemma: 'sehen',
    gloss: 'to see',
    gloss3sg: 'sees',
    glossIt: 'vedere',
    tags: ['transitive'],
    objectTags: ['human', 'object', 'place'],
    de: { aux: 'haben', participle: 'gesehen', vowelChange: { du: 'siehst', er: 'sieht' } },
  },
  {
    id: 'de/verb/sprechen',
    lang: 'de',
    lemma: 'sprechen',
    gloss: 'to speak',
    gloss3sg: 'speaks',
    glossIt: 'parlare',
    tags: ['daily-routine'],
    objectTags: ['abstract'],
    de: { aux: 'haben', participle: 'gesprochen', vowelChange: { du: 'sprichst', er: 'spricht' } },
  },
  {
    id: 'de/verb/schreiben',
    lang: 'de',
    lemma: 'schreiben',
    gloss: 'to write',
    gloss3sg: 'writes',
    glossIt: 'scrivere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object', 'abstract'],
    de: { aux: 'haben', participle: 'geschrieben' },
  },
  {
    id: 'de/verb/hören',
    lang: 'de',
    lemma: 'hören',
    gloss: 'to hear / listen',
    gloss3sg: 'hears',
    glossIt: 'sentire',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['human', 'object'],
    de: { aux: 'haben', participle: 'gehört' },
  },
  {
    id: 'de/verb/nehmen',
    lang: 'de',
    lemma: 'nehmen',
    gloss: 'to take',
    gloss3sg: 'takes',
    glossIt: 'prendere',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    de: { aux: 'haben', participle: 'genommen', vowelChange: { du: 'nimmst', er: 'nimmt' } },
  },
  {
    id: 'de/verb/geben',
    lang: 'de',
    lemma: 'geben',
    gloss: 'to give',
    gloss3sg: 'gives',
    glossIt: 'dare',
    tags: ['transitive'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'gegeben', vowelChange: { du: 'gibst', er: 'gibt' } },
  },
  {
    id: 'de/verb/finden',
    lang: 'de',
    lemma: 'finden',
    gloss: 'to find',
    gloss3sg: 'finds',
    glossIt: 'trovare',
    tags: ['transitive'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'gefunden' },
  },
  {
    id: 'de/verb/tanzen',
    lang: 'de',
    lemma: 'tanzen',
    gloss: 'to dance',
    gloss3sg: 'dances',
    glossIt: 'ballare',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'getanzt' },
  },
  {
    id: 'de/verb/einkaufen',
    lang: 'de',
    lemma: 'einkaufen',
    gloss: 'to go shopping',
    gloss3sg: 'shops',
    glossIt: 'fare la spesa',
    tags: ['daily-routine'],
    de: { aux: 'haben', participle: 'eingekauft', separablePrefix: 'ein' },
  },
  {
    id: 'de/verb/mitkommen',
    lang: 'de',
    lemma: 'mitkommen',
    gloss: 'to come along',
    gloss3sg: 'comes along',
    glossIt: 'venire insieme',
    tags: ['motion'],
    de: { aux: 'sein', participle: 'mitgekommen', separablePrefix: 'mit' },
  },
  {
    id: 'de/verb/können',
    lang: 'de',
    lemma: 'können',
    gloss: 'can / to be able to',
    gloss3sg: 'can',
    glossIt: 'potere',
    tags: ['intransitive'],
    de: {
      aux: 'haben',
      participle: 'gekonnt',
      irregular: { pres: { '1sg': 'kann', '2sg': 'kannst', '3sg': 'kann' }, praet: { '1sg': 'konnte', '2sg': 'konntest', '3sg': 'konnte', '1pl': 'konnten', '2pl': 'konntet', '3pl': 'konnten' } },
    },
  },
  {
    id: 'de/verb/müssen',
    lang: 'de',
    lemma: 'müssen',
    gloss: 'must / to have to',
    gloss3sg: 'must',
    glossIt: 'dovere',
    tags: ['intransitive'],
    de: {
      aux: 'haben',
      participle: 'gemusst',
      irregular: { pres: { '1sg': 'muss', '2sg': 'musst', '3sg': 'muss' }, praet: { '1sg': 'musste', '2sg': 'musstest', '3sg': 'musste', '1pl': 'mussten', '2pl': 'musstet', '3pl': 'mussten' } },
    },
  },
  {
    id: 'de/verb/wollen',
    lang: 'de',
    lemma: 'wollen',
    gloss: 'to want',
    gloss3sg: 'wants',
    glossIt: 'volere',
    tags: ['intransitive'],
    de: {
      aux: 'haben',
      participle: 'gewollt',
      irregular: { pres: { '1sg': 'will', '2sg': 'willst', '3sg': 'will' }, praet: { '1sg': 'wollte', '2sg': 'wolltest', '3sg': 'wollte', '1pl': 'wollten', '2pl': 'wolltet', '3pl': 'wollten' } },
    },
  },
  {
    id: 'de/verb/dürfen',
    lang: 'de',
    lemma: 'dürfen',
    gloss: 'may / to be allowed to',
    gloss3sg: 'may',
    glossIt: 'potere (avere il permesso)',
    tags: ['intransitive'],
    de: {
      aux: 'haben',
      participle: 'gedurft',
      irregular: { pres: { '1sg': 'darf', '2sg': 'darfst', '3sg': 'darf' }, praet: { '1sg': 'durfte', '2sg': 'durftest', '3sg': 'durfte', '1pl': 'durften', '2pl': 'durftet', '3pl': 'durften' } },
    },
  },
  {
    id: 'de/verb/sollen',
    lang: 'de',
    lemma: 'sollen',
    gloss: 'should / to be supposed to',
    gloss3sg: 'should',
    glossIt: 'dovere (consiglio)',
    tags: ['intransitive'],
    de: {
      aux: 'haben',
      participle: 'gesollt',
      irregular: { pres: { '1sg': 'soll', '3sg': 'soll' }, praet: { '1sg': 'sollte', '2sg': 'solltest', '3sg': 'sollte', '1pl': 'sollten', '2pl': 'solltet', '3pl': 'sollten' } },
    },
  },
  {
    id: 'de/verb/möchten',
    lang: 'de',
    lemma: 'möchten',
    gloss: 'would like to',
    gloss3sg: 'would like',
    glossIt: 'volere (gradire)',
    tags: ['intransitive'],
    de: {
      aux: 'haben',
      participle: 'gemocht',
      irregular: {
        pres: { '1sg': 'möchte', '2sg': 'möchtest', '3sg': 'möchte', '1pl': 'möchten', '2pl': 'möchtet', '3pl': 'möchten' },
      },
    },
  },
  {
    id: 'de/verb/werden',
    lang: 'de',
    lemma: 'werden',
    gloss: 'to become / will',
    gloss3sg: 'becomes',
    glossIt: 'diventare',
    tags: ['intransitive'],
    de: {
      aux: 'sein',
      participle: 'geworden',
      irregular: {
        pres: { '1sg': 'werde', '2sg': 'wirst', '3sg': 'wird', '1pl': 'werden', '2pl': 'werdet', '3pl': 'werden' },
      },
    },
  },
  {
    id: 'de/verb/helfen',
    lang: 'de',
    lemma: 'helfen',
    gloss: 'to help',
    gloss3sg: 'helps',
    glossIt: 'aiutare',
    tags: ['transitive'],
    objectTags: ['human'],
    de: { aux: 'haben', participle: 'geholfen', vowelChange: { du: 'hilfst', er: 'hilft' } },
  },
  {
    id: 'de/verb/danken',
    lang: 'de',
    lemma: 'danken',
    gloss: 'to thank',
    gloss3sg: 'thanks',
    glossIt: 'ringraziare',
    tags: ['transitive'],
    objectTags: ['human'],
    de: { aux: 'haben', participle: 'gedankt' },
  },
  {
    id: 'de/verb/fragen',
    lang: 'de',
    lemma: 'fragen',
    gloss: 'to ask',
    gloss3sg: 'asks',
    glossIt: 'domandare',
    tags: ['transitive'],
    objectTags: ['human'],
    de: { aux: 'haben', participle: 'gefragt' },
  },
  {
    id: 'de/verb/antworten',
    lang: 'de',
    lemma: 'antworten',
    gloss: 'to answer',
    gloss3sg: 'answers',
    glossIt: 'rispondere',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'geantwortet' },
  },
  {
    id: 'de/verb/warten',
    lang: 'de',
    lemma: 'warten',
    gloss: 'to wait',
    gloss3sg: 'waits',
    glossIt: 'aspettare',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'gewartet' },
  },
  {
    id: 'de/verb/suchen',
    lang: 'de',
    lemma: 'suchen',
    gloss: 'to look for',
    gloss3sg: 'looks for',
    glossIt: 'cercare',
    tags: ['transitive'],
    objectTags: ['object', 'human', 'place'],
    de: { aux: 'haben', participle: 'gesucht' },
  },
  {
    id: 'de/verb/brauchen',
    lang: 'de',
    lemma: 'brauchen',
    gloss: 'to need',
    gloss3sg: 'needs',
    glossIt: 'avere bisogno di',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    de: { aux: 'haben', participle: 'gebraucht' },
  },
  {
    id: 'de/verb/bekommen',
    lang: 'de',
    lemma: 'bekommen',
    gloss: 'to receive / get',
    gloss3sg: 'gets',
    glossIt: 'ricevere',
    tags: ['transitive'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'bekommen' },
  },
  {
    id: 'de/verb/bringen',
    lang: 'de',
    lemma: 'bringen',
    gloss: 'to bring',
    gloss3sg: 'brings',
    glossIt: 'portare',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    de: { aux: 'haben', participle: 'gebracht' },
  },
  {
    id: 'de/verb/denken',
    lang: 'de',
    lemma: 'denken',
    gloss: 'to think',
    gloss3sg: 'thinks',
    glossIt: 'pensare',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'gedacht' },
  },
  {
    id: 'de/verb/wissen',
    lang: 'de',
    lemma: 'wissen',
    gloss: 'to know (a fact)',
    gloss3sg: 'knows',
    glossIt: 'sapere',
    tags: ['transitive'],
    objectTags: ['abstract'],
    de: {
      aux: 'haben',
      participle: 'gewusst',
      irregular: { pres: { '1sg': 'weiß', '2sg': 'weißt', '3sg': 'weiß' } },
    },
  },
  {
    id: 'de/verb/glauben',
    lang: 'de',
    lemma: 'glauben',
    gloss: 'to believe',
    gloss3sg: 'believes',
    glossIt: 'credere',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'geglaubt' },
  },
  {
    id: 'de/verb/lieben',
    lang: 'de',
    lemma: 'lieben',
    gloss: 'to love',
    gloss3sg: 'loves',
    glossIt: 'amare',
    tags: ['transitive'],
    objectTags: ['human'],
    de: { aux: 'haben', participle: 'geliebt' },
  },
  {
    id: 'de/verb/zeigen',
    lang: 'de',
    lemma: 'zeigen',
    gloss: 'to show',
    gloss3sg: 'shows',
    glossIt: 'mostrare',
    tags: ['transitive'],
    objectTags: ['object', 'place'],
    de: { aux: 'haben', participle: 'gezeigt' },
  },
  {
    id: 'de/verb/erklären',
    lang: 'de',
    lemma: 'erklären',
    gloss: 'to explain',
    gloss3sg: 'explains',
    glossIt: 'spiegare',
    tags: ['transitive'],
    objectTags: ['abstract'],
    de: { aux: 'haben', participle: 'erklärt' },
  },
  {
    id: 'de/verb/verstehen',
    lang: 'de',
    lemma: 'verstehen',
    gloss: 'to understand',
    gloss3sg: 'understands',
    glossIt: 'capire',
    tags: ['transitive'],
    objectTags: ['human', 'abstract'],
    de: { aux: 'haben', participle: 'verstanden' },
  },
  {
    id: 'de/verb/verkaufen',
    lang: 'de',
    lemma: 'verkaufen',
    gloss: 'to sell',
    gloss3sg: 'sells',
    glossIt: 'vendere',
    tags: ['transitive'],
    objectTags: ['object', 'clothing', 'vehicle'],
    de: { aux: 'haben', participle: 'verkauft' },
  },
  {
    id: 'de/verb/bezahlen',
    lang: 'de',
    lemma: 'bezahlen',
    gloss: 'to pay',
    gloss3sg: 'pays',
    glossIt: 'pagare',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    de: { aux: 'haben', participle: 'bezahlt' },
  },
  {
    id: 'de/verb/besuchen',
    lang: 'de',
    lemma: 'besuchen',
    gloss: 'to visit',
    gloss3sg: 'visits',
    glossIt: 'visitare',
    tags: ['transitive'],
    objectTags: ['human', 'place'],
    de: { aux: 'haben', participle: 'besucht' },
  },
  {
    id: 'de/verb/erzählen',
    lang: 'de',
    lemma: 'erzählen',
    gloss: 'to tell (a story)',
    gloss3sg: 'tells',
    glossIt: 'raccontare',
    tags: ['transitive'],
    objectTags: ['abstract'],
    de: { aux: 'haben', participle: 'erzählt' },
  },
  {
    id: 'de/verb/vergessen',
    lang: 'de',
    lemma: 'vergessen',
    gloss: 'to forget',
    gloss3sg: 'forgets',
    glossIt: 'dimenticare',
    tags: ['transitive'],
    objectTags: ['object', 'abstract'],
    de: { aux: 'haben', participle: 'vergessen', vowelChange: { du: 'vergisst', er: 'vergisst' } },
  },
  {
    id: 'de/verb/verlieren',
    lang: 'de',
    lemma: 'verlieren',
    gloss: 'to lose',
    gloss3sg: 'loses',
    glossIt: 'perdere',
    tags: ['transitive'],
    objectTags: ['object'],
    de: { aux: 'haben', participle: 'verloren' },
  },
  {
    id: 'de/verb/gewinnen',
    lang: 'de',
    lemma: 'gewinnen',
    gloss: 'to win',
    gloss3sg: 'wins',
    glossIt: 'vincere',
    tags: ['transitive'],
    objectTags: ['object', 'abstract'],
    de: { aux: 'haben', participle: 'gewonnen' },
  },
  {
    id: 'de/verb/regnen',
    lang: 'de',
    lemma: 'regnen',
    gloss: 'to rain',
    gloss3sg: 'rains',
    glossIt: 'piovere',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'geregnet' },
  },
  {
    id: 'de/verb/schneien',
    lang: 'de',
    lemma: 'schneien',
    gloss: 'to snow',
    gloss3sg: 'snows',
    glossIt: 'nevicare',
    tags: ['intransitive'],
    de: { aux: 'haben', participle: 'geschneit' },
  },
  {
    id: 'de/verb/fliegen',
    lang: 'de',
    lemma: 'fliegen',
    gloss: 'to fly',
    gloss3sg: 'flies',
    glossIt: 'volare',
    tags: ['motion', 'intransitive'],
    de: { aux: 'sein', participle: 'geflogen' },
  },
  {
    id: 'de/verb/laufen',
    lang: 'de',
    lemma: 'laufen',
    gloss: 'to run',
    gloss3sg: 'runs',
    glossIt: 'correre',
    tags: ['motion', 'intransitive'],
    de: { aux: 'sein', participle: 'gelaufen', vowelChange: { du: 'läufst', er: 'läuft' } },
  },
  {
    id: 'de/verb/schwimmen',
    lang: 'de',
    lemma: 'schwimmen',
    gloss: 'to swim',
    gloss3sg: 'swims',
    glossIt: 'nuotare',
    tags: ['motion', 'intransitive'],
    de: { aux: 'sein', participle: 'geschwommen' },
  },
  {
    id: 'de/verb/sterben',
    lang: 'de',
    lemma: 'sterben',
    gloss: 'to die',
    gloss3sg: 'dies',
    glossIt: 'morire',
    tags: ['intransitive'],
    de: { aux: 'sein', participle: 'gestorben', vowelChange: { du: 'stirbst', er: 'stirbt' } },
  },
  {
    id: 'de/verb/anrufen',
    lang: 'de',
    lemma: 'anrufen',
    gloss: 'to call (phone)',
    gloss3sg: 'calls',
    glossIt: 'telefonare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['human'],
    de: { aux: 'haben', participle: 'angerufen', separablePrefix: 'an' },
  },
]

export const DE_VERB_BY_ID = new Map(DE_VERBS.map((v) => [v.id, v]))
