import type { Topic } from '../../types'

// Unit ES-2 · El presente
// Authoring conventions (all unit files follow these):
// - ids are append-only; never rename
// - explanations: short prose, one or two tables, 2+ TTS-able examples, one callout
// - every drillItem's skill cells must appear in skillCells

export const ES_U2_TOPICS: Topic[] = [
  {
    id: 'es-present-ar',
    lang: 'es',
    title: '-ar verbs (present)',
    ruleSummary: 'Drop -ar, add -o, -as, -a, -amos, -áis, -an: hablo, hablas, habla…',
    cefr: 'A1',
    dependencies: ['es-subject-pronouns'],
    explanation: [
      {
        kind: 'prose',
        md: 'Most Spanish verbs end in **-ar**. To conjugate one, cut off **-ar** and add the ending for the person: *hablar* → *habl-* → *hablo* (I speak). The ending does the work of the pronoun, which is why Spanish usually drops *yo*, *tú*, etc.',
      },
      {
        kind: 'table',
        caption: 'hablar — present tense',
        header: ['', 'form'],
        rows: [
          ['yo', 'hablo'],
          ['tú', 'hablas'],
          ['él / ella / usted', 'habla'],
          ['nosotros/as', 'hablamos'],
          ['vosotros/as', 'habláis'],
          ['ellos / ellas / ustedes', 'hablan'],
        ],
      },
      { kind: 'example', text: 'Hablo español.', gloss: 'I speak Spanish.' },
      { kind: 'example', text: 'Trabajamos en la ciudad.', gloss: 'We work in the city.' },
      { kind: 'example', text: 'Ella habla mucho.', gloss: 'She talks a lot.' },
      {
        kind: 'callout',
        style: 'tip',
        md: 'One ending per person, always: *trabajar* works exactly like *hablar* — *trabajo, trabajas, trabaja…* Learn the six endings once and you can conjugate hundreds of verbs.',
      },
    ],
    skillCells: [
      { cellId: '1sg', label: 'yo form' },
      { cellId: '2sg', label: 'tú form' },
      { cellId: '3sg', label: 'él/ella form' },
      { cellId: '1pl', label: 'nosotros form' },
      { cellId: '2pl', label: 'vosotros form' },
      { cellId: '3pl', label: 'ellos form' },
    ],
    introLexemeIds: ['es/verb/hablar', 'es/verb/trabajar'],
    drillItems: [
      { gen: 'match-verb', verbId: 'es/verb/hablar', tense: 'pres' },
      { gen: 'conj', verbId: 'es/verb/hablar', tense: 'pres', persons: ['1sg', '2sg', '3sg'], type: 'mc' },
      { gen: 'conj', verbId: 'es/verb/trabajar', tense: 'pres', persons: ['1pl', '2pl', '3pl'], type: 'cloze' },
    ],
    errorHints: {
      wrongPerson: 'Match the ending to the person: -o (yo), -as (tú), -a (él/ella), -amos, -áis, -an.',
      wrongClass: 'This is an -ar verb — don’t borrow -er/-ir endings.',
      infinitive: '“hablar” is the dictionary form — it must be conjugated here.',
    },
  },

  {
    id: 'es-present-er-ir',
    lang: 'es',
    title: '-er/-ir verbs (present)',
    ruleSummary: '-o, -es, -e, -emos/-imos, -éis/-ís, -en — er and ir differ only in nosotros & vosotros.',
    cefr: 'A1',
    dependencies: ['es-present-ar'],
    explanation: [
      {
        kind: 'prose',
        md: 'The other two verb families end in **-er** and **-ir**. They share almost all their endings: *-o, -es, -e, …, -en*. Only two forms differ: **nosotros** (*-emos* vs *-imos*) and **vosotros** (*-éis* vs *-ís*).',
      },
      {
        kind: 'table',
        caption: 'comer & vivir — present tense',
        header: ['', 'comer (-er)', 'vivir (-ir)'],
        rows: [
          ['yo', 'como', 'vivo'],
          ['tú', 'comes', 'vives'],
          ['él / ella / usted', 'come', 'vive'],
          ['nosotros/as', 'comemos', 'vivimos'],
          ['vosotros/as', 'coméis', 'vivís'],
          ['ellos / ellas / ustedes', 'comen', 'viven'],
        ],
        highlight: [
          [3, 1],
          [3, 2],
          [4, 1],
          [4, 2],
        ],
      },
      { kind: 'example', text: 'Como pan.', gloss: 'I eat bread.' },
      { kind: 'example', text: 'Vivimos en la ciudad.', gloss: 'We live in the city.', note: '-ir: vivimos, not *vivemos' },
      { kind: 'example', text: 'Bebes café.', gloss: 'You drink coffee.' },
      {
        kind: 'callout',
        style: 'warning',
        md: 'Don’t mix the families: -ar verbs use **a**-endings (*hablas, habla*), -er/-ir verbs use **e**-endings (*comes, come*). *Tú comas* is wrong here — that vowel belongs to -ar verbs.',
      },
    ],
    skillCells: [
      { cellId: '1sg', label: 'yo form' },
      { cellId: '2sg', label: 'tú form' },
      { cellId: '3sg', label: 'él/ella form' },
      { cellId: '1pl', label: 'nosotros form' },
      { cellId: '2pl', label: 'vosotros form' },
      { cellId: '3pl', label: 'ellos form' },
    ],
    introLexemeIds: ['es/verb/comer', 'es/verb/vivir', 'es/verb/beber'],
    drillItems: [
      { gen: 'match-verb', verbId: 'es/verb/comer', tense: 'pres' },
      { gen: 'conj', verbId: 'es/verb/comer', tense: 'pres', persons: ['1sg', '2sg', '3sg'], type: 'mc' },
      { gen: 'conj', verbId: 'es/verb/vivir', tense: 'pres', persons: ['1pl', '2pl', '3pl'], type: 'mc' },
      { gen: 'conj', verbId: 'es/verb/beber', tense: 'pres', persons: ['2sg', '1pl', '3pl'], type: 'cloze' },
      { gen: 'conj', verbId: 'es/verb/vivir', tense: 'pres', persons: ['3sg', '2pl'], type: 'cloze' },
    ],
    errorHints: {
      wrongPerson: 'Endings: -o, -es, -e, -emos/-imos, -éis/-ís, -en — match the subject.',
      wrongClass: 'Careful: -ar endings (-as, -a, -amos) don’t belong on -er/-ir verbs.',
      infinitive: 'That’s the dictionary form — it needs a person ending.',
    },
  },

  {
    id: 'es-negation',
    lang: 'es',
    title: 'Negation',
    ruleSummary: 'Put no directly before the conjugated verb; double negatives (no … nada) are normal.',
    cefr: 'A1',
    dependencies: ['es-present-ar'],
    explanation: [
      {
        kind: 'prose',
        md: 'To negate a sentence, put **no** directly before the conjugated verb: *Hablo* → *No hablo*. There is no Spanish “do/does” — *no* alone does the job. And unlike English, **double negatives are correct**: *No como nada* (literally “I don’t eat nothing”) means “I don’t eat anything.”',
      },
      {
        kind: 'table',
        caption: 'Affirmative → negative',
        header: ['affirmative', 'negative'],
        rows: [
          ['Hablo español.', 'No hablo español.'],
          ['Trabajamos.', 'No trabajamos.'],
          ['Como pan.', 'No como nada.'],
        ],
      },
      { kind: 'example', text: 'No hablo francés.', gloss: 'I don’t speak French.' },
      { kind: 'example', text: 'Ella no trabaja hoy.', gloss: 'She isn’t working today.' },
      { kind: 'example', text: 'No como nada.', gloss: 'I don’t eat anything.', note: 'double negative — normal in Spanish' },
      {
        kind: 'callout',
        style: 'warning',
        md: '*No* must sit **immediately before the verb** — nothing squeezes in between, and it never goes after: *Bebo no café* is wrong; say *No bebo café*.',
      },
    ],
    skillCells: [{ cellId: 'core', label: 'negation' }],
    introLexemeIds: [],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: '“I don’t drink coffee.” — pick the correct sentence',
            answer: 'No bebo café.',
            accepted: [],
            options: [
              { text: 'No bebo café.' },
              { text: 'Bebo no café.', strategy: 'v2Violation' },
              { text: 'Bebo café no.', strategy: 'v2Violation' },
            ],
            skillIds: ['es-negation:core'],
            ttsText: 'No bebo café.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: '“We don’t work.” — pick the correct sentence',
            answer: 'No trabajamos.',
            accepted: [],
            options: [
              { text: 'No trabajamos.' },
              { text: 'Trabajamos no.', strategy: 'v2Violation' },
              { text: 'Nosotros trabajamos no.', strategy: 'v2Violation' },
            ],
            skillIds: ['es-negation:core'],
            ttsText: 'No trabajamos.',
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['Yo', '___', 'hablo', 'francés.'],
            gapIndex: 1,
            gloss: 'I don’t speak French.',
            answer: 'no',
            accepted: [],
            skillIds: ['es-negation:core'],
            ttsText: 'Yo no hablo francés.',
            strictSuffixLen: 0,
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: '“She doesn’t live in the city.” — pick the correct sentence',
            answer: 'Ella no vive en la ciudad.',
            accepted: [],
            options: [
              { text: 'Ella no vive en la ciudad.' },
              { text: 'Ella vive no en la ciudad.', strategy: 'v2Violation' },
              { text: 'No ella vive en la ciudad.', strategy: 'v2Violation' },
            ],
            skillIds: ['es-negation:core'],
            ttsText: 'Ella no vive en la ciudad.',
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['No', 'como', '___', 'por', 'la', 'mañana.'],
            gapIndex: 2,
            gloss: 'I don’t eat anything in the morning. (no … nada)',
            answer: 'nada',
            accepted: [],
            skillIds: ['es-negation:core'],
            ttsText: 'No como nada por la mañana.',
            strictSuffixLen: 0,
          },
        ],
      },
    ],
    errorHints: {
      v2Violation: 'Put “no” directly before the conjugated verb: yo no hablo.',
    },
  },

  {
    id: 'es-questions',
    lang: 'es',
    title: 'Questions',
    ruleSummary: 'Rising intonation or verb–subject inversion; question words (qué, dónde…) carry accents and ¿…?',
    cefr: 'A1',
    dependencies: ['es-present-ar'],
    explanation: [
      {
        kind: 'prose',
        md: 'Yes/no questions need no new grammar: keep the word order and raise your voice — *¿Hablas español?* — or invert verb and subject: *¿Trabaja ella hoy?* For open questions, start with a **question word**. All of them carry a written **accent**, and every question is flanked by **¿ … ?**',
      },
      {
        kind: 'table',
        caption: 'Question words',
        header: ['Spanish', 'English'],
        rows: [
          ['¿qué?', 'what?'],
          ['¿dónde?', 'where?'],
          ['¿quién?', 'who?'],
          ['¿cuándo?', 'when?'],
          ['¿cómo?', 'how?'],
          ['¿por qué?', 'why?'],
        ],
      },
      { kind: 'example', text: '¿Dónde vives?', gloss: 'Where do you live?' },
      { kind: 'example', text: '¿Hablas español?', gloss: 'Do you speak Spanish?', note: 'a statement plus ¿? and rising intonation' },
      { kind: 'example', text: '¿Por qué trabajas hoy?', gloss: 'Why are you working today?' },
      {
        kind: 'callout',
        style: 'warning',
        md: 'The accent is not decoration: *dónde* asks, *donde* doesn’t. And don’t drop the opening **¿** — Spanish questions open and close: *¿Cómo estás?*',
      },
    ],
    skillCells: [{ cellId: 'qwords', label: 'question words' }],
    introLexemeIds: [],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'match',
            lang: 'es',
            sentence: [],
            gloss: 'Match each question word with its meaning',
            answer: '',
            accepted: [],
            pairs: [
              ['qué', 'what'],
              ['dónde', 'where'],
              ['quién', 'who'],
              ['cuándo', 'when'],
              ['cómo', 'how'],
            ],
            skillIds: ['es-questions:qwords'],
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', '___', 'vives?'],
            gapIndex: 1,
            gloss: 'Where do you live?',
            answer: 'Dónde',
            accepted: [],
            options: [
              { text: 'Dónde' },
              { text: 'Qué', strategy: 'vocabConfusable' },
              { text: 'Cuándo', strategy: 'vocabConfusable' },
              { text: 'Quién', strategy: 'vocabConfusable' },
            ],
            skillIds: ['es-questions:qwords'],
            ttsText: '¿Dónde vives?',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', '___', 'comes?'],
            gapIndex: 1,
            gloss: 'What do you eat?',
            answer: 'Qué',
            accepted: [],
            options: [
              { text: 'Qué' },
              { text: 'Dónde', strategy: 'vocabConfusable' },
              { text: 'Cómo', strategy: 'vocabConfusable' },
              { text: 'Cuándo', strategy: 'vocabConfusable' },
            ],
            skillIds: ['es-questions:qwords'],
            ttsText: '¿Qué comes?',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', '___', 'trabajas?'],
            gapIndex: 1,
            gloss: 'When do you work?',
            answer: 'Cuándo',
            accepted: [],
            options: [
              { text: 'Cuándo' },
              { text: 'Dónde', strategy: 'vocabConfusable' },
              { text: 'Qué', strategy: 'vocabConfusable' },
              { text: 'Cómo', strategy: 'vocabConfusable' },
            ],
            skillIds: ['es-questions:qwords'],
            ttsText: '¿Cuándo trabajas?',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', '___', 'habla', 'español?'],
            gapIndex: 1,
            gloss: 'Who speaks Spanish?',
            answer: 'Quién',
            accepted: [],
            options: [
              { text: 'Quién' },
              { text: 'Qué', strategy: 'vocabConfusable' },
              { text: 'Cómo', strategy: 'vocabConfusable' },
              { text: 'Dónde', strategy: 'vocabConfusable' },
            ],
            skillIds: ['es-questions:qwords'],
            ttsText: '¿Quién habla español?',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', '___', 'trabajas', 'en', 'casa?'],
            gapIndex: 1,
            gloss: 'Why do you work at home?',
            answer: 'Por qué',
            accepted: [],
            options: [
              { text: 'Por qué' },
              { text: 'Porque', strategy: 'vocabConfusable' },
              { text: 'Qué', strategy: 'vocabConfusable' },
              { text: 'Cómo', strategy: 'vocabConfusable' },
            ],
            skillIds: ['es-questions:qwords'],
            ttsText: '¿Por qué trabajas en casa?',
          },
        ],
      },
    ],
    errorHints: {
      vocabConfusable: 'qué = what, dónde = where, quién = who, cuándo = when, cómo = how, por qué = why.',
    },
  },

  {
    id: 'es-estar-present',
    lang: 'es',
    title: 'Estar — to be (state/place)',
    ruleSummary: 'estoy, estás, está, estamos, estáis, están — for location and temporary states.',
    cefr: 'A1',
    dependencies: ['es-ser-present'],
    explanation: [
      {
        kind: 'prose',
        md: '**Estar** is the second “to be” — for **where** something is and **how** it is right now: location, moods, temporary states. It looks like a regular -ar verb but the *yo* form is *estoy*, and four forms carry a written accent.',
      },
      {
        kind: 'table',
        caption: 'estar — present tense',
        header: ['', 'form'],
        rows: [
          ['yo', 'estoy'],
          ['tú', 'estás'],
          ['él / ella / usted', 'está'],
          ['nosotros/as', 'estamos'],
          ['vosotros/as', 'estáis'],
          ['ellos / ellas / ustedes', 'están'],
        ],
        highlight: [
          [1, 1],
          [2, 1],
          [4, 1],
          [5, 1],
        ],
      },
      { kind: 'example', text: 'Estoy en casa.', gloss: 'I am at home.' },
      { kind: 'example', text: '¿Cómo estás?', gloss: 'How are you?' },
      { kind: 'example', text: 'Estamos en la ciudad.', gloss: 'We are in the city.' },
      {
        kind: 'callout',
        style: 'warning',
        md: 'The accents are part of the word: **estás, está, estáis, están** — writing *esta* instead of *está* turns “he is” into “this”. Only *estoy* and *estamos* go without one.',
      },
    ],
    skillCells: [
      { cellId: '1sg', label: 'yo form' },
      { cellId: '2sg', label: 'tú form' },
      { cellId: '3sg', label: 'él/ella form' },
      { cellId: '1pl', label: 'nosotros form' },
      { cellId: '2pl', label: 'vosotros form' },
      { cellId: '3pl', label: 'ellos form' },
    ],
    introLexemeIds: [],
    drillItems: [
      { gen: 'match-verb', verbId: 'es/verb/estar', tense: 'pres' },
      { gen: 'conj', verbId: 'es/verb/estar', tense: 'pres', persons: ['1sg', '2sg', '3sg'], type: 'mc' },
      { gen: 'conj', verbId: 'es/verb/estar', tense: 'pres', persons: ['1pl', '3pl'], type: 'cloze' },
    ],
    errorHints: {
      wrongPerson: 'Estar: estoy, estás, está, estamos, estáis, están — mind the accents.',
      infinitive: '“estar” is the dictionary form — it must be conjugated here.',
    },
  },

  {
    id: 'es-ser-vs-estar',
    lang: 'es',
    title: 'Ser vs estar',
    ruleSummary: 'ser = what it is (identity, origin, profession); estar = how/where it is (state, location).',
    cefr: 'A1',
    dependencies: ['es-estar-present', 'es-adj-agreement'],
    explanation: [
      {
        kind: 'prose',
        md: 'Spanish splits “to be” in two. **Ser** answers *what is it?* — identity, origin, profession, lasting traits. **Estar** answers *how is it? where is it?* — moods, temporary states, location. The adjective still agrees with the subject either way.',
      },
      {
        kind: 'table',
        caption: 'Two verbs, two questions',
        header: ['ser — what it is', 'estar — how/where it is'],
        rows: [
          ['identity: Soy Ana.', 'state: Estoy cansado.'],
          ['origin: Somos de la ciudad.', 'location: Estamos en casa.'],
          ['trait: Ella es inteligente.', 'mood: Ella está contenta.'],
        ],
      },
      { kind: 'example', text: 'Ella es inteligente.', gloss: 'She is intelligent.', note: 'a lasting trait → ser' },
      { kind: 'example', text: 'Ella está enferma.', gloss: 'She is sick.', note: 'a temporary state → estar' },
      { kind: 'example', text: 'Estamos en la casa.', gloss: 'We are in the house.', note: 'location → estar' },
      {
        kind: 'callout',
        style: 'tip',
        md: 'Quick test before you speak: *what* is it? → **ser**. *How* or *where* is it? → **estar**.',
      },
    ],
    skillCells: [{ cellId: 'core', label: 'ser vs estar choice' }],
    introLexemeIds: ['es/adj/cansado', 'es/adj/contento', 'es/adj/enfermo', 'es/adj/feliz'],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Yo', '___', 'cansado.'],
            gapIndex: 1,
            gloss: 'I am tired.',
            answer: 'estoy',
            accepted: [],
            options: [
              { text: 'estoy' },
              { text: 'soy', strategy: 'serEstarSwap' },
              { text: 'estás', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-ser-vs-estar:core'],
            ttsText: 'Yo estoy cansado.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Ella', '___', 'inteligente.'],
            gapIndex: 1,
            gloss: 'She is intelligent.',
            answer: 'es',
            accepted: [],
            options: [
              { text: 'es' },
              { text: 'está', strategy: 'serEstarSwap' },
              { text: 'eres', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-ser-vs-estar:core'],
            ttsText: 'Ella es inteligente.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Nosotros', '___', 'en', 'la', 'casa.'],
            gapIndex: 1,
            gloss: 'We are in the house.',
            answer: 'estamos',
            accepted: [],
            options: [
              { text: 'estamos' },
              { text: 'somos', strategy: 'serEstarSwap' },
              { text: 'están', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-ser-vs-estar:core'],
            ttsText: 'Nosotros estamos en la casa.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Tú', '___', 'alto.'],
            gapIndex: 1,
            gloss: 'You are tall.',
            answer: 'eres',
            accepted: [],
            options: [
              { text: 'eres' },
              { text: 'estás', strategy: 'serEstarSwap' },
            ],
            skillIds: ['es-ser-vs-estar:core'],
            ttsText: 'Tú eres alto.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Ellos', '___', 'enfermos.'],
            gapIndex: 1,
            gloss: 'They are sick.',
            answer: 'están',
            accepted: [],
            options: [
              { text: 'están' },
              { text: 'son', strategy: 'serEstarSwap' },
              { text: 'está', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-ser-vs-estar:core'],
            ttsText: 'Ellos están enfermos.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Mi', 'amigo', '___', 'de', 'la', 'ciudad.'],
            gapIndex: 2,
            gloss: 'My friend is from the city.',
            answer: 'es',
            accepted: [],
            options: [
              { text: 'es' },
              { text: 'está', strategy: 'serEstarSwap' },
            ],
            skillIds: ['es-ser-vs-estar:core'],
            ttsText: 'Mi amigo es de la ciudad.',
          },
        ],
      },
    ],
    errorHints: {
      serEstarSwap: 'What it is (identity, origin, trait) → ser; how or where it is (state, location) → estar.',
      wrongPerson: 'Right verb, wrong person — match the form to the subject.',
    },
  },
]
