import type { Topic } from '../../types'

// Unit ES-4 · La gente y las cosas
// Authoring conventions (all unit files follow these):
// - ids are append-only; never rename
// - explanations: short prose, one or two tables, 2+ TTS-able examples, one callout
// - every drillItem's skill cells must appear in skillCells

export const ES_U4_TOPICS: Topic[] = [
  {
    id: 'es-possessives',
    lang: 'es',
    title: { en: 'Possessives', it: 'I possessivi' },
    ruleSummary: {
      en: 'mi, tu, su, nuestro… agree with the thing owned — and never take an article: mi casa.',
      it: 'mi, tu, su, nuestro… concordano con la cosa posseduta — e non vogliono l’articolo: mi casa.',
    },
    cefr: 'A1',
    dependencies: ['es-plural-articles'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: 'A Spanish possessive agrees with **the thing owned**, never with the owner: *mi hermano*, *mis hermanas* — the *-s* counts the things, not the people. *Mi, tu, su* have only a singular and a plural form; *nuestro* and *vuestro* also change gender (*nuestra casa*, *nuestros libros*). And they stand **alone**, with no article in front.',
          it: 'Il possessivo spagnolo concorda con **la cosa posseduta**, mai con il possessore: *mi hermano*, *mis hermanas* — la *-s* conta le cose, non le persone. *Mi, tu, su* hanno solo una forma singolare e una plurale; *nuestro* e *vuestro* cambiano anche genere (*nuestra casa*, *nuestros libros*). E stanno **da soli**: in spagnolo l’articolo non ci va mai.',
        },
      },
      {
        kind: 'table',
        caption: { en: 'Possessive adjectives', it: 'Gli aggettivi possessivi' },
        header: [
          { en: 'owner', it: 'possessore' },
          { en: 'one thing', it: 'una cosa' },
          { en: 'several things', it: 'più cose' },
        ],
        rows: [
          [{ en: 'my', it: 'mio, mia' }, 'mi', 'mis'],
          [{ en: 'your (tú)', it: 'tuo, tua' }, 'tu', 'tus'],
          [{ en: 'his / her / your (usted)', it: 'suo, sua, Suo' }, 'su', 'sus'],
          [{ en: 'our', it: 'nostro, nostra' }, 'nuestro / nuestra', 'nuestros / nuestras'],
          [{ en: 'your (vosotros)', it: 'vostro, vostra' }, 'vuestro / vuestra', 'vuestros / vuestras'],
          [{ en: 'their / your (ustedes)', it: 'loro' }, 'su', 'sus'],
        ],
        highlight: [
          [3, 1],
          [3, 2],
          [4, 1],
          [4, 2],
        ],
      },
      {
        kind: 'table',
        caption: { en: 'No article — unlike Italian', it: 'Niente articolo — a differenza dell’italiano' },
        header: [
          { en: 'Spanish', it: 'spagnolo' },
          { en: 'Italian', it: 'italiano' },
          { en: 'English', it: 'inglese' },
        ],
        rows: [
          ['mi casa', 'la mia casa', 'my house'],
          ['tus libros', 'i tuoi libri', 'your books'],
          ['nuestra familia', 'la nostra famiglia', 'our family'],
          ['sus hermanas', 'le sue sorelle', 'his / her sisters'],
        ],
      },
      { kind: 'example', text: 'Mi casa es pequeña.', gloss: { en: 'My house is small.', it: 'La mia casa è piccola.' } },
      {
        kind: 'example',
        text: 'Nuestros libros están en la mesa.',
        gloss: { en: 'Our books are on the table.', it: 'I nostri libri sono sul tavolo.' },
        note: { en: 'nuestros: masculine plural, because libros is', it: 'nuestros: maschile plurale, perché lo è libros' },
      },
      {
        kind: 'example',
        text: 'Sus hermanas viven en Madrid.',
        gloss: { en: 'His (her, their) sisters live in Madrid.', it: 'Le sue (loro) sorelle vivono a Madrid.' },
      },
      {
        kind: 'callout',
        style: 'warning',
        md: {
          en: '*Su* is the busiest word in Spanish: **his, her, their** and formal **your** all at once — Italian *suo / loro / Suo*. Only the context tells them apart; if it really matters, Spanish adds *de él, de ella, de ellos*: *la casa de ella*. And remember: never *la mi casa* — just *mi casa*.',
          it: '*Su* è la parola più affollata dello spagnolo: vale **suo, sua, loro** e il **Suo** di cortesia tutti insieme. Solo il contesto li distingue; se serve davvero chiarire, lo spagnolo aggiunge *de él, de ella, de ellos*: *la casa de ella*. E ricorda: mai *la mi casa* — solo *mi casa*.',
        },
      },
    ],
    skillCells: [{ cellId: 'core', label: { en: 'possessives', it: 'i possessivi' } }],
    introLexemeIds: ['es/noun/casa', 'es/noun/libro', 'es/noun/hermana', 'es/noun/madre', 'es/noun/amigo'],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['___', 'casa'],
            gapIndex: 0,
            gloss: { en: 'my house', it: 'la mia casa' },
            answer: 'mi',
            accepted: [],
            skillIds: ['es-possessives:core'],
            ttsText: 'mi casa',
            strictSuffixLen: 0,
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['___', 'libros'],
            gapIndex: 0,
            gloss: { en: 'our books', it: 'i nostri libri' },
            answer: 'nuestros',
            accepted: [],
            skillIds: ['es-possessives:core'],
            ttsText: 'nuestros libros',
            strictSuffixLen: 1,
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['___', 'hermanas'],
            gapIndex: 0,
            gloss: { en: 'his sisters', it: 'le sue sorelle' },
            answer: 'sus',
            accepted: [],
            skillIds: ['es-possessives:core'],
            ttsText: 'sus hermanas',
            strictSuffixLen: 0,
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'amigos', 'son', 'simpáticos.'],
            gapIndex: 0,
            gloss: { en: 'My friends are nice.', it: 'I miei amici sono simpatici.' },
            answer: 'Mis',
            accepted: [],
            options: [
              { text: 'Mis' },
              { text: 'Mi', strategy: 'wrongNumber' },
              { text: 'Míos', strategy: 'wrongGenderArticle' },
            ],
            skillIds: ['es-possessives:core'],
            ttsText: 'Mis amigos son simpáticos.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'casa', 'es', 'grande.'],
            gapIndex: 0,
            gloss: { en: 'Our house is big.', it: 'La nostra casa è grande.' },
            answer: 'Nuestra',
            accepted: [],
            options: [
              { text: 'Nuestra' },
              { text: 'Nuestro', strategy: 'wrongGenderArticle' },
              { text: 'Nuestras', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-possessives:core'],
            ttsText: 'Nuestra casa es grande.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: {
              en: '“my mother” — pick the correct phrase',
              it: '“mia madre” — scegli la forma corretta',
            },
            answer: 'mi madre',
            accepted: [],
            options: [
              { text: 'mi madre' },
              { text: 'la mi madre', strategy: 'wrongGenderArticle' },
              { text: 'mis madre', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-possessives:core'],
            ttsText: 'mi madre',
          },
        ],
      },
    ],
    errorHints: {
      wrongNumber: {
        en: 'The possessive counts the things owned, not the owners: mi libro → mis libros, nuestra casa → nuestras casas.',
        it: 'Il possessivo conta le cose possedute, non i possessori: mi libro → mis libros, nuestra casa → nuestras casas.',
      },
      wrongGenderArticle: {
        en: 'Only nuestro/vuestro change gender (nuestra casa), and Spanish adds no article: mi madre, not *la mi madre.',
        it: 'Solo nuestro/vuestro cambiano genere (nuestra casa), e lo spagnolo non mette l’articolo: mi madre, non *la mi madre.',
      },
    },
  },

  {
    id: 'es-demonstratives',
    lang: 'es',
    title: { en: 'Demonstratives', it: 'I dimostrativi' },
    ruleSummary: {
      en: 'este/esta/estos/estas = this, these (near); ese/esa/esos/esas = that, those (further away).',
      it: 'este/esta/estos/estas = questo, questi (vicino); ese/esa/esos/esas = quello, quelli (lontano).',
    },
    cefr: 'A1',
    dependencies: ['es-adj-agreement'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: 'Demonstratives point: **este** for what is near you (*questo*), **ese** for what is further off (*quello*). Like any adjective they agree with their noun in gender and number, and like possessives they take **no article**: *este libro*, *esas camisas*.',
          it: 'I dimostrativi indicano: **este** per ciò che è vicino (*questo*), **ese** per ciò che è più lontano (*quello*). Come ogni aggettivo concordano con il nome in genere e numero e, come i possessivi, **non vogliono l’articolo**: *este libro*, *esas camisas*.',
        },
      },
      {
        kind: 'table',
        caption: { en: 'Demonstratives', it: 'I dimostrativi' },
        header: [
          '',
          { en: 'masc. sg', it: 'masch. sing.' },
          { en: 'fem. sg', it: 'femm. sing.' },
          { en: 'masc. pl', it: 'masch. plur.' },
          { en: 'fem. pl', it: 'femm. plur.' },
        ],
        rows: [
          [{ en: 'this / these (near)', it: 'questo (vicino)' }, 'este', 'esta', 'estos', 'estas'],
          [{ en: 'that / those (far)', it: 'quello (lontano)' }, 'ese', 'esa', 'esos', 'esas'],
        ],
        highlight: [
          [0, 1],
          [1, 1],
        ],
      },
      {
        kind: 'table',
        caption: { en: 'Three distances', it: 'Tre distanze' },
        header: [
          { en: 'Spanish', it: 'spagnolo' },
          { en: 'Italian', it: 'italiano' },
          { en: 'where', it: 'dove' },
        ],
        rows: [
          ['este libro', 'questo libro', { en: 'here, with me', it: 'qui, vicino a me' }],
          ['ese libro', 'quel libro', { en: 'there, near you', it: 'lì, vicino a te' }],
          ['aquel libro', 'quel libro laggiù', { en: 'over there, far from both', it: 'laggiù, lontano da entrambi' }],
        ],
      },
      { kind: 'example', text: 'Esta casa es muy bonita.', gloss: { en: 'This house is very pretty.', it: 'Questa casa è molto carina.' } },
      { kind: 'example', text: 'Esos libros son caros.', gloss: { en: 'Those books are expensive.', it: 'Quei libri sono cari.' } },
      {
        kind: 'example',
        text: '¿Qué es esto?',
        gloss: { en: 'What is this?', it: 'Che cos’è questo?' },
        note: { en: 'esto/eso: neuter, for something not yet named', it: 'esto/eso: neutro, per qualcosa di non ancora identificato' },
      },
      {
        kind: 'callout',
        style: 'tip',
        md: {
          en: 'Spanish has a third degree, **aquel/aquella/aquellos/aquellas**, for what is far from both speakers — Italian *quello laggiù*. The neuter forms *esto, eso, aquello* never take a noun: *eso no es verdad*. Written accents on *éste, ése* are no longer required.',
          it: 'Lo spagnolo ha un terzo grado, **aquel/aquella/aquellos/aquellas**, per ciò che è lontano da entrambi gli interlocutori — l’italiano *quello laggiù*. Le forme neutre *esto, eso, aquello* non accompagnano mai un nome: *eso no es verdad*. L’accento scritto su *éste, ése* non è più obbligatorio.',
        },
      },
    ],
    skillCells: [
      { cellId: 'near', label: { en: 'este — near', it: 'este — vicino' } },
      { cellId: 'far', label: { en: 'ese — far', it: 'ese — lontano' } },
    ],
    introLexemeIds: ['es/noun/casa', 'es/noun/libro', 'es/noun/camisa', 'es/noun/zapato', 'es/noun/mujer'],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'casa'],
            gapIndex: 0,
            gloss: { en: 'this house', it: 'questa casa' },
            answer: 'esta',
            accepted: [],
            options: [
              { text: 'esta' },
              { text: 'este', strategy: 'wrongGenderArticle' },
              { text: 'estas', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-demonstratives:near'],
            ttsText: 'esta casa',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'libro'],
            gapIndex: 0,
            gloss: { en: 'this book', it: 'questo libro' },
            answer: 'este',
            accepted: [],
            options: [
              { text: 'este' },
              { text: 'esta', strategy: 'wrongGenderArticle' },
              { text: 'estos', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-demonstratives:near'],
            ttsText: 'este libro',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'zapatos'],
            gapIndex: 0,
            gloss: { en: 'these shoes', it: 'queste scarpe' },
            answer: 'estos',
            accepted: [],
            options: [
              { text: 'estos' },
              { text: 'este', strategy: 'wrongNumber' },
              { text: 'estas', strategy: 'wrongGenderArticle' },
            ],
            skillIds: ['es-demonstratives:near'],
            ttsText: 'estos zapatos',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'libros'],
            gapIndex: 0,
            gloss: { en: 'those books', it: 'quei libri' },
            answer: 'esos',
            accepted: [],
            options: [
              { text: 'esos' },
              { text: 'ese', strategy: 'wrongNumber' },
              { text: 'esas', strategy: 'wrongGenderArticle' },
            ],
            skillIds: ['es-demonstratives:far'],
            ttsText: 'esos libros',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'camisas'],
            gapIndex: 0,
            gloss: { en: 'those shirts', it: 'quelle camicie' },
            answer: 'esas',
            accepted: [],
            options: [
              { text: 'esas' },
              { text: 'esa', strategy: 'wrongNumber' },
              { text: 'esos', strategy: 'wrongGenderArticle' },
            ],
            skillIds: ['es-demonstratives:far'],
            ttsText: 'esas camisas',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'mujer'],
            gapIndex: 0,
            gloss: { en: 'that woman', it: 'quella donna' },
            answer: 'esa',
            accepted: [],
            options: [
              { text: 'esa' },
              { text: 'ese', strategy: 'wrongGenderArticle' },
              { text: 'esas', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-demonstratives:far'],
            ttsText: 'esa mujer',
          },
        ],
      },
    ],
    errorHints: {
      wrongGenderArticle: {
        en: 'The demonstrative copies the noun’s gender: este libro, esta casa, esos zapatos, esas camisas.',
        it: 'Il dimostrativo copia il genere del nome: este libro, esta casa, esos zapatos, esas camisas.',
      },
      wrongNumber: {
        en: 'One thing → este/esta, ese/esa; more than one → estos/estas, esos/esas.',
        it: 'Una cosa → este/esta, ese/esa; più di una → estos/estas, esos/esas.',
      },
    },
  },

  {
    id: 'es-personal-a',
    lang: 'es',
    title: { en: 'The personal a', it: 'La a personale' },
    ruleSummary: {
      en: 'A human direct object needs a: Veo a María — but Veo la casa.',
      it: 'Un complemento oggetto umano richiede la a: Veo a María — ma Veo la casa.',
    },
    cefr: 'A1',
    dependencies: ['es-present-ar'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: 'When the direct object of a verb is a **person** (or a beloved pet), Spanish puts a little **a** in front of it: *Veo **a** María*, *Busco **a** mi amigo*. With things there is no *a*: *Veo la casa*, *Busco un libro*. The *a* adds no meaning — it just flags “this object is human”.',
          it: 'Quando il complemento oggetto di un verbo è una **persona** (o un animale caro), lo spagnolo ci mette davanti una piccola **a**: *Veo **a** María*, *Busco **a** mi amigo*. Con le cose la *a* non c’è: *Veo la casa*, *Busco un libro*. Questa *a* non aggiunge significato: segnala solo che l’oggetto è umano. **In italiano non esiste nulla del genere** — diciamo *vedo Maria*, senza preposizione: è un’abitudine tutta nuova da prendere.',
        },
      },
      {
        kind: 'table',
        caption: { en: 'People take a, things don’t', it: 'Le persone vogliono la a, le cose no' },
        header: [
          { en: 'person → with a', it: 'persona → con la a' },
          { en: 'thing → no a', it: 'cosa → senza a' },
        ],
        rows: [
          ['Veo a María.', 'Veo la casa.'],
          ['Busco a mi amigo.', 'Busco un libro.'],
          ['Llamo a mi madre.', 'Compro un regalo.'],
          ['Miran a los niños.', 'Miran la televisión.'],
        ],
      },
      { kind: 'example', text: 'Veo a María en la calle.', gloss: { en: 'I see María in the street.', it: 'Vedo Maria per strada.' } },
      {
        kind: 'example',
        text: 'Busco un libro.',
        gloss: { en: 'I am looking for a book.', it: 'Cerco un libro.' },
        note: { en: 'a thing — no personal a', it: 'una cosa — niente a personale' },
      },
      { kind: 'example', text: 'Llamo a mi madre todos los días.', gloss: { en: 'I call my mother every day.', it: 'Chiamo mia madre tutti i giorni.' } },
      {
        kind: 'callout',
        style: 'warning',
        md: {
          en: 'Italian has nothing like this, so the *a* is easy to forget — and just as easy to over-use. Two brakes: *tener* never takes it (*Tengo dos hermanos*), and an unspecified person doesn’t either (*Busco un médico* — any doctor at all).',
          it: 'L’italiano non ha nulla di simile, quindi la *a* si dimentica facilmente — e altrettanto facilmente si mette di troppo. Due freni: *tener* non la vuole mai (*Tengo dos hermanos*) e nemmeno una persona non specificata la richiede (*Busco un médico* — un medico qualsiasi).',
        },
      },
    ],
    skillCells: [{ cellId: 'core', label: { en: 'personal a', it: 'la a personale' } }],
    introLexemeIds: ['es/verb/ver', 'es/verb/buscar', 'es/verb/llamar', 'es/noun/amigo', 'es/noun/libro'],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: { en: '“I see María.” — pick the correct sentence', it: '“Vedo Maria.” — scegli la frase corretta' },
            answer: 'Veo a María.',
            accepted: [],
            options: [
              { text: 'Veo a María.' },
              { text: 'Veo María.', strategy: 'missingPersonalA' },
              { text: 'Veo a la María.', strategy: 'wrongGenderArticle' },
            ],
            skillIds: ['es-personal-a:core'],
            ttsText: 'Veo a María.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: { en: '“I am looking for my friend.” — pick the correct sentence', it: '“Cerco il mio amico.” — scegli la frase corretta' },
            answer: 'Busco a mi amigo.',
            accepted: [],
            options: [
              { text: 'Busco a mi amigo.' },
              { text: 'Busco mi amigo.', strategy: 'missingPersonalA' },
              { text: 'Busco a mis amigo.', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-personal-a:core'],
            ttsText: 'Busco a mi amigo.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: { en: '“I am looking for a book.” — pick the correct sentence', it: '“Cerco un libro.” — scegli la frase corretta' },
            answer: 'Busco un libro.',
            accepted: [],
            options: [
              { text: 'Busco un libro.' },
              { text: 'Busco a un libro.', strategy: 'missingPersonalA' },
              { text: 'Busco un libros.', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-personal-a:core'],
            ttsText: 'Busco un libro.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: { en: '“I see the house.” — pick the correct sentence', it: '“Vedo la casa.” — scegli la frase corretta' },
            answer: 'Veo la casa.',
            accepted: [],
            options: [
              { text: 'Veo la casa.' },
              { text: 'Veo a la casa.', strategy: 'missingPersonalA' },
              { text: 'Veo las casa.', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-personal-a:core'],
            ttsText: 'Veo la casa.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: { en: '“I call my mother.” — pick the correct sentence', it: '“Chiamo mia madre.” — scegli la frase corretta' },
            answer: 'Llamo a mi madre.',
            accepted: [],
            options: [
              { text: 'Llamo a mi madre.' },
              { text: 'Llamo mi madre.', strategy: 'missingPersonalA' },
              { text: 'Llamo a mis madre.', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-personal-a:core'],
            ttsText: 'Llamo a mi madre.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___'],
            gapIndex: 0,
            gloss: { en: '“They watch the children.” — pick the correct sentence', it: '“Guardano i bambini.” — scegli la frase corretta' },
            answer: 'Miran a los niños.',
            accepted: [],
            options: [
              { text: 'Miran a los niños.' },
              { text: 'Miran los niños.', strategy: 'missingPersonalA' },
              { text: 'Miran a el niños.', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-personal-a:core'],
            ttsText: 'Miran a los niños.',
          },
        ],
      },
    ],
    errorHints: {
      missingPersonalA: {
        en: 'A human direct object takes a (Veo a María); a thing does not (Veo la casa) — and never add a to an object that isn’t a person.',
        it: 'Un oggetto umano vuole la a (Veo a María); una cosa no (Veo la casa) — e non mettere mai la a davanti a un oggetto che non sia una persona.',
      },
      wrongGenderArticle: {
        en: 'Proper names take no article in Spanish: Veo a María, not *a la María.',
        it: 'In spagnolo i nomi propri non prendono l’articolo: Veo a María, non *a la María.',
      },
      wrongNumber: {
        en: 'The article and the possessive must match the noun: a mi amigo, a los niños.',
        it: 'L’articolo e il possessivo devono concordare con il nome: a mi amigo, a los niños.',
      },
    },
  },

  {
    id: 'es-dop',
    lang: 'es',
    title: { en: 'Direct object pronouns', it: 'I pronomi diretti' },
    ruleSummary: {
      en: 'lo, la, los, las, me, te, nos, os — they stand before the conjugated verb: Lo veo.',
      it: 'lo, la, los, las, me, te, nos, os — stanno prima del verbo coniugato: Lo veo.',
    },
    cefr: 'A2',
    dependencies: ['es-personal-a'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: 'Instead of repeating the object, replace it with a pronoun: *¿El libro? **Lo** leo.* The third-person forms agree with the noun they replace (*lo, la, los, las*), and the pronoun goes **before the conjugated verb** — exactly as in Italian *lo vedo*, *non la conosco*.',
          it: 'Invece di ripetere l’oggetto, lo si sostituisce con un pronome: *¿El libro? **Lo** leo.* Le forme di terza persona concordano con il nome che sostituiscono (*lo, la, los, las*) e il pronome va **prima del verbo coniugato** — esattamente come in italiano: *lo vedo*, *non la conosco*.',
        },
      },
      {
        kind: 'table',
        caption: { en: 'Direct object pronouns', it: 'I pronomi diretti' },
        header: [
          { en: 'meaning', it: 'significato' },
          { en: 'pronoun', it: 'pronome' },
          { en: 'example', it: 'esempio' },
        ],
        rows: [
          [{ en: 'me', it: 'mi' }, 'me', 'Me ves.'],
          [{ en: 'you (tú)', it: 'ti' }, 'te', 'Te veo.'],
          [{ en: 'him / it (m) / you (usted)', it: 'lo' }, 'lo', 'Lo veo.'],
          [{ en: 'her / it (f) / you (usted)', it: 'la' }, 'la', 'La veo.'],
          [{ en: 'us', it: 'ci' }, 'nos', 'Nos ven.'],
          [{ en: 'you (vosotros)', it: 'vi' }, 'os', 'Os veo.'],
          [{ en: 'them (m) / you (ustedes)', it: 'li' }, 'los', 'Los compro.'],
          [{ en: 'them (f) / you (ustedes)', it: 'le' }, 'las', 'Las compro.'],
        ],
        highlight: [
          [2, 1],
          [3, 1],
          [6, 1],
          [7, 1],
        ],
      },
      {
        kind: 'table',
        caption: { en: 'Where the pronoun goes', it: 'Dove va il pronome' },
        header: [
          { en: 'Spanish', it: 'spagnolo' },
          { en: 'Italian', it: 'italiano' },
        ],
        rows: [
          ['Lo veo.', 'Lo vedo.'],
          ['No la conozco.', 'Non la conosco.'],
          ['Voy a comprarlo. / Lo voy a comprar.', 'Vado a comprarlo. / Lo vado a comprare.'],
        ],
      },
      { kind: 'example', text: '¿El libro? Lo leo esta noche.', gloss: { en: 'The book? I’ll read it tonight.', it: 'Il libro? Lo leggo stasera.' } },
      { kind: 'example', text: '¿Las manzanas? Las como por la mañana.', gloss: { en: 'The apples? I eat them in the morning.', it: 'Le mele? Le mangio la mattina.' } },
      {
        kind: 'example',
        text: 'No la conozco.',
        gloss: { en: 'I don’t know her.', it: 'Non la conosco.' },
        note: { en: 'no comes first, then the pronoun, then the verb', it: 'prima no, poi il pronome, poi il verbo' },
      },
      {
        kind: 'callout',
        style: 'tip',
        md: {
          en: 'Placement is the same as in Italian, so trust your ear: before the conjugated verb, and attached to an infinitive if you prefer (*quiero verlo* = *lo quiero ver*, like *voglio vederlo* = *lo voglio vedere*). Watch the gender, though: *la camisa* → *la*, even though Italian says *la camicia*, and *los zapatos* → *los*, where Italian has *le scarpe*.',
          it: 'La posizione è identica all’italiano, quindi fidati dell’orecchio: prima del verbo coniugato, oppure attaccato all’infinito (*quiero verlo* = *lo quiero ver*, come *voglio vederlo* = *lo voglio vedere*). Attenzione però al genere: *los zapatos* → *los*, mentre in italiano diresti *le scarpe*.',
        },
      },
    ],
    skillCells: [
      { cellId: 'forms', label: { en: 'choosing the pronoun', it: 'scelta del pronome' } },
      { cellId: 'placement', label: { en: 'pronoun placement', it: 'posizione del pronome' } },
    ],
    introLexemeIds: ['es/verb/ver', 'es/verb/comprar', 'es/verb/leer', 'es/noun/libro', 'es/noun/manzana'],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['¿', 'El', 'libro?', '___', 'leo.'],
            gapIndex: 3,
            gloss: { en: 'The book? I read it.', it: 'Il libro? Lo leggo.' },
            answer: 'Lo',
            accepted: [],
            skillIds: ['es-dop:forms'],
            ttsText: '¿El libro? Lo leo.',
            strictSuffixLen: 0,
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['¿', 'Las', 'manzanas?', '___', 'como.'],
            gapIndex: 3,
            gloss: { en: 'The apples? I eat them.', it: 'Le mele? Le mangio.' },
            answer: 'Las',
            accepted: [],
            skillIds: ['es-dop:forms'],
            ttsText: '¿Las manzanas? Las como.',
            strictSuffixLen: 0,
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', 'La', 'camisa?', '___', 'compro', 'mañana.'],
            gapIndex: 3,
            gloss: { en: 'The shirt? I’ll buy it tomorrow.', it: 'La camicia? La compro domani.' },
            answer: 'La',
            accepted: [],
            options: [
              { text: 'La' },
              { text: 'Lo', strategy: 'wrongGenderArticle' },
              { text: 'Las', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-dop:forms'],
            ttsText: '¿La camisa? La compro mañana.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', 'Los', 'zapatos?', 'No', '___', 'llevo.'],
            gapIndex: 4,
            gloss: { en: 'The shoes? I don’t wear them.', it: 'Le scarpe? Non le porto.' },
            answer: 'los',
            accepted: [],
            options: [
              { text: 'los' },
              { text: 'las', strategy: 'wrongGenderArticle' },
              { text: 'lo', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-dop:forms'],
            ttsText: '¿Los zapatos? No los llevo.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Mi', 'madre', '___', 'llama', 'todos', 'los', 'días.'],
            gapIndex: 2,
            gloss: { en: 'My mother calls me every day.', it: 'Mia madre mi chiama tutti i giorni.' },
            answer: 'me',
            accepted: [],
            options: [
              { text: 'me' },
              { text: 'te', strategy: 'wrongPerson' },
              { text: 'nos', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-dop:forms'],
            ttsText: 'Mi madre me llama todos los días.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', 'Ves', 'a', 'Juan?', 'Sí,', '___', 'veo.'],
            gapIndex: 5,
            gloss: { en: 'Do you see Juan? Yes, I see him.', it: 'Vedi Juan? Sì, lo vedo.' },
            answer: 'lo',
            accepted: ['le'],
            options: [
              { text: 'lo' },
              { text: 'la', strategy: 'wrongGenderArticle' },
              { text: 'los', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-dop:forms'],
            ttsText: '¿Ves a Juan? Sí, lo veo.',
          },
        ],
      },
      {
        gen: 'word-order',
        items: [
          { answer: 'Lo veo', gloss: { en: 'I see it', it: 'Lo vedo' }, cellId: 'placement' },
          { answer: 'No la conozco', gloss: { en: 'I don’t know her', it: 'Non la conosco' }, cellId: 'placement' },
        ],
      },
    ],
    errorHints: {
      wrongGenderArticle: {
        en: 'The pronoun copies the gender of the Spanish noun: la camisa → la, el libro → lo, los zapatos → los.',
        it: 'Il pronome copia il genere del nome spagnolo: la camisa → la, el libro → lo, los zapatos → los.',
      },
      wrongNumber: {
        en: 'One thing → lo/la; several → los/las. Same for me vs nos.',
        it: 'Una cosa → lo/la; più cose → los/las. Lo stesso vale per me e nos.',
      },
      wrongPerson: {
        en: 'Ask who is on the receiving end: me (me), te (you), nos (us), os (you all).',
        it: 'Chiediti chi riceve l’azione: me (me), te (te), nos (noi), os (voi).',
      },
    },
  },

  {
    id: 'es-iop',
    lang: 'es',
    title: { en: 'Indirect object pronouns', it: 'I pronomi indiretti' },
    ruleSummary: {
      en: 'me, te, le, nos, os, les — the person you give, say or write to.',
      it: 'me, te, le, nos, os, les — la persona a cui dai, dici o scrivi qualcosa.',
    },
    cefr: 'A2',
    dependencies: ['es-dop'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: 'The indirect object is the person **to whom** something happens: *Le escribo* — I write **to him/her**. Only the third person differs from the direct pronouns: **le** and **les** instead of *lo/la/los/las*, and they have no gender. Placement is the same: before the conjugated verb.',
          it: 'Il complemento di termine è la persona **a cui** succede qualcosa: *Le escribo* — gli/le scrivo. Solo la terza persona è diversa dai pronomi diretti: **le** e **les** al posto di *lo/la/los/las*, e non hanno genere. La posizione è la stessa: prima del verbo coniugato.',
        },
      },
      {
        kind: 'table',
        caption: { en: 'Indirect object pronouns', it: 'I pronomi indiretti' },
        header: [
          { en: 'to whom', it: 'a chi' },
          { en: 'pronoun', it: 'pronome' },
          { en: 'example', it: 'esempio' },
        ],
        rows: [
          [{ en: 'to me', it: 'a me → mi' }, 'me', 'Me dan dinero.'],
          [{ en: 'to you (tú)', it: 'a te → ti' }, 'te', 'Te digo la verdad.'],
          [{ en: 'to him / her / you (usted)', it: 'a lui, a lei → gli, le' }, 'le', 'Le escribo.'],
          [{ en: 'to us', it: 'a noi → ci' }, 'nos', 'Nos compra un regalo.'],
          [{ en: 'to you (vosotros)', it: 'a voi → vi' }, 'os', 'Os doy el libro.'],
          [{ en: 'to them / you (ustedes)', it: 'a loro → gli' }, 'les', 'Les hablo.'],
        ],
        highlight: [
          [2, 1],
          [5, 1],
        ],
      },
      {
        kind: 'table',
        caption: { en: 'lo/la (what?) vs le (to whom?)', it: 'lo/la (che cosa?) contro le (a chi?)' },
        header: [
          { en: 'direct — what / whom?', it: 'diretto — che cosa / chi?' },
          { en: 'indirect — to whom?', it: 'indiretto — a chi?' },
        ],
        rows: [
          [
            { en: 'Lo veo — I see him.', it: 'Lo veo — lo vedo.' },
            { en: 'Le hablo — I talk to him.', it: 'Le hablo — gli parlo.' },
          ],
          [
            { en: 'La llamo — I call her.', it: 'La llamo — la chiamo.' },
            { en: 'Le doy un regalo — I give her a present.', it: 'Le doy un regalo — le do un regalo.' },
          ],
          [
            { en: 'Los conozco — I know them.', it: 'Los conozco — li conosco.' },
            { en: 'Les escribo — I write to them.', it: 'Les escribo — scrivo loro.' },
          ],
        ],
      },
      { kind: 'example', text: 'Le escribo a mi madre.', gloss: { en: 'I write to my mother.', it: 'Scrivo a mia madre.' } },
      { kind: 'example', text: 'Mis padres me dan dinero.', gloss: { en: 'My parents give me money.', it: 'I miei genitori mi danno dei soldi.' } },
      {
        kind: 'example',
        text: 'Les hablo a mis amigos.',
        gloss: { en: 'I speak to my friends.', it: 'Parlo ai miei amici.' },
        note: { en: 'the pronoun stays even though the people are named', it: 'il pronome resta anche se le persone sono nominate' },
      },
      {
        kind: 'callout',
        style: 'warning',
        md: {
          en: 'Spanish doubles up: *Le escribo **a mi madre*** keeps the pronoun even when the person is spelled out — Italian would just say *Scrivo a mia madre*. Dropping the *le* sounds wrong to a Spanish ear. Since *le* covers him, her and you (usted), the *a + person* phrase is also what removes the ambiguity.',
          it: 'Lo spagnolo raddoppia: *Le escribo **a mi madre*** mantiene il pronome anche quando la persona è già nominata — in italiano diresti semplicemente *Scrivo a mia madre*. Omettere *le* suona sbagliato a un orecchio spagnolo. E poiché *le* vale per lui, lei e Lei di cortesia, è proprio il gruppo *a + persona* a togliere l’ambiguità.',
        },
      },
    ],
    skillCells: [{ cellId: 'core', label: { en: 'indirect object pronouns', it: 'i pronomi indiretti' } }],
    introLexemeIds: ['es/verb/dar', 'es/verb/escribir', 'es/verb/decir', 'es/noun/madre', 'es/noun/dinero'],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['___', 'escribo', 'a', 'mi', 'madre.'],
            gapIndex: 0,
            gloss: { en: 'I write to my mother.', it: 'Scrivo a mia madre.' },
            answer: 'Le',
            accepted: [],
            skillIds: ['es-iop:core'],
            ttsText: 'Le escribo a mi madre.',
            strictSuffixLen: 0,
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['Mis', 'padres', '___', 'dan', 'dinero.'],
            gapIndex: 2,
            gloss: { en: 'My parents give me money.', it: 'I miei genitori mi danno dei soldi.' },
            answer: 'me',
            accepted: [],
            skillIds: ['es-iop:core'],
            ttsText: 'Mis padres me dan dinero.',
            strictSuffixLen: 0,
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['___', 'hablo', 'a', 'mis', 'amigos.'],
            gapIndex: 0,
            gloss: { en: 'I speak to my friends.', it: 'Parlo ai miei amici.' },
            answer: 'Les',
            accepted: [],
            skillIds: ['es-iop:core'],
            ttsText: 'Les hablo a mis amigos.',
            strictSuffixLen: 1,
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', '___', 'digo', 'la', 'verdad?'],
            gapIndex: 1,
            gloss: { en: 'Shall I tell you the truth?', it: 'Ti dico la verità?' },
            answer: 'Te',
            accepted: [],
            options: [
              { text: 'Te' },
              { text: 'Le', strategy: 'wrongPerson' },
              { text: 'Os', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-iop:core'],
            ttsText: '¿Te digo la verdad?',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'doy', 'un', 'regalo', 'a', 'mi', 'hermana.'],
            gapIndex: 0,
            gloss: { en: 'I give my sister a present.', it: 'Do un regalo a mia sorella.' },
            answer: 'Le',
            accepted: [],
            options: [
              { text: 'Le' },
              { text: 'La', strategy: 'vocabConfusable' },
              { text: 'Les', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-iop:core'],
            ttsText: 'Le doy un regalo a mi hermana.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Mi', 'amigo', '___', 'compra', 'un', 'regalo.'],
            gapIndex: 2,
            gloss: { en: 'My friend buys us a present.', it: 'Il mio amico ci compra un regalo.' },
            answer: 'nos',
            accepted: [],
            options: [
              { text: 'nos' },
              { text: 'os', strategy: 'wrongPerson' },
              { text: 'me', strategy: 'wrongNumber' },
            ],
            skillIds: ['es-iop:core'],
            ttsText: 'Mi amigo nos compra un regalo.',
          },
        ],
      },
    ],
    errorHints: {
      wrongPerson: {
        en: 'Ask “to whom?”: me (to me), te (to you), le (to him/her), nos (to us), os (to you all), les (to them).',
        it: 'Chiediti “a chi?”: me (a me), te (a te), le (a lui/lei), nos (a noi), os (a voi), les (a loro).',
      },
      wrongNumber: {
        en: 'One person → le; more than one → les. Same for me vs nos, te vs os.',
        it: 'Una persona → le; più persone → les. Lo stesso vale per me e nos, te e os.',
      },
      vocabConfusable: {
        en: 'lo/la answer “what?”, le/les answer “to whom?”: La llamo (I call her) but Le doy un regalo (I give her a present).',
        it: 'lo/la rispondono a “che cosa?”, le/les a “a chi?”: La llamo (la chiamo) ma Le doy un regalo (le do un regalo).',
      },
    },
  },

  {
    id: 'es-gustar',
    lang: 'es',
    title: { en: 'Gustar-type verbs', it: 'I verbi come gustar' },
    ruleSummary: {
      en: 'me gusta el café — the thing liked is the subject: gusta + one thing or an infinitive, gustan + several.',
      it: 'me gusta el café — la cosa che piace è il soggetto: gusta + una cosa o un infinito, gustan + più cose.',
    },
    cefr: 'A2',
    dependencies: ['es-iop'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: '*Me gusta el café* does not mean “I like coffee” word by word — it means “coffee is pleasing **to me**”. The liked thing is the **subject**, so the verb agrees with **it**, not with you: **gusta** before one thing or an infinitive, **gustan** before several. The person doing the liking is an indirect pronoun: *me, te, le, nos, os, les*.',
          it: '*Me gusta el café* non è “io amo il caffè” parola per parola: è “il caffè piace **a me**”. La cosa che piace è il **soggetto**, quindi il verbo concorda con **essa**, non con te: **gusta** davanti a una cosa sola o a un infinito, **gustan** davanti a più cose. Chi prova il gradimento è un pronome indiretto: *me, te, le, nos, os, les*. In altre parole: funziona **esattamente come “mi piace / mi piacciono”** — hai già tutto il meccanismo in testa.',
        },
      },
      {
        kind: 'table',
        caption: { en: 'gustar — one verb, two forms', it: 'gustar — un verbo, due forme' },
        header: [
          { en: 'to whom', it: 'a chi' },
          { en: '+ one thing / an action', it: '+ una cosa / un’azione' },
          { en: '+ several things', it: '+ più cose' },
        ],
        rows: [
          ['me', 'me gusta el café', 'me gustan los libros'],
          ['te', 'te gusta el café', 'te gustan los libros'],
          ['le', 'le gusta el café', 'le gustan los libros'],
          ['nos', 'nos gusta el café', 'nos gustan los libros'],
          ['os', 'os gusta el café', 'os gustan los libros'],
          ['les', 'les gusta el café', 'les gustan los libros'],
        ],
        highlight: [
          [0, 1],
          [0, 2],
        ],
      },
      {
        kind: 'table',
        caption: { en: 'Exactly like Italian piacere', it: 'Esattamente come il verbo piacere' },
        header: [
          { en: 'Spanish', it: 'spagnolo' },
          { en: 'Italian', it: 'italiano' },
          { en: 'English', it: 'inglese' },
        ],
        rows: [
          ['Me gusta el café.', 'Mi piace il caffè.', 'I like coffee.'],
          ['Me gustan las manzanas.', 'Mi piacciono le mele.', 'I like apples.'],
          ['Nos gusta bailar.', 'Ci piace ballare.', 'We like dancing.'],
          ['A ella le encanta viajar.', 'A lei piace moltissimo viaggiare.', 'She loves travelling.'],
        ],
      },
      { kind: 'example', text: 'Me gusta el café.', gloss: { en: 'I like coffee.', it: 'Mi piace il caffè.' } },
      {
        kind: 'example',
        text: 'Me gustan los libros de historia.',
        gloss: { en: 'I like history books.', it: 'Mi piacciono i libri di storia.' },
        note: { en: 'plural thing → gustan', it: 'cosa al plurale → gustan' },
      },
      { kind: 'example', text: '¿Te gusta bailar?', gloss: { en: 'Do you like dancing?', it: 'Ti piace ballare?' } },
      {
        kind: 'callout',
        style: 'tip',
        md: {
          en: 'Italian gives you this one for free: *mi piace / mi piacciono* is the same machine. Two extras: an infinitive always counts as singular (*me gusta viajar*, *mi piace viaggiare*), and you can add *a él, a ella, a mis padres* at the front to say who — *A ella le gustan las manzanas*. *Encantar* works identically and means “to love it”: *me encanta*.',
          it: 'L’italiano ti regala questo argomento: *mi piace / mi piacciono* è lo stesso meccanismo. Due dettagli: l’infinito conta sempre come singolare (*me gusta viajar*, *mi piace viaggiare*) e puoi aggiungere davanti *a él, a ella, a mis padres* per dire a chi — *A ella le gustan las manzanas*. *Encantar* funziona allo stesso modo e vale “piacere moltissimo”: *me encanta*.',
        },
      },
    ],
    skillCells: [
      { cellId: 'sg', label: { en: 'gusta — one thing', it: 'gusta — una cosa' } },
      { cellId: 'pl', label: { en: 'gustan — several things', it: 'gustan — più cose' } },
    ],
    introLexemeIds: ['es/verb/gustar', 'es/verb/encantar', 'es/noun/café', 'es/noun/libro', 'es/verb/bailar'],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Me', '___', 'el', 'café.'],
            gapIndex: 1,
            gloss: { en: 'I like coffee.', it: 'Mi piace il caffè.' },
            answer: 'gusta',
            accepted: [],
            options: [
              { text: 'gusta' },
              { text: 'gustan', strategy: 'gustarNumberSwap' },
              { text: 'gusto', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-gustar:sg'],
            ttsText: 'Me gusta el café.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Me', '___', 'los', 'libros.'],
            gapIndex: 1,
            gloss: { en: 'I like books.', it: 'Mi piacciono i libri.' },
            answer: 'gustan',
            accepted: [],
            options: [
              { text: 'gustan' },
              { text: 'gusta', strategy: 'gustarNumberSwap' },
              { text: 'gusto', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-gustar:pl'],
            ttsText: 'Me gustan los libros.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', 'Te', '___', 'bailar?'],
            gapIndex: 2,
            gloss: { en: 'Do you like dancing?', it: 'Ti piace ballare?' },
            answer: 'gusta',
            accepted: [],
            options: [
              { text: 'gusta' },
              { text: 'gustan', strategy: 'gustarNumberSwap' },
              { text: 'gustas', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-gustar:sg'],
            ttsText: '¿Te gusta bailar?',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Nos', '___', 'la', 'casa', 'nueva.'],
            gapIndex: 1,
            gloss: { en: 'We like the new house.', it: 'Ci piace la casa nuova.' },
            answer: 'gusta',
            accepted: [],
            options: [
              { text: 'gusta' },
              { text: 'gustan', strategy: 'gustarNumberSwap' },
              { text: 'gustamos', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-gustar:sg'],
            ttsText: 'Nos gusta la casa nueva.',
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['A', 'ella', '___', 'gustan', 'las', 'manzanas.'],
            gapIndex: 2,
            gloss: { en: 'She likes apples.', it: 'A lei piacciono le mele.' },
            answer: 'le',
            accepted: [],
            skillIds: ['es-gustar:pl'],
            ttsText: 'A ella le gustan las manzanas.',
            strictSuffixLen: 0,
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['A', 'ellos', '___', 'gusta', 'viajar.'],
            gapIndex: 2,
            gloss: { en: 'They like travelling.', it: 'A loro piace viaggiare.' },
            answer: 'les',
            accepted: [],
            skillIds: ['es-gustar:sg'],
            ttsText: 'A ellos les gusta viajar.',
            strictSuffixLen: 1,
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Me', '___', 'los', 'zapatos', 'rojos.'],
            gapIndex: 1,
            gloss: { en: 'I love the red shoes.', it: 'Adoro le scarpe rosse.' },
            answer: 'encantan',
            accepted: [],
            options: [
              { text: 'encantan' },
              { text: 'encanta', strategy: 'gustarNumberSwap' },
              { text: 'encanto', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-gustar:pl'],
            ttsText: 'Me encantan los zapatos rojos.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['A', 'mi', 'madre', '___', 'encanta', 'el', 'vino.'],
            gapIndex: 3,
            gloss: { en: 'My mother loves wine.', it: 'A mia madre piace molto il vino.' },
            answer: 'le',
            accepted: [],
            options: [
              { text: 'le' },
              { text: 'les', strategy: 'wrongNumber' },
              { text: 'me', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-gustar:sg'],
            ttsText: 'A mi madre le encanta el vino.',
          },
        ],
      },
    ],
    errorHints: {
      gustarNumberSwap: {
        en: 'gusta if ONE thing (or an action) is pleasing, gustan if SEVERAL are: me gusta el café, me gustan los libros.',
        it: 'gusta se piace UNA cosa (o un’azione), gustan se ne piacciono TANTE: me gusta el café, me gustan los libros.',
      },
      wrongPerson: {
        en: 'gustar never agrees with you — you are the pronoun (me, te, le…), and the verb follows the thing liked.',
        it: 'gustar non concorda mai con te — tu sei il pronome (me, te, le…) e il verbo segue la cosa che piace.',
      },
      wrongNumber: {
        en: 'One person → le; more than one → les: a mi madre le gusta, a mis padres les gusta.',
        it: 'Una persona → le; più persone → les: a mi madre le gusta, a mis padres les gusta.',
      },
    },
  },
]
