import type { Topic } from '../../types'

// Unit ES-7 · Antes y ahora
// Authoring conventions (all unit files follow these):
// - ids are append-only; never rename
// - explanations: short prose, one or two tables, 2+ TTS-able examples, one callout
// - every drillItem's skill cells must appear in skillCells

export const ES_U7_TOPICS: Topic[] = [
  {
    id: 'es-imperfect',
    lang: 'es',
    title: { en: 'The imperfect', it: 'L’imperfetto' },
    ruleSummary: {
      en: 'hablaba, comía — habits, background and ongoing past states; only ser, ir, ver are irregular.',
      it: 'hablaba, comía — abitudini, sfondo e stati in corso nel passato; irregolari solo ser, ir, ver.',
    },
    cefr: 'A2',
    dependencies: ['es-preterite-regular'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: 'The **imperfecto** paints the background of the past: habits, descriptions, states that were ongoing. *Hablaba* = “I used to speak / I was speaking”. Verbs in **-ar** take **-aba, -abas, -aba, -ábamos, -abais, -aban**; **-er** and **-ir** verbs share one series: **-ía, -ías, -ía, -íamos, -íais, -ían**. And here is the good news: in the entire language only **three** verbs are irregular — *ser* (**era**), *ir* (**iba**), *ver* (**veía**). There are **no stem changes** in the imperfect: *quería*, *podía*, *dormía*.',
          it: 'L’**imperfecto** dipinge lo sfondo del passato: abitudini, descrizioni, stati in corso. *Hablaba* = “parlavo”. I verbi in **-ar** prendono **-aba, -abas, -aba, -ábamos, -abais, -aban**; quelli in **-er** e **-ir** condividono un’unica serie: **-ía, -ías, -ía, -íamos, -íais, -ían**. E c’è una bella notizia: in tutta la lingua gli irregolari sono solo **tre** — *ser* (**era**), *ir* (**iba**), *ver* (**veía**). All’imperfetto **non ci sono dittongazioni**: *quería*, *podía*, *dormía*.',
        },
      },
      {
        kind: 'table',
        caption: { en: 'hablar & comer — imperfect', it: 'hablar e comer — imperfetto' },
        header: ['', 'hablar', 'comer'],
        rows: [
          ['yo', 'hablaba', 'comía'],
          ['tú', 'hablabas', 'comías'],
          ['él / ella / usted', 'hablaba', 'comía'],
          ['nosotros/as', 'hablábamos', 'comíamos'],
          ['vosotros/as', 'hablabais', 'comíais'],
          ['ellos / ellas / ustedes', 'hablaban', 'comían'],
        ],
        highlight: [
          [0, 1],
          [0, 2],
          [3, 1],
          [3, 2],
        ],
      },
      {
        kind: 'table',
        caption: {
          en: 'The only three irregulars: ser, ir, ver',
          it: 'Gli unici tre irregolari: ser, ir, ver',
        },
        header: ['', 'ser', 'ir', 'ver'],
        rows: [
          ['yo', 'era', 'iba', 'veía'],
          ['tú', 'eras', 'ibas', 'veías'],
          ['él / ella / usted', 'era', 'iba', 'veía'],
          ['nosotros/as', 'éramos', 'íbamos', 'veíamos'],
          ['vosotros/as', 'erais', 'ibais', 'veíais'],
          ['ellos / ellas / ustedes', 'eran', 'iban', 'veían'],
        ],
        highlight: [
          [0, 1],
          [0, 2],
          [0, 3],
        ],
      },
      {
        kind: 'example',
        text: 'Cuando era niño, vivía en Sevilla.',
        gloss: { en: 'When I was a child, I lived in Seville.', it: 'Quando ero bambino, vivevo a Siviglia.' },
      },
      {
        kind: 'example',
        text: 'Antes trabajaba en un restaurante.',
        gloss: { en: 'I used to work in a restaurant.', it: 'Prima lavoravo in un ristorante.' },
      },
      {
        kind: 'example',
        text: 'Íbamos a la playa todos los veranos.',
        gloss: {
          en: 'We used to go to the beach every summer.',
          it: 'Andavamo in spiaggia tutte le estati.',
        },
        note: {
          en: 'ir → iba: one of only three irregular imperfects',
          it: 'ir → iba: uno dei soli tre imperfetti irregolari',
        },
      },
      {
        kind: 'callout',
        style: 'tip',
        md: {
          en: 'For Italian speakers this tense maps **one to one** onto the imperfetto: wherever you would say *parlavo*, say *hablaba*. The whole past system lines up — preterite ↔ passato prossimo, imperfect ↔ imperfetto — so your Italian instinct for choosing between them works unchanged in Spanish.',
          it: 'Questo tempo corrisponde **uno a uno** all’imperfetto italiano: dove diresti *parlavo*, di’ *hablaba*. Tutto il sistema del passato si allinea — pretérito ↔ passato prossimo, imperfecto ↔ imperfetto — quindi il tuo istinto italiano per scegliere tra i due funziona identico in spagnolo.',
        },
      },
    ],
    skillCells: [
      { cellId: '1sg', label: { en: 'yo form', it: 'forma di yo' } },
      { cellId: '2sg', label: { en: 'tú form', it: 'forma di tú' } },
      { cellId: '3sg', label: { en: 'él/ella form', it: 'forma di él/ella' } },
      { cellId: '1pl', label: { en: 'nosotros form', it: 'forma di nosotros' } },
      { cellId: '2pl', label: { en: 'vosotros form', it: 'forma di vosotros' } },
      { cellId: '3pl', label: { en: 'ellos form', it: 'forma di ellos' } },
    ],
    introLexemeIds: [
      'es/verb/hablar',
      'es/verb/comer',
      'es/verb/trabajar',
      'es/verb/ser',
      'es/verb/ir',
    ],
    drillItems: [
      { gen: 'match-verb', verbId: 'es/verb/hablar', tense: 'impf' },
      { gen: 'conj', verbId: 'es/verb/trabajar', tense: 'impf', persons: ['1sg', '3sg'], type: 'mc' },
      { gen: 'conj', verbId: 'es/verb/comer', tense: 'impf', persons: ['3sg', '1pl'], type: 'cloze' },
      { gen: 'conj', verbId: 'es/verb/ser', tense: 'impf', persons: ['1sg', '3pl'], type: 'mc' },
      { gen: 'conj', verbId: 'es/verb/ir', tense: 'impf', persons: ['1sg'], type: 'cloze' },
    ],
    errorHints: {
      wrongPerson: {
        en: 'Match the ending to the subject: hablaba, hablabas, hablaba, hablábamos, hablabais, hablaban.',
        it: 'Fai concordare la desinenza con il soggetto: hablaba, hablabas, hablaba, hablábamos, hablabais, hablaban.',
      },
      wrongClass: {
        en: '-ar verbs take -aba/-abas/-aba; -er and -ir verbs share -ía/-ías/-ía.',
        it: 'I verbi in -ar prendono -aba/-abas/-aba; quelli in -er e -ir condividono -ía/-ías/-ía.',
      },
      infinitive: {
        en: 'That’s the dictionary form — the imperfect needs a person ending.',
        it: 'Quella è la forma del dizionario — all’imperfetto serve una desinenza di persona.',
      },
    },
  },

  {
    id: 'es-perfect',
    lang: 'es',
    title: { en: 'The present perfect', it: 'Il passato prossimo (pretérito perfecto)' },
    ruleSummary: {
      en: 'he/has/ha/hemos/habéis/han + participle — the recent, still-relevant past: hoy, esta semana, ya.',
      it: 'he/has/ha/hemos/habéis/han + participio — il passato recente e ancora attuale: hoy, esta semana, ya.',
    },
    cefr: 'A2',
    dependencies: ['es-preterite-regular'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: 'The **pretérito perfecto** is built from the present of **haber** — **he, has, ha, hemos, habéis, han** — plus the past participle: **-ar → -ado** (*hablado*), **-er/-ir → -ido** (*comido*, *vivido*). A short list of participles is irregular: **hecho, dicho, visto, puesto, escrito, vuelto, abierto**. Spanish uses it for the recent or still-relevant past, typically with **hoy**, **esta semana**, **ya**, **todavía no**: *Hoy he trabajado mucho*.',
          it: 'Il **pretérito perfecto** si costruisce con il presente di **haber** — **he, has, ha, hemos, habéis, han** — più il participio passato: **-ar → -ado** (*hablado*), **-er/-ir → -ido** (*comido*, *vivido*). Una breve lista di participi è irregolare: **hecho, dicho, visto, puesto, escrito, vuelto, abierto**. Lo spagnolo lo usa per il passato recente o ancora attuale, tipicamente con **hoy**, **esta semana**, **ya**, **todavía no**: *Hoy he trabajado mucho*.',
        },
      },
      {
        kind: 'table',
        caption: { en: 'haber + participle', it: 'haber + participio' },
        header: ['', 'haber', { en: '+ participle', it: '+ participio' }],
        rows: [
          ['yo', 'he', 'hablado / comido / vivido'],
          ['tú', 'has', 'hablado / comido / vivido'],
          ['él / ella / usted', 'ha', 'hablado / comido / vivido'],
          ['nosotros/as', 'hemos', 'hablado / comido / vivido'],
          ['vosotros/as', 'habéis', 'hablado / comido / vivido'],
          ['ellos / ellas / ustedes', 'han', 'hablado / comido / vivido'],
        ],
        highlight: [
          [0, 1],
          [2, 1],
        ],
      },
      {
        kind: 'table',
        caption: { en: 'Irregular participles', it: 'Participi irregolari' },
        header: [
          { en: 'infinitive', it: 'infinito' },
          { en: 'participle', it: 'participio' },
          { en: 'Italian', it: 'italiano' },
        ],
        rows: [
          ['hacer', 'hecho', 'fatto'],
          ['decir', 'dicho', 'detto'],
          ['ver', 'visto', 'visto'],
          ['poner', 'puesto', 'messo'],
          ['escribir', 'escrito', 'scritto'],
          ['volver', 'vuelto', 'tornato'],
          ['abrir', 'abierto', 'aperto'],
        ],
      },
      {
        kind: 'example',
        text: 'Hoy he comido mucho.',
        gloss: { en: 'Today I have eaten a lot.', it: 'Oggi ho mangiato molto.' },
      },
      {
        kind: 'example',
        text: '¿Has visto la película?',
        gloss: { en: 'Have you seen the film?', it: 'Hai visto il film?' },
      },
      {
        kind: 'example',
        text: 'Todavía no hemos vuelto a casa.',
        gloss: { en: 'We haven’t gone back home yet.', it: 'Non siamo ancora tornati a casa.' },
        note: {
          en: 'haber even with motion verbs: hemos vuelto, never *somos vuelto',
          it: 'haber anche con i verbi di movimento: hemos vuelto, mai *somos vuelto',
        },
      },
      {
        kind: 'callout',
        style: 'warning',
        md: {
          en: 'It is formed exactly like the Italian passato prossimo — **but always with haber, never with ser**. Where Italian switches auxiliary (*ho mangiato* but *sono andato*), Spanish never does: “sono andato” → **he ido**, not *soy ido*; “ci siamo alzati” → **nos hemos levantado**.',
          it: 'Si forma esattamente come il passato prossimo italiano — **ma sempre con haber, mai con ser**. Dove l’italiano cambia ausiliare (*ho mangiato* ma *sono andato*), lo spagnolo non lo fa mai: “sono andato” → **he ido**, non *soy ido*; “ci siamo alzati” → **nos hemos levantado**.',
        },
      },
    ],
    skillCells: [
      { cellId: 'aux', label: { en: 'haber (auxiliary)', it: 'l’ausiliare haber' } },
      { cellId: 'part', label: { en: 'past participle', it: 'il participio passato' } },
    ],
    introLexemeIds: [
      'es/verb/hacer',
      'es/verb/ver',
      'es/verb/escribir',
      'es/verb/volver',
      'es/verb/abrir',
    ],
    drillItems: [
      {
        gen: 'perfect',
        verbIds: [
          'es/verb/hablar',
          'es/verb/comer',
          'es/verb/vivir',
          'es/verb/trabajar',
          'es/verb/comprar',
        ],
        count: 4,
        mode: 'aux',
        persons: ['1sg', '3sg', '2sg', '1pl'],
        cellId: 'aux',
      },
      {
        gen: 'perfect',
        verbIds: [
          'es/verb/hacer',
          'es/verb/ver',
          'es/verb/escribir',
          'es/verb/volver',
          'es/verb/comer',
        ],
        count: 4,
        mode: 'participle',
        persons: ['1sg', '3sg'],
        cellId: 'part',
      },
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Hoy', '___', 'comido', 'mucho.'],
            gapIndex: 1,
            gloss: { en: 'Today I have eaten a lot.', it: 'Oggi ho mangiato molto.' },
            answer: 'he',
            accepted: [],
            options: [
              { text: 'he' },
              { text: 'ha', strategy: 'wrongPerson' },
              { text: 'has', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-perfect:aux'],
            ttsText: 'Hoy he comido mucho.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['¿', '___', 'visto', 'la', 'película?'],
            gapIndex: 1,
            gloss: { en: 'Have you (tú) seen the film?', it: 'Hai visto il film? (tú)' },
            answer: 'Has',
            accepted: [],
            options: [
              { text: 'Has' },
              { text: 'Ha', strategy: 'wrongPerson' },
              { text: 'He', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-perfect:aux'],
            ttsText: '¿Has visto la película?',
          },
        ],
      },
    ],
    errorHints: {
      wrongPerson: {
        en: 'haber carries the person: yo he, tú has, él ha, nosotros hemos, vosotros habéis, ellos han.',
        it: 'È haber a portare la persona: yo he, tú has, él ha, nosotros hemos, vosotros habéis, ellos han.',
      },
      infinitive: {
        en: 'After haber you need the participle (-ado/-ido or hecho, visto…), never the infinitive.',
        it: 'Dopo haber serve il participio (-ado/-ido oppure hecho, visto…), mai l’infinito.',
      },
    },
  },

  {
    id: 'es-imperative',
    lang: 'es',
    title: { en: 'The imperative (tú)', it: 'L’imperativo (tú)' },
    ruleSummary: {
      en: '¡Habla! ¡Come! — the tú command is the 3sg present; eight irregulars: di, haz, ve, pon, sal, sé, ten, ven.',
      it: '¡Habla! ¡Come! — l’imperativo con tú è la 3ª persona del presente; otto irregolari: di, haz, ve, pon, sal, sé, ten, ven.',
    },
    cefr: 'A2',
    dependencies: ['es-present-er-ir'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: 'To give an order to **tú**, use the **él/ella form of the present**: *¡Habla!* (speak!), *¡Come!* (eat!), *¡Escribe!* (write!). Stem changes stay in place, because the 3sg has them: *¡Pide!* (order!), *¡Duerme!* (sleep!). Eight short classics are irregular and worth learning as a chant: **di** (decir), **haz** (hacer), **ve** (ir), **pon** (poner), **sal** (salir), **sé** (ser), **ten** (tener), **ven** (venir).',
          it: 'Per dare un ordine a **tú**, usa la **forma di él/ella del presente**: *¡Habla!* (parla!), *¡Come!* (mangia!), *¡Escribe!* (scrivi!). Le dittongazioni restano, perché la 3ª persona le ha: *¡Pide!* (ordina!), *¡Duerme!* (dormi!). Otto classici brevissimi sono irregolari e vanno imparati come una filastrocca: **di** (decir), **haz** (hacer), **ve** (ir), **pon** (poner), **sal** (salir), **sé** (ser), **ten** (tener), **ven** (venir).',
        },
      },
      {
        kind: 'table',
        caption: { en: 'Regular tú commands = 3sg present', it: 'Imperativo regolare con tú = 3ª persona del presente' },
        header: [
          { en: 'infinitive', it: 'infinito' },
          { en: 'tú command', it: 'imperativo (tú)' },
          { en: 'Italian', it: 'italiano' },
        ],
        rows: [
          ['hablar', '¡Habla!', 'parla!'],
          ['comer', '¡Come!', 'mangia!'],
          ['escribir', '¡Escribe!', 'scrivi!'],
          ['pedir', '¡Pide!', 'ordina!'],
          ['dormir', '¡Duerme!', 'dormi!'],
        ],
      },
      {
        kind: 'table',
        caption: { en: 'The eight irregular tú commands', it: 'Gli otto imperativi irregolari con tú' },
        header: [
          { en: 'infinitive', it: 'infinito' },
          { en: 'tú command', it: 'imperativo (tú)' },
          { en: 'Italian', it: 'italiano' },
        ],
        rows: [
          ['decir', '¡Di!', 'di’!'],
          ['hacer', '¡Haz!', 'fai!'],
          ['ir', '¡Ve!', 'vai!'],
          ['poner', '¡Pon!', 'metti!'],
          ['salir', '¡Sal!', 'esci!'],
          ['ser', '¡Sé!', 'sii!'],
          ['tener', '¡Ten!', 'tieni!'],
          ['venir', '¡Ven!', 'vieni!'],
        ],
      },
      {
        kind: 'example',
        text: '¡Habla más despacio, por favor!',
        gloss: { en: 'Speak more slowly, please!', it: 'Parla più lentamente, per favore!' },
      },
      {
        kind: 'example',
        text: '¡Ven aquí y pon la mesa!',
        gloss: { en: 'Come here and set the table!', it: 'Vieni qui e apparecchia la tavola!' },
      },
      {
        kind: 'callout',
        style: 'tip',
        md: {
          en: 'It works just like the Italian tu-imperative — *parla!*, *mangia!* — one bare form, no pronoun. And Spanish keeps its stem changes in the command, because the 3sg present has them: *¡Pide!*, *¡Duerme!*, *¡Empieza!*.',
          it: 'Funziona proprio come l’imperativo italiano con tu — *parla!*, *mangia!* — una forma nuda, senza pronome. E lo spagnolo mantiene le dittongazioni nell’ordine, perché la 3ª persona del presente le ha: *¡Pide!*, *¡Duerme!*, *¡Empieza!*.',
        },
      },
    ],
    skillCells: [{ cellId: 'tu', label: { en: 'tú commands', it: 'l’imperativo con tú' } }],
    introLexemeIds: [
      'es/verb/decir',
      'es/verb/hacer',
      'es/verb/venir',
      'es/verb/pedir',
      'es/verb/dormir',
    ],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['___', 'más', 'despacio'],
            gapIndex: 0,
            gloss: { en: 'Speak more slowly! (tú)', it: 'Parla più lentamente! (tú)' },
            answer: 'Habla',
            accepted: [],
            skillIds: ['es-imperative:tu'],
            ttsText: '¡Habla más despacio!',
            strictSuffixLen: 0,
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['___', 'la', 'verdad'],
            gapIndex: 0,
            gloss: { en: 'Tell the truth! (tú)', it: 'Di’ la verità! (tú)' },
            answer: 'Di',
            accepted: [],
            skillIds: ['es-imperative:tu'],
            ttsText: '¡Di la verdad!',
            strictSuffixLen: 0,
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['___', 'los', 'deberes'],
            gapIndex: 0,
            gloss: { en: 'Do your homework! (tú)', it: 'Fai i compiti! (tú)' },
            answer: 'Haz',
            accepted: [],
            skillIds: ['es-imperative:tu'],
            ttsText: '¡Haz los deberes!',
            strictSuffixLen: 0,
          },
          {
            type: 'cloze',
            lang: 'es',
            sentence: ['___', 'aquí'],
            gapIndex: 0,
            gloss: { en: 'Come here! (tú)', it: 'Vieni qui! (tú)' },
            answer: 'Ven',
            accepted: [],
            skillIds: ['es-imperative:tu'],
            ttsText: '¡Ven aquí!',
            strictSuffixLen: 0,
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'con', 'tu', 'madre.'],
            gapIndex: 0,
            gloss: { en: 'Speak with your mother! (tú)', it: 'Parla con tua madre! (tú)' },
            answer: 'Habla',
            accepted: [],
            options: [
              { text: 'Habla' },
              { text: 'Hablas', strategy: 'wrongPerson' },
              { text: 'Hable', strategy: 'wrongPerson' },
            ],
            skillIds: ['es-imperative:tu'],
            ttsText: '¡Habla con tu madre!',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'la', 'ventana.'],
            gapIndex: 0,
            gloss: { en: 'Open the window! (tú)', it: 'Apri la finestra! (tú)' },
            answer: 'Abre',
            accepted: [],
            options: [
              { text: 'Abre' },
              { text: 'Abres', strategy: 'wrongPerson' },
              { text: 'Abrir', strategy: 'infinitive' },
            ],
            skillIds: ['es-imperative:tu'],
            ttsText: '¡Abre la ventana!',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'el', 'pescado.'],
            gapIndex: 0,
            gloss: { en: 'Order the fish! (tú)', it: 'Ordina il pesce! (tú)' },
            answer: 'Pide',
            accepted: [],
            options: [
              { text: 'Pide' },
              { text: 'Pides', strategy: 'wrongPerson' },
              { text: 'Pedir', strategy: 'infinitive' },
            ],
            skillIds: ['es-imperative:tu'],
            ttsText: '¡Pide el pescado!',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['___', 'bien', 'esta', 'noche.'],
            gapIndex: 0,
            gloss: { en: 'Sleep well tonight! (tú)', it: 'Dormi bene stanotte! (tú)' },
            answer: 'Duerme',
            accepted: [],
            options: [
              { text: 'Duerme' },
              { text: 'Duermes', strategy: 'wrongPerson' },
              { text: 'Dormir', strategy: 'infinitive' },
            ],
            skillIds: ['es-imperative:tu'],
            ttsText: '¡Duerme bien esta noche!',
          },
        ],
      },
    ],
    errorHints: {
      wrongPerson: {
        en: 'The tú command is the él/ella form of the present, with no -s: ¡Habla!, not *¡Hablas!.',
        it: 'L’imperativo con tú è la forma di él/ella del presente, senza -s: ¡Habla!, non *¡Hablas!.',
      },
      infinitive: {
        en: 'That’s the dictionary form — a command needs the imperative: ¡Abre!, ¡Pide!, ¡Duerme!.',
        it: 'Quella è la forma del dizionario — un ordine vuole l’imperativo: ¡Abre!, ¡Pide!, ¡Duerme!.',
      },
    },
  },

  {
    id: 'es-por-para',
    lang: 'es',
    title: { en: 'Por vs para', it: 'Por e para' },
    ruleSummary: {
      en: 'para = purpose, destination, deadline; por = cause, exchange, movement through, duration.',
      it: 'para = scopo, destinazione, scadenza; por = causa, scambio, attraversamento, durata.',
    },
    cefr: 'A2',
    dependencies: ['es-preterite-regular'],
    explanation: [
      {
        kind: 'prose',
        md: {
          en: 'Spanish splits “for” in two. **Para** looks **forward**: purpose (*para trabajar* — in order to work), destination (*el tren para Madrid*), recipient (*es para ti*), deadline (*para mañana*). **Por** looks at the **reason or the path**: cause (*gracias por el regalo*), exchange (*veinte euros por el libro*), movement through (*pasa por Madrid*), duration (*por dos horas*).',
          it: 'Lo spagnolo divide il “per” in due. **Para** guarda **avanti**: scopo (*para trabajar* — per lavorare), destinazione (*el tren para Madrid*), destinatario (*es para ti*), scadenza (*para mañana*). **Por** guarda alla **causa o al percorso**: causa (*gracias por el regalo*), scambio (*veinte euros por el libro*), attraversamento (*pasa por Madrid*), durata (*por dos horas*).',
        },
      },
      {
        kind: 'table',
        caption: { en: 'para vs por — the categories', it: 'para e por — le categorie' },
        header: [
          'para',
          { en: 'example', it: 'esempio' },
          'por',
          { en: 'example', it: 'esempio' },
        ],
        rows: [
          [
            { en: 'purpose', it: 'scopo' },
            'Estudio para trabajar.',
            { en: 'cause', it: 'causa' },
            'Gracias por el regalo.',
          ],
          [
            { en: 'destination', it: 'destinazione' },
            'Salgo para Madrid.',
            { en: 'movement through', it: 'attraversamento' },
            'El tren pasa por Madrid.',
          ],
          [
            { en: 'recipient', it: 'destinatario' },
            'Este regalo es para ti.',
            { en: 'exchange', it: 'scambio' },
            'Pagué diez euros por el libro.',
          ],
          [
            { en: 'deadline', it: 'scadenza' },
            'Es para mañana.',
            { en: 'duration', it: 'durata' },
            'Trabajé por dos horas.',
          ],
        ],
      },
      {
        kind: 'example',
        text: 'Estudio español para trabajar en España.',
        gloss: {
          en: 'I study Spanish in order to work in Spain.',
          it: 'Studio spagnolo per lavorare in Spagna.',
        },
      },
      {
        kind: 'example',
        text: 'Gracias por el regalo.',
        gloss: { en: 'Thanks for the gift.', it: 'Grazie per il regalo.' },
      },
      {
        kind: 'example',
        text: 'El tren pasa por Madrid.',
        gloss: { en: 'The train goes through Madrid.', it: 'Il treno passa per Madrid.' },
      },
      {
        kind: 'callout',
        style: 'warning',
        md: {
          en: 'Both translate the Italian *per* — that is exactly why they are hard. Don’t translate the word: learn the **categories**. Ask what the *per* is doing — purpose, destination or deadline → **para**; cause, exchange, through or duration → **por**.',
          it: 'Tutti e due traducono il *per* italiano — ed è proprio per questo che sono difficili. Non tradurre la parola: impara le **categorie**. Chiediti cosa fa quel *per* — scopo, destinazione o scadenza → **para**; causa, scambio, attraversamento o durata → **por**.',
        },
      },
    ],
    skillCells: [{ cellId: 'core', label: { en: 'por vs para', it: 'por o para' } }],
    introLexemeIds: [
      'es/verb/estudiar',
      'es/verb/trabajar',
      'es/verb/viajar',
      'es/verb/comprar',
    ],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Estudio', 'español', '___', 'trabajar', 'en', 'España.'],
            gapIndex: 2,
            gloss: {
              en: 'I study Spanish in order to work in Spain. (purpose)',
              it: 'Studio spagnolo per lavorare in Spagna. (scopo)',
            },
            answer: 'para',
            accepted: [],
            options: [{ text: 'para' }, { text: 'por', strategy: 'vocabConfusable' }, { text: 'de', strategy: 'vocabConfusable' }],
            skillIds: ['es-por-para:core'],
            ttsText: 'Estudio español para trabajar en España.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Gracias', '___', 'el', 'regalo.'],
            gapIndex: 1,
            gloss: { en: 'Thanks for the gift. (cause)', it: 'Grazie per il regalo. (causa)' },
            answer: 'por',
            accepted: [],
            options: [{ text: 'por' }, { text: 'para', strategy: 'vocabConfusable' }, { text: 'en', strategy: 'vocabConfusable' }],
            skillIds: ['es-por-para:core'],
            ttsText: 'Gracias por el regalo.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['El', 'tren', 'pasa', '___', 'Madrid.'],
            gapIndex: 3,
            gloss: {
              en: 'The train goes through Madrid. (through)',
              it: 'Il treno passa per Madrid. (attraversamento)',
            },
            answer: 'por',
            accepted: [],
            options: [{ text: 'por' }, { text: 'para', strategy: 'vocabConfusable' }, { text: 'a', strategy: 'vocabConfusable' }],
            skillIds: ['es-por-para:core'],
            ttsText: 'El tren pasa por Madrid.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Este', 'regalo', 'es', '___', 'ti.'],
            gapIndex: 3,
            gloss: {
              en: 'This gift is for you. (recipient)',
              it: 'Questo regalo è per te. (destinatario)',
            },
            answer: 'para',
            accepted: [],
            options: [{ text: 'para' }, { text: 'por', strategy: 'vocabConfusable' }, { text: 'de', strategy: 'vocabConfusable' }],
            skillIds: ['es-por-para:core'],
            ttsText: 'Este regalo es para ti.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Trabajé', '___', 'dos', 'horas.'],
            gapIndex: 1,
            gloss: { en: 'I worked for two hours. (duration)', it: 'Ho lavorato per due ore. (durata)' },
            answer: 'por',
            accepted: [],
            options: [{ text: 'por' }, { text: 'para', strategy: 'vocabConfusable' }, { text: 'en', strategy: 'vocabConfusable' }],
            skillIds: ['es-por-para:core'],
            ttsText: 'Trabajé por dos horas.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Necesito', 'el', 'libro', '___', 'mañana.'],
            gapIndex: 3,
            gloss: {
              en: 'I need the book by tomorrow. (deadline)',
              it: 'Mi serve il libro per domani. (scadenza)',
            },
            answer: 'para',
            accepted: [],
            options: [{ text: 'para' }, { text: 'por', strategy: 'vocabConfusable' }, { text: 'a', strategy: 'vocabConfusable' }],
            skillIds: ['es-por-para:core'],
            ttsText: 'Necesito el libro para mañana.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Salgo', '___', 'Madrid', 'mañana.'],
            gapIndex: 1,
            gloss: {
              en: 'I leave for Madrid tomorrow. (destination)',
              it: 'Parto per Madrid domani. (destinazione)',
            },
            answer: 'para',
            accepted: [],
            options: [{ text: 'para' }, { text: 'por', strategy: 'vocabConfusable' }, { text: 'de', strategy: 'vocabConfusable' }],
            skillIds: ['es-por-para:core'],
            ttsText: 'Salgo para Madrid mañana.',
          },
          {
            type: 'mc',
            lang: 'es',
            sentence: ['Pagué', 'diez', 'euros', '___', 'el', 'libro.'],
            gapIndex: 3,
            gloss: {
              en: 'I paid ten euros for the book. (exchange)',
              it: 'Ho pagato dieci euro per il libro. (scambio)',
            },
            answer: 'por',
            accepted: [],
            options: [{ text: 'por' }, { text: 'para', strategy: 'vocabConfusable' }, { text: 'en', strategy: 'vocabConfusable' }],
            skillIds: ['es-por-para:core'],
            ttsText: 'Pagué diez euros por el libro.',
          },
        ],
      },
    ],
    errorHints: {
      vocabConfusable: {
        en: 'Both translate “per” — para marks purpose/destination, por marks cause/exchange/through.',
        it: 'Entrambi traducono “per” — para indica scopo/destinazione, por indica causa/scambio/attraversamento.',
      },
    },
  },
]
