import type { VocabPack } from '../types'
import { ES_NOUNS } from './morphology/nouns'
import { ES_VERBS } from './morphology/verbs'
import { ES_ADJS } from './morphology/adjectives'
import type { VocabLexeme } from '../../engine/vocab'

export const ES_PACK_BASICS: VocabPack = {
  id: 'es-pack-basics',
  lang: 'es',
  unitId: 'es-u1',
  title: { en: 'First words', it: 'Prime parole' },
  lexemeIds: [
    'es/noun/casa',
    'es/noun/libro',
    'es/noun/agua',
    'es/noun/café',
    'es/noun/pan',
    'es/noun/mujer',
    'es/noun/hombre',
    'es/noun/amigo',
    'es/verb/hablar',
    'es/verb/comer',
    'es/verb/beber',
    'es/verb/trabajar',
  ],
}

export const ES_PACK_FAMILY: VocabPack = {
  id: 'es-pack-family',
  lang: 'es',
  unitId: 'es-u1',
  title: { en: 'Family', it: 'La famiglia' },
  lexemeIds: [
    'es/noun/familia',
    'es/noun/padre',
    'es/noun/madre',
    'es/noun/hermano',
    'es/noun/hermana',
    'es/noun/hijo',
    'es/noun/hija',
    'es/noun/abuelo',
    'es/noun/abuela',
    'es/noun/niño',
    'es/noun/niña',
  ],
}

export const ES_PACK_DESCRIBE: VocabPack = {
  id: 'es-pack-describe',
  lang: 'es',
  unitId: 'es-u1',
  title: { en: 'Describing things', it: 'Descrivere le cose' },
  lexemeIds: [
    'es/adj/alto',
    'es/adj/bajo',
    'es/adj/grande',
    'es/adj/pequeño',
    'es/adj/nuevo',
    'es/adj/viejo',
    'es/adj/bonito',
    'es/adj/bueno',
    'es/adj/malo',
    'es/adj/feliz',
  ],
}

export const ES_PACK_FOOD: VocabPack = {
  id: 'es-pack-food',
  lang: 'es',
  unitId: 'es-u2',
  title: { en: 'Food & drink', it: 'Cibo e bevande' },
  lexemeIds: [
    'es/noun/leche',
    'es/noun/queso',
    'es/noun/huevo',
    'es/noun/carne',
    'es/noun/pescado',
    'es/noun/arroz',
    'es/noun/fruta',
    'es/noun/naranja',
    'es/noun/vino',
    'es/noun/cerveza',
    'es/verb/comer',
    'es/verb/beber',
    'es/verb/cocinar',
    'es/verb/tomar',
  ],
}

export const ES_PACK_TOWN: VocabPack = {
  id: 'es-pack-town',
  lang: 'es',
  unitId: 'es-u2',
  title: { en: 'Around town', it: 'In città' },
  lexemeIds: [
    'es/noun/ciudad',
    'es/noun/escuela',
    'es/noun/restaurante',
    'es/noun/tienda',
    'es/noun/parque',
    'es/noun/calle',
    'es/noun/playa',
    'es/noun/país',
    'es/noun/pueblo',
    'es/noun/mercado',
    'es/verb/caminar',
  ],
}

export const ES_PACK_DAILY: VocabPack = {
  id: 'es-pack-daily',
  lang: 'es',
  unitId: 'es-u2',
  title: { en: 'Daily life', it: 'Vita quotidiana' },
  lexemeIds: [
    'es/verb/estudiar',
    'es/verb/escuchar',
    'es/verb/mirar',
    'es/verb/comprar',
    'es/verb/leer',
    'es/verb/escribir',
    'es/verb/aprender',
    'es/noun/trabajo',
    'es/noun/escuela',
    'es/noun/día',
    'es/noun/noche',
  ],
}

export const ES_PACK_HOUSE: VocabPack = {
  id: 'es-pack-house',
  lang: 'es',
  unitId: 'es-u3',
  title: { en: 'Around the house', it: 'In casa' },
  lexemeIds: [
    'es/noun/cocina',
    'es/noun/baño',
    'es/noun/dormitorio',
    'es/noun/salón',
    'es/noun/cama',
    'es/noun/ducha',
    'es/noun/jardín',
    'es/noun/espejo',
    'es/noun/puerta',
    'es/noun/ventana',
    'es/noun/mesa',
    'es/noun/silla',
  ],
}

export const ES_PACK_ACTIONS: VocabPack = {
  id: 'es-pack-actions',
  lang: 'es',
  unitId: 'es-u3',
  title: { en: 'Verbs on the move', it: 'Verbi in movimento' },
  lexemeIds: [
    'es/verb/venir',
    'es/verb/salir',
    'es/verb/poner',
    'es/verb/decir',
    'es/verb/ver',
    'es/verb/dar',
    'es/verb/volver',
    'es/verb/jugar',
    'es/verb/dormir',
    'es/verb/empezar',
    'es/verb/pensar',
    'es/verb/entender',
  ],
}

export const ES_PACK_CLOTHES: VocabPack = {
  id: 'es-pack-clothes',
  lang: 'es',
  unitId: 'es-u4',
  title: { en: 'Clothes & shopping', it: 'Vestiti e acquisti' },
  lexemeIds: [
    'es/noun/camisa',
    'es/noun/camiseta',
    'es/noun/pantalón',
    'es/noun/vestido',
    'es/noun/falda',
    'es/noun/abrigo',
    'es/noun/chaqueta',
    'es/noun/sombrero',
    'es/noun/dinero',
    'es/noun/precio',
    'es/noun/regalo',
    'es/verb/llevar',
    'es/verb/pagar',
    'es/verb/buscar',
  ],
}

export const ES_PACK_DESCRIBE2: VocabPack = {
  id: 'es-pack-describe2',
  lang: 'es',
  unitId: 'es-u4',
  title: { en: 'More descriptions', it: 'Altre descrizioni' },
  lexemeIds: [
    'es/adj/rápido',
    'es/adj/lento',
    'es/adj/largo',
    'es/adj/corto',
    'es/adj/guapo',
    'es/adj/divertido',
    'es/adj/aburrido',
    'es/adj/importante',
    'es/adj/moreno',
    'es/adj/joven',
    'es/adj/simpático',
  ],
}

export const ES_PACK_ROUTINE: VocabPack = {
  id: 'es-pack-routine',
  lang: 'es',
  unitId: 'es-u5',
  title: { en: 'Daily routine', it: 'La routine quotidiana' },
  lexemeIds: [
    'es/verb/levantar',
    'es/verb/duchar',
    'es/verb/acostar',
    'es/verb/despertar',
    'es/verb/desayunar',
    'es/verb/cenar',
    'es/verb/terminar',
    'es/noun/desayuno',
    'es/noun/comida',
    'es/noun/cena',
    'es/noun/mañana',
    'es/noun/tarde',
  ],
}

export const ES_PACK_TRAVEL: VocabPack = {
  id: 'es-pack-travel',
  lang: 'es',
  unitId: 'es-u6',
  title: { en: 'Travel', it: 'In viaggio' },
  lexemeIds: [
    'es/noun/viaje',
    'es/noun/tren',
    'es/noun/avión',
    'es/noun/autobús',
    'es/noun/hotel',
    'es/noun/maleta',
    'es/noun/billete',
    'es/noun/aeropuerto',
    'es/noun/mar',
    'es/noun/montaña',
    'es/verb/viajar',
    'es/verb/visitar',
    'es/verb/llegar',
  ],
}

export const ES_PACK_BODY: VocabPack = {
  id: 'es-pack-body',
  lang: 'es',
  unitId: 'es-u5',
  title: { en: 'Body & health', it: 'Corpo e salute' },
  lexemeIds: [
    'es/noun/cabeza',
    'es/noun/ojo',
    'es/noun/mano',
    'es/noun/pie',
    'es/noun/brazo',
    'es/noun/pierna',
    'es/noun/corazón',
    'es/noun/boca',
    'es/noun/nariz',
    'es/noun/pelo',
    'es/noun/hospital',
    'es/noun/farmacia',
    'es/noun/dolor',
    'es/noun/gripe',
    'es/adj/sano',
  ],
}

export const ES_PACK_FEELINGS: VocabPack = {
  id: 'es-pack-feelings',
  lang: 'es',
  unitId: 'es-u4',
  title: { en: 'Feelings', it: 'Sentimenti' },
  lexemeIds: [
    'es/noun/miedo',
    'es/noun/alegría',
    'es/noun/amor',
    'es/noun/problema',
    'es/noun/suerte',
    'es/noun/ayuda',
    'es/noun/idea',
    'es/noun/verdad',
    'es/noun/mentira',
    'es/adj/triste',
    'es/adj/nervioso',
    'es/adj/tranquilo',
    'es/adj/serio',
  ],
}

export const ES_PACK_NATURE: VocabPack = {
  id: 'es-pack-nature',
  lang: 'es',
  unitId: 'es-u6',
  title: { en: 'Weather & nature', it: 'Tempo e natura' },
  lexemeIds: [
    'es/noun/sol',
    'es/noun/luna',
    'es/noun/cielo',
    'es/noun/estrella',
    'es/noun/lluvia',
    'es/noun/nieve',
    'es/noun/viento',
    'es/noun/nube',
    'es/noun/árbol',
    'es/noun/flor',
    'es/noun/río',
    'es/noun/tiempo',
    'es/noun/calor',
    'es/verb/llover',
    'es/verb/nevar',
  ],
}

export const ES_PACK_WORK: VocabPack = {
  id: 'es-pack-work',
  lang: 'es',
  unitId: 'es-u3',
  title: { en: 'Work & school', it: 'Lavoro e scuola' },
  lexemeIds: [
    'es/noun/oficina',
    'es/noun/empresa',
    'es/noun/jefe',
    'es/noun/jefa',
    'es/noun/reunión',
    'es/noun/examen',
    'es/noun/clase',
    'es/noun/universidad',
    'es/noun/palabra',
    'es/noun/deberes',
    'es/noun/profesión',
    'es/verb/enseñar',
    'es/verb/explicar',
    'es/verb/preguntar',
    'es/verb/contestar',
  ],
}

export const ES_PACK_TECH: VocabPack = {
  id: 'es-pack-tech',
  lang: 'es',
  unitId: 'es-u4',
  title: { en: 'Tech & media', it: 'Tecnologia e media' },
  lexemeIds: [
    'es/noun/internet',
    'es/noun/película',
    'es/noun/música',
    'es/noun/canción',
    'es/noun/radio',
    'es/noun/televisión',
    'es/noun/foto',
    'es/noun/mensaje',
    'es/noun/juego',
    'es/noun/red',
    'es/noun/correo',
    'es/verb/enviar',
    'es/verb/recibir',
    'es/verb/usar',
  ],
}

export const ES_PACK_CITY: VocabPack = {
  id: 'es-pack-city',
  lang: 'es',
  unitId: 'es-u6',
  title: { en: 'In the city', it: 'In città 2' },
  lexemeIds: [
    'es/noun/plaza',
    'es/noun/iglesia',
    'es/noun/museo',
    'es/noun/banco',
    'es/noun/puente',
    'es/noun/barrio',
    'es/noun/estación',
    'es/noun/taxi',
    'es/noun/metro',
    'es/noun/entrada',
    'es/noun/salida',
    'es/noun/esquina',
    'es/verb/subir',
    'es/verb/bajar',
  ],
}

export const ES_PACK_FOOD2: VocabPack = {
  id: 'es-pack-food2',
  lang: 'es',
  unitId: 'es-u2',
  title: { en: 'More food', it: 'Altro cibo' },
  lexemeIds: [
    'es/noun/sopa',
    'es/noun/ensalada',
    'es/noun/pollo',
    'es/noun/tomate',
    'es/noun/patata',
    'es/noun/azúcar',
    'es/noun/sal',
    'es/noun/aceite',
    'es/noun/postre',
    'es/noun/helado',
    'es/noun/tarta',
    'es/noun/zumo',
  ],
}

export const ES_PACK_TIME: VocabPack = {
  id: 'es-pack-time',
  lang: 'es',
  unitId: 'es-u7',
  title: { en: 'Days & seasons', it: 'Giorni e stagioni' },
  lexemeIds: [
    'es/noun/lunes',
    'es/noun/martes',
    'es/noun/miércoles',
    'es/noun/jueves',
    'es/noun/viernes',
    'es/noun/sábado',
    'es/noun/domingo',
    'es/noun/mes',
    'es/noun/primavera',
    'es/noun/verano',
    'es/noun/otoño',
    'es/noun/invierno',
    'es/noun/fecha',
    'es/noun/cumpleaños',
    'es/noun/vacaciones',
  ],
}

export const ES_PACK_HOUSE2: VocabPack = {
  id: 'es-pack-house2',
  lang: 'es',
  unitId: 'es-u3',
  title: { en: 'Home 2', it: 'In casa 2' },
  lexemeIds: [
    'es/noun/llave',
    'es/noun/escalera',
    'es/noun/ascensor',
    'es/noun/pared',
    'es/noun/suelo',
    'es/noun/techo',
    'es/noun/horno',
    'es/noun/nevera',
    'es/noun/lavadora',
    'es/noun/toalla',
    'es/noun/jabón',
    'es/noun/almohada',
    'es/verb/cerrar',
    'es/verb/romper',
  ],
}

export const ES_PACK_RESTAURANT: VocabPack = {
  id: 'es-pack-restaurant',
  lang: 'es',
  unitId: 'es-u4',
  title: { en: 'Eating out', it: 'Al ristorante' },
  lexemeIds: [
    'es/noun/camarero',
    'es/noun/camarera',
    'es/noun/cuenta',
    'es/noun/propina',
    'es/noun/menú',
    'es/noun/carnicería',
    'es/noun/panadería',
    'es/noun/rebajas',
    'es/noun/talla',
    'es/noun/bolsa',
    'es/noun/caja',
    'es/noun/tarjeta',
    'es/noun/efectivo',
    'es/verb/probar',
    'es/verb/traer',
  ],
}

export const ES_PACK_SCHOOL: VocabPack = {
  id: 'es-pack-school',
  lang: 'es',
  unitId: 'es-u5',
  title: { en: 'Learning Spanish', it: 'Imparare lo spagnolo' },
  lexemeIds: [
    'es/noun/gramática',
    'es/noun/ejercicio',
    'es/noun/error',
    'es/noun/nivel',
    'es/noun/curso',
    'es/noun/página',
    'es/noun/cuaderno',
    'es/noun/bolígrafo',
    'es/noun/lápiz',
    'es/noun/significado',
    'es/verb/intentar',
    'es/verb/responder',
    'es/verb/conseguir',
  ],
}

export const ES_PACK_ANIMALS: VocabPack = {
  id: 'es-pack-animals',
  lang: 'es',
  unitId: 'es-u6',
  title: { en: 'Animals & nature 2', it: 'Animali e natura 2' },
  lexemeIds: [
    'es/noun/animal',
    'es/noun/pájaro',
    'es/noun/perro',
    'es/noun/gato',
    'es/noun/caballo',
    'es/noun/pez',
    'es/noun/vaca',
    'es/noun/isla',
    'es/noun/piedra',
    'es/noun/hierba',
    'es/noun/hoja',
    'es/noun/campo',
    'es/noun/bosque',
  ],
}

export const ES_PACK_TRAVEL2: VocabPack = {
  id: 'es-pack-travel2',
  lang: 'es',
  unitId: 'es-u7',
  title: { en: 'Travel 2', it: 'In viaggio 2' },
  lexemeIds: [
    'es/noun/pasaporte',
    'es/noun/frontera',
    'es/noun/reserva',
    'es/noun/habitación',
    'es/noun/llegada',
    'es/noun/retraso',
    'es/noun/andén',
    'es/noun/vuelo',
    'es/noun/equipaje',
    'es/noun/turismo',
    'es/noun/guía',
    'es/noun/mapa',
    'es/verb/seguir',
  ],
}

export const ES_PACK_ESSENTIALS: VocabPack = {
  id: 'es-pack-essentials',
  lang: 'es',
  unitId: 'es-u7',
  title: { en: 'Essential words', it: 'Parole essenziali' },
  lexemeIds: [
    'es/noun/cosa',
    'es/noun/vez',
    'es/noun/vida',
    'es/noun/mundo',
    'es/noun/historia',
    'es/noun/luz',
    'es/noun/fuego',
    'es/noun/aire',
    'es/noun/color',
    'es/noun/forma',
    'es/noun/parte',
    'es/noun/lado',
    'es/noun/centro',
    'es/noun/final',
    'es/noun/principio',
  ],
}

export const ES_PACKS: VocabPack[] = [
  ES_PACK_BASICS,
  ES_PACK_FAMILY,
  ES_PACK_DESCRIBE,
  ES_PACK_FOOD,
  ES_PACK_TOWN,
  ES_PACK_DAILY,
  ES_PACK_HOUSE,
  ES_PACK_ACTIONS,
  ES_PACK_CLOTHES,
  ES_PACK_DESCRIBE2,
  ES_PACK_ROUTINE,
  ES_PACK_TRAVEL,
  ES_PACK_BODY,
  ES_PACK_FEELINGS,
  ES_PACK_NATURE,
  ES_PACK_WORK,
  ES_PACK_TECH,
  ES_PACK_CITY,
  ES_PACK_FOOD2,
  ES_PACK_TIME,
  ES_PACK_HOUSE2,
  ES_PACK_RESTAURANT,
  ES_PACK_SCHOOL,
  ES_PACK_ANIMALS,
  ES_PACK_TRAVEL2,
  ES_PACK_ESSENTIALS,
]

/** lemma-key ("casa") -> lexeme, for resolving vocab skill ids back to words */
export const ES_LEXEME_BY_KEY: Map<string, VocabLexeme> = new Map(
  [...ES_NOUNS, ...ES_VERBS, ...ES_ADJS].map((l) => [l.id.split('/').pop()!, l]),
)

export function packLexemes(pack: VocabPack): VocabLexeme[] {
  return pack.lexemeIds
    .map((id) => ES_LEXEME_BY_KEY.get(id.split('/').pop()!))
    .filter((l): l is VocabLexeme => !!l)
}
