import type { Topic } from '../../types'

// Unit DE-2 · Sätze bauen
// Authoring conventions (all unit files follow these):
// - ids are append-only; never rename
// - explanations: short prose, one or two tables, 2+ TTS-able examples, one callout
// - every drillItem's skill cells must appear in skillCells

export const DE_U2_TOPICS: Topic[] = [
  {
    id: 'de-questions',
    lang: 'de',
    title: 'Questions',
    ruleSummary: 'Yes/no questions start with the verb (Trinkst du Kaffee?); W-questions: W-word + verb + subject.',
    cefr: 'A1',
    dependencies: ['de-word-order-v2'],
    explanation: [
      {
        kind: 'prose',
        md: 'German questions come in two shapes, and neither needs a helper like English “do”. A **yes/no question** simply puts the conjugated verb **first**: *Trinkst du Kaffee?* — literally “Drink you coffee?”. A **W-question** starts with a question word, and the verb stays right behind it in position 2: *Wo wohnst du?* (Where do you live?).',
      },
      {
        kind: 'table',
        caption: 'The six W-words',
        header: ['W-word', 'meaning', 'example'],
        rows: [
          ['wer', 'who', 'Wer bist du?'],
          ['was', 'what', 'Was isst du?'],
          ['wo', 'where', 'Wo wohnst du?'],
          ['wann', 'when', 'Wann arbeitest du?'],
          ['wie', 'how', 'Wie heißt du?'],
          ['warum', 'why', 'Warum lernst du Deutsch?'],
        ],
      },
      { kind: 'example', text: 'Trinkst du Kaffee?', gloss: 'Do you drink coffee?', note: 'verb first — no “do”' },
      { kind: 'example', text: 'Wo wohnst du?', gloss: 'Where do you live?' },
      { kind: 'example', text: 'Was isst du?', gloss: 'What are you eating?' },
      {
        kind: 'callout',
        style: 'tip',
        md: 'No do-support, ever: to ask a yes/no question, just **flip verb and subject** — *Du trinkst Kaffee.* → *Trinkst du Kaffee?* The W-words all start with **w** (English flipped them to “wh”).',
      },
    ],
    skillCells: [
      { cellId: 'q.yesno', label: 'yes/no questions' },
      { cellId: 'q.wword', label: 'W-questions' },
    ],
    introLexemeIds: [],
    drillItems: [
      {
        gen: 'word-order',
        items: [
          { answer: 'Trinkst du Kaffee', gloss: 'Do you drink coffee?', cellId: 'q.yesno' },
          { answer: 'Arbeitest du heute', gloss: 'Are you working today?', cellId: 'q.yesno' },
          { answer: 'Wo wohnst du', gloss: 'Where do you live?', cellId: 'q.wword' },
          { answer: 'Was isst du', gloss: 'What are you eating?', cellId: 'q.wword' },
        ],
      },
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'de',
            sentence: ['___', 'wohnst', 'du?', '—', 'In', 'Berlin.'],
            gapIndex: 0,
            gloss: '___ do you live? — In Berlin.',
            answer: 'Wo',
            accepted: [],
            options: [
              { text: 'Wo' },
              { text: 'Was', strategy: 'vocabConfusable' },
              { text: 'Wann', strategy: 'vocabConfusable' },
              { text: 'Wer', strategy: 'vocabConfusable' },
            ],
            skillIds: ['de-questions:q.wword'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['___', 'trinkst', 'du?', '—', 'Tee.'],
            gapIndex: 0,
            gloss: '___ are you drinking? — Tea.',
            answer: 'Was',
            accepted: [],
            options: [
              { text: 'Was' },
              { text: 'Wo', strategy: 'vocabConfusable' },
              { text: 'Wer', strategy: 'vocabConfusable' },
              { text: 'Wie', strategy: 'vocabConfusable' },
            ],
            skillIds: ['de-questions:q.wword'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['___', 'arbeitest', 'du?', '—', 'Heute.'],
            gapIndex: 0,
            gloss: '___ do you work? — Today.',
            answer: 'Wann',
            accepted: [],
            options: [
              { text: 'Wann' },
              { text: 'Wo', strategy: 'vocabConfusable' },
              { text: 'Warum', strategy: 'vocabConfusable' },
              { text: 'Was', strategy: 'vocabConfusable' },
            ],
            skillIds: ['de-questions:q.wword'],
          },
        ],
      },
    ],
    errorHints: {
      vocabConfusable: 'Match the W-word to the answer given: wer = who, was = what, wo = where, wann = when, wie = how, warum = why.',
      v2Violation: 'Yes/no questions put the verb FIRST; in W-questions the verb comes right after the W-word.',
    },
  },

  {
    id: 'de-plurals',
    lang: 'de',
    title: 'Plurals',
    ruleSummary: 'Five main patterns — -e, -er, -(e)n, -s, umlaut — and the plural article is always die.',
    cefr: 'A1',
    dependencies: ['de-noun-gender'],
    explanation: [
      {
        kind: 'prose',
        md: 'German has no single plural rule — nouns follow one of **five main patterns**, often with an **umlaut** on top (*Stadt → Städte*). So learn each noun’s plural **with the word**, just like its gender. The consolation prize: in the plural, gender vanishes — the article is **always die**.',
      },
      {
        kind: 'table',
        caption: 'The five main plural patterns',
        header: ['pattern', 'singular', 'plural'],
        rows: [
          ['-e', 'der Tisch', 'die Tische'],
          ['-er', 'das Kind', 'die Kinder'],
          ['-(e)n', 'die Frau', 'die Frauen'],
          ['-s', 'das Auto', 'die Autos'],
          ['umlaut', 'der Apfel', 'die Äpfel'],
        ],
      },
      { kind: 'example', text: 'die Kinder', gloss: 'the children' },
      { kind: 'example', text: 'die Äpfel', gloss: 'the apples', note: 'umlaut only, no ending' },
      { kind: 'example', text: 'die Männer', gloss: 'the men', note: 'umlaut + -er' },
      {
        kind: 'callout',
        style: 'tip',
        md: 'Whatever the gender was in the singular, the plural “the” is **die**: *der Mann → die Männer*, *das Buch → die Bücher*. Watch the umlauts — they are part of the plural, not decoration: *Stadt → Städte*.',
      },
    ],
    skillCells: [
      { cellId: 'pl-form', label: 'plural forms' },
      { cellId: 'pl-article', label: 'plural article' },
    ],
    introLexemeIds: ['de/noun/apfel', 'de/noun/auto'],
    drillItems: [
      {
        gen: 'plural',
        nounIds: [
          'de/noun/tisch',
          'de/noun/kind',
          'de/noun/frau',
          'de/noun/buch',
          'de/noun/apfel',
          'de/noun/stadt',
          'de/noun/mann',
        ],
        count: 5,
      },
      {
        gen: 'case-article',
        nounIds: ['de/noun/tisch', 'de/noun/frau', 'de/noun/kind', 'de/noun/apfel'],
        count: 3,
        case: 'nom',
        det: 'def',
        number: 'pl',
        frames: [{ tokens: ['___', '{noun}'], gloss: 'the {gloss} (plural)' }],
        cellId: 'pl-article',
      },
    ],
    errorHints: {
      wrongGenderArticle: 'Gender disappears in the plural — the article is always die.',
      wrongCaseArticle: 'Plural “the” in the nominative is die; den is the dative plural.',
    },
  },

  {
    id: 'de-nom-acc',
    lang: 'de',
    title: 'Nominative vs accusative',
    ruleSummary: 'Subject = nominative, direct object = accusative; only masculine changes: der → den, ein → einen.',
    cefr: 'A1',
    dependencies: ['de-noun-gender', 'de-regular-present'],
    explanation: [
      {
        kind: 'prose',
        md: 'The **subject** of a sentence stands in the **nominative** — the forms you already know (*der, die, das*). The **direct object** (whatever is seen, taken, found…) stands in the **accusative**. The good news: feminine and neuter look exactly the same in both cases. Only the **masculine** changes: **der → den**, **ein → einen**.',
      },
      {
        kind: 'table',
        caption: 'Articles: nominative vs accusative',
        header: ['', 'nominative', 'accusative'],
        rows: [
          ['masculine', 'der / ein', 'den / einen'],
          ['feminine', 'die / eine', 'die / eine'],
          ['neuter', 'das / ein', 'das / ein'],
        ],
        highlight: [
          [0, 1],
          [0, 2],
        ],
      },
      { kind: 'example', text: 'Der Mann trinkt Kaffee.', gloss: 'The man drinks coffee.', note: 'der Mann = subject → nominative' },
      { kind: 'example', text: 'Ich sehe den Mann.', gloss: 'I see the man.', note: 'den Mann = direct object → accusative' },
      { kind: 'example', text: 'Ich sehe den Studenten.', gloss: 'I see the student.', note: 'a few masculine nouns also add -en' },
      {
        kind: 'callout',
        style: 'warning',
        md: 'In German it’s the **article**, not the word order, that marks the object: *Den Mann sieht die Frau* still means the woman sees the man. A small group of masculine “weak” nouns (*der Student, der Junge*) adds **-(e)n** in the accusative: *den Studenten*, *den Jungen*.',
      },
    ],
    skillCells: [
      { cellId: 'acc.m', label: 'accusative masculine (den)' },
      { cellId: 'acc.f', label: 'accusative feminine (die)' },
      { cellId: 'acc.n', label: 'accusative neuter (das)' },
    ],
    introLexemeIds: ['de/verb/sehen', 'de/verb/finden', 'de/verb/nehmen', 'de/noun/student'],
    drillItems: [
      {
        gen: 'case-article',
        nounIds: ['de/noun/mann', 'de/noun/student', 'de/noun/tisch', 'de/noun/apfel'],
        count: 3,
        case: 'acc',
        det: 'def',
        number: 'sg',
        frames: [
          { tokens: ['Ich', 'sehe', '___', '{noun}'], gloss: 'I see the {gloss}' },
          { tokens: ['Ich', 'finde', '___', '{noun}'], gloss: 'I find the {gloss}' },
        ],
        cellId: 'acc.m',
      },
      {
        gen: 'case-article',
        nounIds: ['de/noun/frau', 'de/noun/tasche', 'de/noun/stadt'],
        count: 2,
        case: 'acc',
        det: 'def',
        number: 'sg',
        frames: [
          { tokens: ['Ich', 'sehe', '___', '{noun}'], gloss: 'I see the {gloss}' },
          { tokens: ['Ich', 'finde', '___', '{noun}'], gloss: 'I find the {gloss}' },
        ],
        cellId: 'acc.f',
      },
      {
        gen: 'case-article',
        nounIds: ['de/noun/buch', 'de/noun/auto', 'de/noun/brot'],
        count: 2,
        case: 'acc',
        det: 'def',
        number: 'sg',
        frames: [
          { tokens: ['Ich', 'sehe', '___', '{noun}'], gloss: 'I see the {gloss}' },
          { tokens: ['Ich', 'nehme', '___', '{noun}'], gloss: 'I take the {gloss}' },
        ],
        cellId: 'acc.n',
      },
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'de',
            sentence: [],
            gloss: 'Which sentence is correct? — “I see the man.”',
            answer: 'Ich sehe den Mann.',
            accepted: [],
            options: [
              { text: 'Ich sehe den Mann.' },
              { text: 'Ich sehe der Mann.', strategy: 'wrongCaseArticle' },
            ],
            skillIds: ['de-nom-acc:acc.m'],
          },
        ],
      },
    ],
    errorHints: {
      wrongCaseArticle: 'The direct object takes the accusative — and only masculine changes: der → den, ein → einen.',
      wrongGenderArticle: 'Check the noun’s gender first; feminine and neuter keep their nominative article in the accusative.',
    },
  },

  {
    id: 'de-negation',
    lang: 'de',
    title: 'nicht vs kein',
    ruleSummary: 'kein negates nouns with ein or no article (declines like ein: acc masc keinen); nicht negates everything else.',
    cefr: 'A1',
    dependencies: ['de-nom-acc'],
    explanation: [
      {
        kind: 'prose',
        md: 'German has two negators. **kein** negates a noun that has *ein* or **no article at all**: *Ich habe ein Auto → Ich habe **kein** Auto*; *Ich trinke Bier → Ich trinke **kein** Bier*. **nicht** negates everything else — verbs, adjectives, whole sentences — and usually comes **late** in the sentence: *Er arbeitet **nicht***.',
      },
      {
        kind: 'table',
        caption: 'kein declines exactly like ein',
        header: ['', 'masculine', 'feminine', 'neuter'],
        rows: [
          ['nominative', 'kein', 'keine', 'kein'],
          ['accusative', 'keinen', 'keine', 'kein'],
        ],
        highlight: [[1, 1]],
      },
      { kind: 'example', text: 'Ich habe kein Auto.', gloss: 'I don’t have a car.' },
      { kind: 'example', text: 'Ich sehe keinen Mann.', gloss: 'I don’t see a man.', note: 'accusative masculine → keinen' },
      { kind: 'example', text: 'Er arbeitet nicht.', gloss: 'He doesn’t work.' },
      {
        kind: 'callout',
        style: 'tip',
        md: 'Quick test: could you put **ein** in front of the thing you’re negating (or is it a bare noun like *Bier*)? Then use **kein** — declined like *ein*. Everything else gets **nicht**.',
      },
    ],
    skillCells: [{ cellId: 'core', label: 'nicht vs kein' }],
    introLexemeIds: ['de/noun/bier', 'de/noun/auto', 'de/noun/milch'],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Ich', 'trinke', '___', 'Bier.'],
            gapIndex: 2,
            gloss: 'I don’t drink beer.',
            answer: 'kein',
            accepted: [],
            options: [
              { text: 'kein' },
              { text: 'nicht', strategy: 'nichtKeinSwap' },
              { text: 'keinen', strategy: 'wrongCaseArticle' },
              { text: 'keine', strategy: 'wrongCaseArticle' },
            ],
            skillIds: ['de-negation:core'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Ich', 'habe', '___', 'Auto.'],
            gapIndex: 2,
            gloss: 'I don’t have a car.',
            answer: 'kein',
            accepted: [],
            options: [
              { text: 'kein' },
              { text: 'nicht', strategy: 'nichtKeinSwap' },
              { text: 'keinen', strategy: 'wrongCaseArticle' },
            ],
            skillIds: ['de-negation:core'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Er', 'arbeitet', '___'],
            gapIndex: 2,
            gloss: 'He doesn’t work.',
            answer: 'nicht',
            accepted: [],
            options: [
              { text: 'nicht' },
              { text: 'kein', strategy: 'nichtKeinSwap' },
              { text: 'keine', strategy: 'nichtKeinSwap' },
            ],
            skillIds: ['de-negation:core'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Ich', 'sehe', '___', 'Mann.'],
            gapIndex: 2,
            gloss: 'I don’t see a man.',
            answer: 'keinen',
            accepted: [],
            options: [
              { text: 'keinen' },
              { text: 'kein', strategy: 'wrongCaseArticle' },
              { text: 'keine', strategy: 'wrongCaseArticle' },
              { text: 'nicht', strategy: 'nichtKeinSwap' },
            ],
            skillIds: ['de-negation:core'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Sie', 'trinkt', '___', 'Milch.'],
            gapIndex: 2,
            gloss: 'She doesn’t drink milk.',
            answer: 'keine',
            accepted: [],
            options: [
              { text: 'keine' },
              { text: 'keinen', strategy: 'wrongCaseArticle' },
              { text: 'nicht', strategy: 'nichtKeinSwap' },
            ],
            skillIds: ['de-negation:core'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Der', 'Kaffee', 'ist', '___', 'gut.'],
            gapIndex: 3,
            gloss: 'The coffee is not good.',
            answer: 'nicht',
            accepted: [],
            options: [
              { text: 'nicht' },
              { text: 'kein', strategy: 'nichtKeinSwap' },
              { text: 'keinen', strategy: 'nichtKeinSwap' },
            ],
            skillIds: ['de-negation:core'],
          },
        ],
      },
    ],
    errorHints: {
      nichtKeinSwap: 'kein for nouns you could put ein before (or bare nouns); nicht for verbs, adjectives and everything else.',
      wrongCaseArticle: 'kein declines like ein — accusative masculine is keinen: Ich sehe keinen Mann.',
    },
  },

  {
    id: 'de-vowel-change',
    lang: 'de',
    title: 'Strong verbs: du/er vowel change',
    ruleSummary: 'Some verbs change their vowel in du and er/sie/es only: fahren → du fährst, essen → du isst.',
    cefr: 'A1',
    dependencies: ['de-regular-present'],
    explanation: [
      {
        kind: 'prose',
        md: 'A group of very common verbs — the **strong verbs** — changes its stem vowel in exactly two forms: **du** and **er/sie/es**. Three patterns: **a → ä** (*fahren → fährst/fährt*, *schlafen → schläfst*), **e → i** (*essen → isst*, *sprechen → sprichst*, *nehmen → nimmst*, *geben → gibst*) and **e → ie** (*lesen → liest*, *sehen → siehst*). All other forms are perfectly regular: *wir fahren*, *ihr fahrt*.',
      },
      {
        kind: 'table',
        caption: 'fahren & essen — the vowel changes in du and er only',
        header: ['', 'fahren (a → ä)', 'essen (e → i)'],
        rows: [
          ['ich', 'fahre', 'esse'],
          ['du', 'fährst', 'isst'],
          ['er / sie / es', 'fährt', 'isst'],
          ['wir', 'fahren', 'essen'],
          ['ihr', 'fahrt', 'esst'],
          ['sie / Sie', 'fahren', 'essen'],
        ],
        highlight: [
          [1, 1],
          [1, 2],
          [2, 1],
          [2, 2],
        ],
      },
      { kind: 'example', text: 'Du fährst nach Berlin.', gloss: 'You are driving to Berlin.' },
      { kind: 'example', text: 'Er isst Brot.', gloss: 'He eats bread.' },
      { kind: 'example', text: 'Wir fahren nach Berlin.', gloss: 'We are driving to Berlin.', note: 'wir keeps the stem — no change' },
      {
        kind: 'callout',
        style: 'warning',
        md: 'The change never leaves *du* and *er/sie/es*: **wir fahren, ihr fahrt** keep the plain stem. And *nehmen* doubles the *m* on top of the vowel change: *du nimmst, er nimmt*.',
      },
    ],
    skillCells: [
      { cellId: '1sg', label: 'ich form' },
      { cellId: '2sg', label: 'du form' },
      { cellId: '3sg', label: 'er/sie/es form' },
      { cellId: '1pl', label: 'wir form' },
      { cellId: '2pl', label: 'ihr form' },
      { cellId: '3pl', label: 'sie/Sie form' },
    ],
    introLexemeIds: [
      'de/verb/fahren',
      'de/verb/sehen',
      'de/verb/sprechen',
      'de/verb/schlafen',
      'de/verb/nehmen',
      'de/verb/geben',
    ],
    drillItems: [
      { gen: 'match-verb', verbId: 'de/verb/fahren', tense: 'pres' },
      { gen: 'conj', verbId: 'de/verb/essen', tense: 'pres', persons: ['2sg', '3sg'], type: 'mc' },
      { gen: 'conj', verbId: 'de/verb/fahren', tense: 'pres', persons: ['2sg', '1pl'], type: 'mc' },
      { gen: 'conj', verbId: 'de/verb/lesen', tense: 'pres', persons: ['3sg'], type: 'cloze' },
      { gen: 'conj', verbId: 'de/verb/schlafen', tense: 'pres', persons: ['2sg'], type: 'cloze' },
    ],
    errorHints: {
      missingVowelChange: 'This verb changes its vowel for du and er/sie/es: fährst, isst, liest.',
      wrongPerson: 'Only du and er/sie/es change the vowel — wir, ihr and sie/Sie keep the infinitive stem.',
      infinitive: 'That’s the dictionary form — conjugate it, and check the vowel.',
    },
  },

  {
    id: 'de-coord-conjunctions',
    lang: 'de',
    title: 'und, aber, oder, denn',
    ruleSummary: 'und, aber, oder, denn sit at “position zero” — the word order stays verb-second after them.',
    cefr: 'A1',
    dependencies: ['de-word-order-v2'],
    explanation: [
      {
        kind: 'prose',
        md: 'Four little connectors join whole sentences: **und** (and), **aber** (but), **oder** (or), **denn** (because). They occupy “**position zero**” — they don’t count as an element at all, so the clause after them keeps its normal verb-second order: *Ich trinke Kaffee, **aber** er trinkt Tee.* Nothing moves.',
      },
      {
        kind: 'table',
        caption: 'The four connectors',
        header: ['connector', 'meaning', 'example'],
        rows: [
          ['und', 'and', 'Ich lese und er schläft.'],
          ['aber', 'but', 'Ich arbeite, aber er schläft.'],
          ['oder', 'or', 'Trinkst du Kaffee oder Tee?'],
          ['denn', 'because', 'Ich lerne Deutsch, denn es ist schön.'],
        ],
      },
      { kind: 'example', text: 'Ich trinke Kaffee, aber er trinkt Tee.', gloss: 'I drink coffee, but he drinks tea.' },
      { kind: 'example', text: 'Trinkst du Kaffee oder Tee?', gloss: 'Do you drink coffee or tea?' },
      { kind: 'example', text: 'Ich lerne Deutsch, denn es ist schön.', gloss: 'I am learning German, because it is beautiful.' },
      {
        kind: 'callout',
        style: 'tip',
        md: 'Later you’ll meet **weil**, which also means “because” but kicks the verb to the end of its clause. **denn** is the easy one: subject + verb, exactly as usual.',
      },
    ],
    skillCells: [{ cellId: 'core', label: 'connectors' }],
    introLexemeIds: [],
    drillItems: [
      {
        gen: 'authored',
        exercises: [
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Ich', 'lerne', 'Deutsch,', '___', 'es', 'ist', 'schön.'],
            gapIndex: 3,
            gloss: 'I am learning German, because it is beautiful.',
            answer: 'denn',
            accepted: [],
            options: [
              { text: 'denn' },
              { text: 'aber', strategy: 'vocabConfusable' },
              { text: 'oder', strategy: 'vocabConfusable' },
              { text: 'und', strategy: 'vocabConfusable' },
            ],
            skillIds: ['de-coord-conjunctions:core'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Trinkst', 'du', 'Kaffee', '___', 'Tee?'],
            gapIndex: 3,
            gloss: 'Do you drink coffee or tea?',
            answer: 'oder',
            accepted: [],
            options: [
              { text: 'oder' },
              { text: 'und', strategy: 'vocabConfusable' },
              { text: 'denn', strategy: 'vocabConfusable' },
            ],
            skillIds: ['de-coord-conjunctions:core'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Ich', 'arbeite', 'heute,', '___', 'er', 'schläft.'],
            gapIndex: 3,
            gloss: 'I am working today, but he is sleeping.',
            answer: 'aber',
            accepted: [],
            options: [
              { text: 'aber' },
              { text: 'und', strategy: 'vocabConfusable' },
              { text: 'oder', strategy: 'vocabConfusable' },
              { text: 'denn', strategy: 'vocabConfusable' },
            ],
            skillIds: ['de-coord-conjunctions:core'],
          },
          {
            type: 'mc',
            lang: 'de',
            sentence: ['Er', 'isst', 'Brot', '___', 'trinkt', 'Wasser.'],
            gapIndex: 3,
            gloss: 'He eats bread and drinks water.',
            answer: 'und',
            accepted: [],
            options: [
              { text: 'und' },
              { text: 'oder', strategy: 'vocabConfusable' },
              { text: 'aber', strategy: 'vocabConfusable' },
              { text: 'denn', strategy: 'vocabConfusable' },
            ],
            skillIds: ['de-coord-conjunctions:core'],
          },
        ],
      },
      {
        gen: 'word-order',
        items: [
          { answer: 'Ich lese und er schläft', gloss: 'I read and he sleeps', cellId: 'core' },
          { answer: 'Er isst Brot aber ich esse Reis', gloss: 'He eats bread but I eat rice', cellId: 'core' },
        ],
      },
    ],
    errorHints: {
      vocabConfusable: 'und = and, aber = but, oder = or, denn = because — pick the one that matches the English.',
      v2Violation: 'After und, aber, oder and denn nothing moves: subject first, verb second, as usual.',
    },
  },
]
