import type { AdjEntry } from '../../types'

export const ES_ADJS: AdjEntry[] = [
  { id: 'es/adj/alto', lang: 'es', lemma: 'alto', gloss: 'tall', glossItForms: { m: 'alto', f: 'alta', mpl: 'alti', fpl: 'alte' }, tags: ['human'], es: {} },
  { id: 'es/adj/bajo', lang: 'es', lemma: 'bajo', gloss: 'short (height)', glossItForms: { m: 'basso', f: 'bassa', mpl: 'bassi', fpl: 'basse' }, tags: ['human'], es: {} },
  { id: 'es/adj/nuevo', lang: 'es', lemma: 'nuevo', gloss: 'new', glossItForms: { m: 'nuovo', f: 'nuova', mpl: 'nuovi', fpl: 'nuove' }, tags: ['object'], es: {} },
  { id: 'es/adj/viejo', lang: 'es', lemma: 'viejo', gloss: 'old', glossItForms: { m: 'vecchio', f: 'vecchia', mpl: 'vecchi', fpl: 'vecchie' }, tags: ['object', 'human'], es: {} },
  { id: 'es/adj/bonito', lang: 'es', lemma: 'bonito', gloss: 'pretty', glossItForms: { m: 'bello', f: 'bella', mpl: 'belli', fpl: 'belle' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/pequeño', lang: 'es', lemma: 'pequeño', gloss: 'small', glossItForms: { m: 'piccolo', f: 'piccola', mpl: 'piccoli', fpl: 'piccole' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/bueno', lang: 'es', lemma: 'bueno', gloss: 'good', glossItForms: { m: 'buono', f: 'buona', mpl: 'buoni', fpl: 'buone' }, tags: ['object', 'food'], es: {} },
  { id: 'es/adj/malo', lang: 'es', lemma: 'malo', gloss: 'bad', glossItForms: { m: 'cattivo', f: 'cattiva', mpl: 'cattivi', fpl: 'cattive' }, tags: ['object'], es: {} },
  { id: 'es/adj/rojo', lang: 'es', lemma: 'rojo', gloss: 'red', glossItForms: { m: 'rosso', f: 'rossa', mpl: 'rossi', fpl: 'rosse' }, tags: ['object'], es: {} },
  { id: 'es/adj/blanco', lang: 'es', lemma: 'blanco', gloss: 'white', glossItForms: { m: 'bianco', f: 'bianca', mpl: 'bianchi', fpl: 'bianche' }, tags: ['object'], es: {} },
  { id: 'es/adj/grande', lang: 'es', lemma: 'grande', gloss: 'big', glossItForms: { m: 'grande', f: 'grande', mpl: 'grandi', fpl: 'grandi' }, tags: ['object', 'place'], es: { invariable: true } },
  { id: 'es/adj/verde', lang: 'es', lemma: 'verde', gloss: 'green', glossItForms: { m: 'verde', f: 'verde', mpl: 'verdi', fpl: 'verdi' }, tags: ['object'], es: { invariable: true } },
  { id: 'es/adj/azul', lang: 'es', lemma: 'azul', gloss: 'blue', glossItForms: { m: 'blu', f: 'blu', mpl: 'blu', fpl: 'blu' }, tags: ['object'], es: { invariable: true } },
  { id: 'es/adj/feliz', lang: 'es', lemma: 'feliz', gloss: 'happy', glossItForms: { m: 'felice', f: 'felice', mpl: 'felici', fpl: 'felici' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/inteligente', lang: 'es', lemma: 'inteligente', gloss: 'intelligent', glossItForms: { m: 'intelligente', f: 'intelligente', mpl: 'intelligenti', fpl: 'intelligenti' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/simpático', lang: 'es', lemma: 'simpático', gloss: 'nice, friendly', glossItForms: { m: 'simpatico', f: 'simpatica', mpl: 'simpatici', fpl: 'simpatiche' }, tags: ['human'], es: {} },
  { id: 'es/adj/cansado', lang: 'es', lemma: 'cansado', gloss: 'tired', glossItForms: { m: 'stanco', f: 'stanca', mpl: 'stanchi', fpl: 'stanche' }, tags: ['human'], es: {} },
  { id: 'es/adj/contento', lang: 'es', lemma: 'contento', gloss: 'glad', glossItForms: { m: 'contento', f: 'contenta', mpl: 'contenti', fpl: 'contente' }, tags: ['human'], es: {} },
  { id: 'es/adj/enfermo', lang: 'es', lemma: 'enfermo', gloss: 'sick', glossItForms: { m: 'malato', f: 'malata', mpl: 'malati', fpl: 'malate' }, tags: ['human'], es: {} },
  { id: 'es/adj/caro', lang: 'es', lemma: 'caro', gloss: 'expensive', glossItForms: { m: 'caro', f: 'cara', mpl: 'cari', fpl: 'care' }, tags: ['object'], es: {} },
  { id: 'es/adj/barato', lang: 'es', lemma: 'barato', gloss: 'cheap', glossItForms: { m: 'economico', f: 'economica', mpl: 'economici', fpl: 'economiche' }, tags: ['object'], es: {} },
  { id: 'es/adj/difícil', lang: 'es', lemma: 'difícil', gloss: 'difficult', glossItForms: { m: 'difficile', f: 'difficile', mpl: 'difficili', fpl: 'difficili' }, tags: ['abstract'], es: { invariable: true } },
  { id: 'es/adj/fácil', lang: 'es', lemma: 'fácil', gloss: 'easy', glossItForms: { m: 'facile', f: 'facile', mpl: 'facili', fpl: 'facili' }, tags: ['abstract'], es: { invariable: true } },
  { id: 'es/adj/joven', lang: 'es', lemma: 'joven', gloss: 'young', glossItForms: { m: 'giovane', f: 'giovane', mpl: 'giovani', fpl: 'giovani' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/trabajador', lang: 'es', lemma: 'trabajador', gloss: 'hard-working', glossItForms: { m: 'lavoratore', f: 'lavoratrice', mpl: 'lavoratori', fpl: 'lavoratrici' }, tags: ['human'], es: { formsOverride: { m: 'trabajador', f: 'trabajadora', mpl: 'trabajadores', fpl: 'trabajadoras' } } },
  { id: 'es/adj/rápido', lang: 'es', lemma: 'rápido', gloss: 'fast', glossItForms: { m: 'veloce', f: 'veloce', mpl: 'veloci', fpl: 'veloci' }, tags: ['vehicle', 'human'], es: {} },
  { id: 'es/adj/lento', lang: 'es', lemma: 'lento', gloss: 'slow', glossItForms: { m: 'lento', f: 'lenta', mpl: 'lenti', fpl: 'lente' }, tags: ['vehicle', 'human'], es: {} },
  { id: 'es/adj/largo', lang: 'es', lemma: 'largo', gloss: 'long', glossItForms: { m: 'lungo', f: 'lunga', mpl: 'lunghi', fpl: 'lunghe' }, tags: ['object'], es: {} },
  { id: 'es/adj/corto', lang: 'es', lemma: 'corto', gloss: 'short (length)', glossItForms: { m: 'corto', f: 'corta', mpl: 'corti', fpl: 'corte' }, tags: ['object'], es: {} },
  { id: 'es/adj/guapo', lang: 'es', lemma: 'guapo', gloss: 'good-looking', glossItForms: { m: 'bello', f: 'bella', mpl: 'belli', fpl: 'belle' }, tags: ['human'], es: {} },
  { id: 'es/adj/divertido', lang: 'es', lemma: 'divertido', gloss: 'fun, funny', glossItForms: { m: 'divertente', f: 'divertente', mpl: 'divertenti', fpl: 'divertenti' }, tags: ['human'], es: {} },
  { id: 'es/adj/aburrido', lang: 'es', lemma: 'aburrido', gloss: 'boring', glossItForms: { m: 'noioso', f: 'noiosa', mpl: 'noiosi', fpl: 'noiose' }, tags: ['human'], es: {} },
  { id: 'es/adj/importante', lang: 'es', lemma: 'importante', gloss: 'important', glossItForms: { m: 'importante', f: 'importante', mpl: 'importanti', fpl: 'importanti' }, tags: ['abstract'], es: { invariable: true } },
  { id: 'es/adj/moreno', lang: 'es', lemma: 'moreno', gloss: 'dark-haired', glossItForms: { m: 'moro', f: 'mora', mpl: 'mori', fpl: 'more' }, tags: ['human'], es: {} },
  { id: 'es/adj/frío', lang: 'es', lemma: 'frío', gloss: 'cold', glossItForms: { m: 'freddo', f: 'fredda', mpl: 'freddi', fpl: 'fredde' }, tags: ['object', 'food', 'nature'], es: {} },
  { id: 'es/adj/caliente', lang: 'es', lemma: 'caliente', gloss: 'hot', glossItForms: { m: 'caldo', f: 'calda', mpl: 'caldi', fpl: 'calde' }, tags: ['food', 'drink', 'object'], es: { invariable: true } },
  { id: 'es/adj/sano', lang: 'es', lemma: 'sano', gloss: 'healthy', glossItForms: { m: 'sano', f: 'sana', mpl: 'sani', fpl: 'sane' }, tags: ['human', 'food'], es: {} },
  { id: 'es/adj/fuerte', lang: 'es', lemma: 'fuerte', gloss: 'strong', glossItForms: { m: 'forte', f: 'forte', mpl: 'forti', fpl: 'forti' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/débil', lang: 'es', lemma: 'débil', gloss: 'weak', glossItForms: { m: 'debole', f: 'debole', mpl: 'deboli', fpl: 'deboli' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/rico', lang: 'es', lemma: 'rico', gloss: 'rich / tasty', glossItForms: { m: 'ricco', f: 'ricca', mpl: 'ricchi', fpl: 'ricche' }, tags: ['human', 'food'], es: {} },
  { id: 'es/adj/pobre', lang: 'es', lemma: 'pobre', gloss: 'poor', glossItForms: { m: 'povero', f: 'povera', mpl: 'poveri', fpl: 'povere' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/limpio', lang: 'es', lemma: 'limpio', gloss: 'clean', glossItForms: { m: 'pulito', f: 'pulita', mpl: 'puliti', fpl: 'pulite' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/sucio', lang: 'es', lemma: 'sucio', gloss: 'dirty', glossItForms: { m: 'sporco', f: 'sporca', mpl: 'sporchi', fpl: 'sporche' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/lleno', lang: 'es', lemma: 'lleno', gloss: 'full', glossItForms: { m: 'pieno', f: 'piena', mpl: 'pieni', fpl: 'piene' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/vacío', lang: 'es', lemma: 'vacío', gloss: 'empty', glossItForms: { m: 'vuoto', f: 'vuota', mpl: 'vuoti', fpl: 'vuote' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/abierto', lang: 'es', lemma: 'abierto', gloss: 'open', glossItForms: { m: 'aperto', f: 'aperta', mpl: 'aperti', fpl: 'aperte' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/cerrado', lang: 'es', lemma: 'cerrado', gloss: 'closed', glossItForms: { m: 'chiuso', f: 'chiusa', mpl: 'chiusi', fpl: 'chiuse' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/tranquilo', lang: 'es', lemma: 'tranquilo', gloss: 'calm', glossItForms: { m: 'tranquillo', f: 'tranquilla', mpl: 'tranquilli', fpl: 'tranquille' }, tags: ['human', 'place'], es: {} },
  { id: 'es/adj/nervioso', lang: 'es', lemma: 'nervioso', gloss: 'nervous', glossItForms: { m: 'nervoso', f: 'nervosa', mpl: 'nervosi', fpl: 'nervose' }, tags: ['human'], es: {} },
  { id: 'es/adj/triste', lang: 'es', lemma: 'triste', gloss: 'sad', glossItForms: { m: 'triste', f: 'triste', mpl: 'tristi', fpl: 'tristi' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/serio', lang: 'es', lemma: 'serio', gloss: 'serious', glossItForms: { m: 'serio', f: 'seria', mpl: 'seri', fpl: 'serie' }, tags: ['human'], es: {} },
  { id: 'es/adj/amable', lang: 'es', lemma: 'amable', gloss: 'kind', glossItForms: { m: 'gentile', f: 'gentile', mpl: 'gentili', fpl: 'gentili' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/peligroso', lang: 'es', lemma: 'peligroso', gloss: 'dangerous', glossItForms: { m: 'pericoloso', f: 'pericolosa', mpl: 'pericolosi', fpl: 'pericolose' }, tags: ['place', 'object'], es: {} },
  { id: 'es/adj/seguro', lang: 'es', lemma: 'seguro', gloss: 'safe, sure', glossItForms: { m: 'sicuro', f: 'sicura', mpl: 'sicuri', fpl: 'sicure' }, tags: ['place', 'object', 'human'], es: {} },
  { id: 'es/adj/libre', lang: 'es', lemma: 'libre', gloss: 'free', glossItForms: { m: 'libero', f: 'libera', mpl: 'liberi', fpl: 'libere' }, tags: ['human', 'object'], es: { invariable: true } },
  { id: 'es/adj/ocupado', lang: 'es', lemma: 'ocupado', gloss: 'busy', glossItForms: { m: 'occupato', f: 'occupata', mpl: 'occupati', fpl: 'occupate' }, tags: ['human', 'object'], es: {} },
  { id: 'es/adj/próximo', lang: 'es', lemma: 'próximo', gloss: 'next', glossItForms: { m: 'prossimo', f: 'prossima', mpl: 'prossimi', fpl: 'prossime' }, tags: ['time'], es: {} },
  { id: 'es/adj/último', lang: 'es', lemma: 'último', gloss: 'last', glossItForms: { m: 'ultimo', f: 'ultima', mpl: 'ultimi', fpl: 'ultime' }, tags: ['time', 'object'], es: {} },
  { id: 'es/adj/primero', lang: 'es', lemma: 'primero', gloss: 'first', glossItForms: { m: 'primo', f: 'prima', mpl: 'primi', fpl: 'prime' }, tags: ['time', 'object'], es: {} },
]

export const ES_ADJ_BY_ID = new Map(ES_ADJS.map((a) => [a.id, a]))
