import type { AdjEntry } from '../../types'

export const ES_ADJS: AdjEntry[] = [
  { id: 'es/adj/alto', lang: 'es', lemma: 'alto', gloss: 'tall', glossItForms: { m: 'alto', f: 'alta', mpl: 'alti', fpl: 'alte' }, tags: ['human'], es: {} },
  { id: 'es/adj/bajo', lang: 'es', lemma: 'bajo', gloss: 'short (height)', glossItForms: { m: 'basso', f: 'bassa', mpl: 'bassi', fpl: 'basse' }, tags: ['human'], es: {} },
  { id: 'es/adj/nuevo', lang: 'es', lemma: 'nuevo', gloss: 'new', glossItForms: { m: 'nuovo', f: 'nuova', mpl: 'nuovi', fpl: 'nuove' }, tags: ['object'], es: {} },
  { id: 'es/adj/viejo', lang: 'es', lemma: 'viejo', gloss: 'old', glossItForms: { m: 'vecchio', f: 'vecchia', mpl: 'vecchi', fpl: 'vecchie' }, tags: ['object', 'human'], es: {} },
  { id: 'es/adj/bonito', lang: 'es', lemma: 'bonito', gloss: 'pretty', glossItForms: { m: 'bello', f: 'bella', mpl: 'belli', fpl: 'belle' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/pequeño', lang: 'es', lemma: 'pequeño', gloss: 'small', glossItForms: { m: 'piccolo', f: 'piccola', mpl: 'piccoli', fpl: 'piccole' }, tags: ['object', 'place'], es: {} },
  { id: 'es/adj/bueno', lang: 'es', lemma: 'bueno', gloss: 'good', glossItForms: { m: 'buono', f: 'buona', mpl: 'buoni', fpl: 'buone' }, tags: ['object', 'food'], es: {} },
  { id: 'es/adj/malo', lang: 'es', lemma: 'malo', gloss: 'bad', glossItForms: { m: 'cattivo', f: 'cattiva', mpl: 'cattivi', fpl: 'cattive' }, tags: ['object'], es: {} },
  { id: 'es/adj/rojo', lang: 'es', lemma: 'rojo', gloss: 'red', glossItForms: { m: 'rosso', f: 'rossa', mpl: 'rossi', fpl: 'rosse' }, tags: ['object'], es: {} },
  { id: 'es/adj/blanco', lang: 'es', lemma: 'blanco', gloss: 'white', glossItForms: { m: 'bianco', f: 'bianca', mpl: 'bianchi', fpl: 'bianche' }, tags: ['object'], es: {} },
  { id: 'es/adj/grande', lang: 'es', lemma: 'grande', gloss: 'big', glossItForms: { m: 'grande', f: 'grande', mpl: 'grandi', fpl: 'grandi' }, tags: ['object', 'place'], es: { invariable: true } },
  { id: 'es/adj/verde', lang: 'es', lemma: 'verde', gloss: 'green', glossItForms: { m: 'verde', f: 'verde', mpl: 'verdi', fpl: 'verdi' }, tags: ['object'], es: { invariable: true } },
  { id: 'es/adj/azul', lang: 'es', lemma: 'azul', gloss: 'blue', glossItForms: { m: 'blu', f: 'blu', mpl: 'blu', fpl: 'blu' }, tags: ['object'], es: { invariable: true } },
  { id: 'es/adj/feliz', lang: 'es', lemma: 'feliz', gloss: 'happy', glossItForms: { m: 'felice', f: 'felice', mpl: 'felici', fpl: 'felici' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/inteligente', lang: 'es', lemma: 'inteligente', gloss: 'intelligent', glossItForms: { m: 'intelligente', f: 'intelligente', mpl: 'intelligenti', fpl: 'intelligenti' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/simpático', lang: 'es', lemma: 'simpático', gloss: 'nice, friendly', glossItForms: { m: 'simpatico', f: 'simpatica', mpl: 'simpatici', fpl: 'simpatiche' }, tags: ['human'], es: {} },
  { id: 'es/adj/cansado', lang: 'es', lemma: 'cansado', gloss: 'tired', glossItForms: { m: 'stanco', f: 'stanca', mpl: 'stanchi', fpl: 'stanche' }, tags: ['human'], es: {} },
  { id: 'es/adj/contento', lang: 'es', lemma: 'contento', gloss: 'glad', glossItForms: { m: 'contento', f: 'contenta', mpl: 'contenti', fpl: 'contente' }, tags: ['human'], es: {} },
  { id: 'es/adj/enfermo', lang: 'es', lemma: 'enfermo', gloss: 'sick', glossItForms: { m: 'malato', f: 'malata', mpl: 'malati', fpl: 'malate' }, tags: ['human'], es: {} },
  { id: 'es/adj/caro', lang: 'es', lemma: 'caro', gloss: 'expensive', glossItForms: { m: 'caro', f: 'cara', mpl: 'cari', fpl: 'care' }, tags: ['object'], es: {} },
  { id: 'es/adj/barato', lang: 'es', lemma: 'barato', gloss: 'cheap', glossItForms: { m: 'economico', f: 'economica', mpl: 'economici', fpl: 'economiche' }, tags: ['object'], es: {} },
  { id: 'es/adj/difícil', lang: 'es', lemma: 'difícil', gloss: 'difficult', glossItForms: { m: 'difficile', f: 'difficile', mpl: 'difficili', fpl: 'difficili' }, tags: ['abstract'], es: { invariable: true } },
  { id: 'es/adj/fácil', lang: 'es', lemma: 'fácil', gloss: 'easy', glossItForms: { m: 'facile', f: 'facile', mpl: 'facili', fpl: 'facili' }, tags: ['abstract'], es: { invariable: true } },
  { id: 'es/adj/joven', lang: 'es', lemma: 'joven', gloss: 'young', glossItForms: { m: 'giovane', f: 'giovane', mpl: 'giovani', fpl: 'giovani' }, tags: ['human'], es: { invariable: true } },
  { id: 'es/adj/trabajador', lang: 'es', lemma: 'trabajador', gloss: 'hard-working', glossItForms: { m: 'lavoratore', f: 'lavoratrice', mpl: 'lavoratori', fpl: 'lavoratrici' }, tags: ['human'], es: { formsOverride: { m: 'trabajador', f: 'trabajadora', mpl: 'trabajadores', fpl: 'trabajadoras' } } },
  { id: 'es/adj/rápido', lang: 'es', lemma: 'rápido', gloss: 'fast', glossItForms: { m: 'veloce', f: 'veloce', mpl: 'veloci', fpl: 'veloci' }, tags: ['vehicle', 'human'], es: {} },
  { id: 'es/adj/lento', lang: 'es', lemma: 'lento', gloss: 'slow', glossItForms: { m: 'lento', f: 'lenta', mpl: 'lenti', fpl: 'lente' }, tags: ['vehicle', 'human'], es: {} },
  { id: 'es/adj/largo', lang: 'es', lemma: 'largo', gloss: 'long', glossItForms: { m: 'lungo', f: 'lunga', mpl: 'lunghi', fpl: 'lunghe' }, tags: ['object'], es: {} },
  { id: 'es/adj/corto', lang: 'es', lemma: 'corto', gloss: 'short (length)', glossItForms: { m: 'corto', f: 'corta', mpl: 'corti', fpl: 'corte' }, tags: ['object'], es: {} },
  { id: 'es/adj/guapo', lang: 'es', lemma: 'guapo', gloss: 'good-looking', glossItForms: { m: 'bello', f: 'bella', mpl: 'belli', fpl: 'belle' }, tags: ['human'], es: {} },
  { id: 'es/adj/divertido', lang: 'es', lemma: 'divertido', gloss: 'fun, funny', glossItForms: { m: 'divertente', f: 'divertente', mpl: 'divertenti', fpl: 'divertenti' }, tags: ['human'], es: {} },
  { id: 'es/adj/aburrido', lang: 'es', lemma: 'aburrido', gloss: 'boring', glossItForms: { m: 'noioso', f: 'noiosa', mpl: 'noiosi', fpl: 'noiose' }, tags: ['human'], es: {} },
  { id: 'es/adj/importante', lang: 'es', lemma: 'importante', gloss: 'important', glossItForms: { m: 'importante', f: 'importante', mpl: 'importanti', fpl: 'importanti' }, tags: ['abstract'], es: { invariable: true } },
  { id: 'es/adj/moreno', lang: 'es', lemma: 'moreno', gloss: 'dark-haired', glossItForms: { m: 'moro', f: 'mora', mpl: 'mori', fpl: 'more' }, tags: ['human'], es: {} },
]

export const ES_ADJ_BY_ID = new Map(ES_ADJS.map((a) => [a.id, a]))
