import type { NounEntry } from '../../types'

// Starter nouns (M3). Grows with each unit's vocab packs.
export const ES_NOUNS: NounEntry[] = [
  { id: 'es/noun/casa', lang: 'es', lemma: 'casa', gloss: 'house', glossIt: 'la casa', glossItPl: 'le case', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/libro', lang: 'es', lemma: 'libro', gloss: 'book', glossIt: 'il libro', glossItPl: 'i libri', tags: ['object'], es: { gender: 'm' } },
  { id: 'es/noun/agua', lang: 'es', lemma: 'agua', gloss: 'water', glossIt: 'l’acqua', glossItPl: 'le acque', tags: ['drink'], es: { gender: 'f', singularArticle: 'el' } },
  { id: 'es/noun/café', lang: 'es', lemma: 'café', gloss: 'coffee', glossIt: 'il caffè', glossItPl: 'i caffè', tags: ['drink'], es: { gender: 'm' } },
  { id: 'es/noun/pan', lang: 'es', lemma: 'pan', gloss: 'bread', glossIt: 'il pane', glossItPl: 'i pani', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/manzana', lang: 'es', lemma: 'manzana', gloss: 'apple', glossIt: 'la mela', glossItPl: 'le mele', tags: ['food'], es: { gender: 'f' } },
  { id: 'es/noun/mujer', lang: 'es', lemma: 'mujer', gloss: 'woman', glossIt: 'la donna', glossItPl: 'le donne', tags: ['human'], es: { gender: 'f', pluralIrregular: 'mujeres' } },
  { id: 'es/noun/hombre', lang: 'es', lemma: 'hombre', gloss: 'man', glossIt: 'l’uomo', glossItPl: 'gli uomini', tags: ['human'], es: { gender: 'm' } },
  { id: 'es/noun/amigo', lang: 'es', lemma: 'amigo', gloss: 'friend', glossIt: 'l’amico', glossItPl: 'gli amici', tags: ['human'], es: { gender: 'm' } },
  { id: 'es/noun/ciudad', lang: 'es', lemma: 'ciudad', gloss: 'city', glossIt: 'la città', glossItPl: 'le città', tags: ['place'], es: { gender: 'f', pluralIrregular: 'ciudades' } },
  { id: 'es/noun/trabajo', lang: 'es', lemma: 'trabajo', gloss: 'job', glossIt: 'il lavoro', glossItPl: 'i lavori', tags: ['abstract'], es: { gender: 'm' } },
  { id: 'es/noun/familia', lang: 'es', lemma: 'familia', gloss: 'family', glossIt: 'la famiglia', glossItPl: 'le famiglie', tags: ['family'], es: { gender: 'f' } },
  // family
  { id: 'es/noun/padre', lang: 'es', lemma: 'padre', gloss: 'father', glossIt: 'il padre', glossItPl: 'i padri', tags: ['family', 'human'], es: { gender: 'm' } },
  { id: 'es/noun/madre', lang: 'es', lemma: 'madre', gloss: 'mother', glossIt: 'la madre', glossItPl: 'le madri', tags: ['family', 'human'], es: { gender: 'f' } },
  { id: 'es/noun/hermano', lang: 'es', lemma: 'hermano', gloss: 'brother', glossIt: 'il fratello', glossItPl: 'i fratelli', tags: ['family', 'human'], es: { gender: 'm' } },
  { id: 'es/noun/hermana', lang: 'es', lemma: 'hermana', gloss: 'sister', glossIt: 'la sorella', glossItPl: 'le sorelle', tags: ['family', 'human'], es: { gender: 'f' } },
  { id: 'es/noun/hijo', lang: 'es', lemma: 'hijo', gloss: 'son', glossIt: 'il figlio', glossItPl: 'i figli', tags: ['family', 'human'], es: { gender: 'm' } },
  { id: 'es/noun/hija', lang: 'es', lemma: 'hija', gloss: 'daughter', glossIt: 'la figlia', glossItPl: 'le figlie', tags: ['family', 'human'], es: { gender: 'f' } },
  { id: 'es/noun/abuelo', lang: 'es', lemma: 'abuelo', gloss: 'grandfather', glossIt: 'il nonno', glossItPl: 'i nonni', tags: ['family', 'human'], es: { gender: 'm' } },
  { id: 'es/noun/abuela', lang: 'es', lemma: 'abuela', gloss: 'grandmother', glossIt: 'la nonna', glossItPl: 'le nonne', tags: ['family', 'human'], es: { gender: 'f' } },
  // people & professions
  { id: 'es/noun/profesor', lang: 'es', lemma: 'profesor', gloss: 'teacher (male)', glossIt: 'il professore', glossItPl: 'i professori', tags: ['human', 'profession'], es: { gender: 'm' } },
  { id: 'es/noun/profesora', lang: 'es', lemma: 'profesora', gloss: 'teacher (female)', glossIt: 'la professoressa', glossItPl: 'le professoresse', tags: ['human', 'profession'], es: { gender: 'f' } },
  { id: 'es/noun/estudiante', lang: 'es', lemma: 'estudiante', gloss: 'student', glossIt: 'lo studente', glossItPl: 'gli studenti', tags: ['human', 'profession'], es: { gender: 'm' } },
  { id: 'es/noun/médico', lang: 'es', lemma: 'médico', gloss: 'doctor (male)', glossIt: 'il medico', glossItPl: 'i medici', tags: ['human', 'profession'], es: { gender: 'm' } },
  { id: 'es/noun/médica', lang: 'es', lemma: 'médica', gloss: 'doctor (female)', glossIt: 'la dottoressa', glossItPl: 'le dottoresse', tags: ['human', 'profession'], es: { gender: 'f' } },
  { id: 'es/noun/niño', lang: 'es', lemma: 'niño', gloss: 'boy', glossIt: 'il bambino', glossItPl: 'i bambini', tags: ['human'], es: { gender: 'm' } },
  { id: 'es/noun/niña', lang: 'es', lemma: 'niña', gloss: 'girl', glossIt: 'la bambina', glossItPl: 'le bambine', tags: ['human'], es: { gender: 'f' } },
  // food & drink
  { id: 'es/noun/leche', lang: 'es', lemma: 'leche', gloss: 'milk', glossIt: 'il latte', glossItPl: 'il latte', tags: ['drink'], es: { gender: 'f' } },
  { id: 'es/noun/queso', lang: 'es', lemma: 'queso', gloss: 'cheese', glossIt: 'il formaggio', glossItPl: 'i formaggi', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/huevo', lang: 'es', lemma: 'huevo', gloss: 'egg', glossIt: 'l’uovo', glossItPl: 'le uova', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/carne', lang: 'es', lemma: 'carne', gloss: 'meat', glossIt: 'la carne', glossItPl: 'le carni', tags: ['food'], es: { gender: 'f' } },
  { id: 'es/noun/pescado', lang: 'es', lemma: 'pescado', gloss: 'fish', glossPlural: 'fish', glossIt: 'il pesce', glossItPl: 'i pesci', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/arroz', lang: 'es', lemma: 'arroz', gloss: 'rice', glossIt: 'il riso', glossItPl: 'il riso', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/fruta', lang: 'es', lemma: 'fruta', gloss: 'fruit', glossIt: 'la frutta', glossItPl: 'la frutta', tags: ['food'], es: { gender: 'f' } },
  { id: 'es/noun/naranja', lang: 'es', lemma: 'naranja', gloss: 'orange', glossIt: 'l’arancia', glossItPl: 'le arance', tags: ['food'], es: { gender: 'f' } },
  { id: 'es/noun/vino', lang: 'es', lemma: 'vino', gloss: 'wine', glossIt: 'il vino', glossItPl: 'i vini', tags: ['drink'], es: { gender: 'm' } },
  { id: 'es/noun/cerveza', lang: 'es', lemma: 'cerveza', gloss: 'beer', glossIt: 'la birra', glossItPl: 'le birre', tags: ['drink'], es: { gender: 'f' } },
  { id: 'es/noun/té', lang: 'es', lemma: 'té', gloss: 'tea', glossIt: 'il tè', glossItPl: 'i tè', tags: ['drink'], es: { gender: 'm' } },
  // places
  { id: 'es/noun/escuela', lang: 'es', lemma: 'escuela', gloss: 'school', glossIt: 'la scuola', glossItPl: 'le scuole', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/restaurante', lang: 'es', lemma: 'restaurante', gloss: 'restaurant', glossIt: 'il ristorante', glossItPl: 'i ristoranti', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/tienda', lang: 'es', lemma: 'tienda', gloss: 'shop', glossIt: 'il negozio', glossItPl: 'i negozi', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/parque', lang: 'es', lemma: 'parque', gloss: 'park', glossIt: 'il parco', glossItPl: 'i parchi', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/calle', lang: 'es', lemma: 'calle', gloss: 'street', glossIt: 'la strada', glossItPl: 'le strade', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/playa', lang: 'es', lemma: 'playa', gloss: 'beach', glossPlural: 'beaches', glossIt: 'la spiaggia', glossItPl: 'le spiagge', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/país', lang: 'es', lemma: 'país', gloss: 'country', glossPlural: 'countries', glossIt: 'la nazione', glossItPl: 'le nazioni', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/pueblo', lang: 'es', lemma: 'pueblo', gloss: 'town', glossIt: 'il paese', glossItPl: 'i paesi', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/mercado', lang: 'es', lemma: 'mercado', gloss: 'market', glossIt: 'il mercato', glossItPl: 'i mercati', tags: ['place'], es: { gender: 'm' } },
  // everyday objects
  { id: 'es/noun/mesa', lang: 'es', lemma: 'mesa', gloss: 'table', glossIt: 'il tavolo', glossItPl: 'i tavoli', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/silla', lang: 'es', lemma: 'silla', gloss: 'chair', glossIt: 'la sedia', glossItPl: 'le sedie', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/puerta', lang: 'es', lemma: 'puerta', gloss: 'door', glossIt: 'la porta', glossItPl: 'le porte', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/ventana', lang: 'es', lemma: 'ventana', gloss: 'window', glossIt: 'la finestra', glossItPl: 'le finestre', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/coche', lang: 'es', lemma: 'coche', gloss: 'car', glossIt: 'la macchina', glossItPl: 'le macchine', tags: ['vehicle'], es: { gender: 'm' } },
  { id: 'es/noun/teléfono', lang: 'es', lemma: 'teléfono', gloss: 'phone', glossIt: 'il telefono', glossItPl: 'i telefoni', tags: ['object'], es: { gender: 'm' } },
  { id: 'es/noun/ordenador', lang: 'es', lemma: 'ordenador', gloss: 'computer', glossIt: 'il computer', glossItPl: 'i computer', tags: ['object'], es: { gender: 'm' } },
  { id: 'es/noun/ropa', lang: 'es', lemma: 'ropa', gloss: 'clothing', glossPlural: 'clothes', glossIt: 'i vestiti', glossItPl: 'i vestiti', tags: ['clothing'], es: { gender: 'f' } },
  { id: 'es/noun/zapato', lang: 'es', lemma: 'zapato', gloss: 'shoe', glossIt: 'la scarpa', glossItPl: 'le scarpe', tags: ['clothing'], es: { gender: 'm' } },
  { id: 'es/noun/bolso', lang: 'es', lemma: 'bolso', gloss: 'bag', glossIt: 'la borsa', glossItPl: 'le borse', tags: ['object'], es: { gender: 'm' } },
  // time & abstract
  { id: 'es/noun/día', lang: 'es', lemma: 'día', gloss: 'day', glossIt: 'il giorno', glossItPl: 'i giorni', tags: ['time'], es: { gender: 'm' } },
  { id: 'es/noun/noche', lang: 'es', lemma: 'noche', gloss: 'night', glossIt: 'la notte', glossItPl: 'le notti', tags: ['time'], es: { gender: 'f' } },
  { id: 'es/noun/semana', lang: 'es', lemma: 'semana', gloss: 'week', glossIt: 'la settimana', glossItPl: 'le settimane', tags: ['time'], es: { gender: 'f' } },
  { id: 'es/noun/año', lang: 'es', lemma: 'año', gloss: 'year', glossIt: 'l’anno', glossItPl: 'gli anni', tags: ['time'], es: { gender: 'm' } },
  { id: 'es/noun/hora', lang: 'es', lemma: 'hora', gloss: 'hour', glossIt: 'l’ora', glossItPl: 'le ore', tags: ['time'], es: { gender: 'f' } },
  { id: 'es/noun/nombre', lang: 'es', lemma: 'nombre', gloss: 'name', glossIt: 'il nome', glossItPl: 'i nomi', tags: ['abstract'], es: { gender: 'm' } },
  { id: 'es/noun/idioma', lang: 'es', lemma: 'idioma', gloss: 'language', glossIt: 'la lingua', glossItPl: 'le lingue', tags: ['abstract'], es: { gender: 'm' } },
  // house & rooms
  { id: 'es/noun/cocina', lang: 'es', lemma: 'cocina', gloss: 'kitchen', glossIt: 'la cucina', glossItPl: 'le cucine', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/baño', lang: 'es', lemma: 'baño', gloss: 'bathroom', glossIt: 'il bagno', glossItPl: 'i bagni', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/dormitorio', lang: 'es', lemma: 'dormitorio', gloss: 'bedroom', glossIt: 'la camera da letto', glossItPl: 'le camere da letto', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/salón', lang: 'es', lemma: 'salón', gloss: 'living room', glossIt: 'il soggiorno', glossItPl: 'i soggiorni', tags: ['place'], es: { gender: 'm', pluralIrregular: 'salones' } },
  { id: 'es/noun/cama', lang: 'es', lemma: 'cama', gloss: 'bed', glossIt: 'il letto', glossItPl: 'i letti', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/ducha', lang: 'es', lemma: 'ducha', gloss: 'shower', glossIt: 'la doccia', glossItPl: 'le docce', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/jardín', lang: 'es', lemma: 'jardín', gloss: 'garden', glossIt: 'il giardino', glossItPl: 'i giardini', tags: ['place', 'nature'], es: { gender: 'm', pluralIrregular: 'jardines' } },
  { id: 'es/noun/espejo', lang: 'es', lemma: 'espejo', gloss: 'mirror', glossIt: 'lo specchio', glossItPl: 'gli specchi', tags: ['object'], es: { gender: 'm' } },
  // clothes & shopping
  { id: 'es/noun/camisa', lang: 'es', lemma: 'camisa', gloss: 'shirt', glossIt: 'la camicia', glossItPl: 'le camicie', tags: ['clothing'], es: { gender: 'f' } },
  { id: 'es/noun/camiseta', lang: 'es', lemma: 'camiseta', gloss: 'T-shirt', glossIt: 'la maglietta', glossItPl: 'le magliette', tags: ['clothing'], es: { gender: 'f' } },
  { id: 'es/noun/pantalón', lang: 'es', lemma: 'pantalón', gloss: 'trousers', glossPlural: 'trousers', glossIt: 'i pantaloni', glossItPl: 'i pantaloni', tags: ['clothing'], es: { gender: 'm', pluralIrregular: 'pantalones' } },
  { id: 'es/noun/vestido', lang: 'es', lemma: 'vestido', gloss: 'dress', glossPlural: 'dresses', glossIt: 'il vestito', glossItPl: 'i vestiti', tags: ['clothing'], es: { gender: 'm' } },
  { id: 'es/noun/falda', lang: 'es', lemma: 'falda', gloss: 'skirt', glossIt: 'la gonna', glossItPl: 'le gonne', tags: ['clothing'], es: { gender: 'f' } },
  { id: 'es/noun/abrigo', lang: 'es', lemma: 'abrigo', gloss: 'coat', glossIt: 'il cappotto', glossItPl: 'i cappotti', tags: ['clothing'], es: { gender: 'm' } },
  { id: 'es/noun/chaqueta', lang: 'es', lemma: 'chaqueta', gloss: 'jacket', glossIt: 'la giacca', glossItPl: 'le giacche', tags: ['clothing'], es: { gender: 'f' } },
  { id: 'es/noun/sombrero', lang: 'es', lemma: 'sombrero', gloss: 'hat', glossIt: 'il cappello', glossItPl: 'i cappelli', tags: ['clothing'], es: { gender: 'm' } },
  { id: 'es/noun/dinero', lang: 'es', lemma: 'dinero', gloss: 'money', glossIt: 'i soldi', glossItPl: 'i soldi', tags: ['abstract'], es: { gender: 'm' } },
  { id: 'es/noun/precio', lang: 'es', lemma: 'precio', gloss: 'price', glossIt: 'il prezzo', glossItPl: 'i prezzi', tags: ['abstract'], es: { gender: 'm' } },
  { id: 'es/noun/regalo', lang: 'es', lemma: 'regalo', gloss: 'gift', glossIt: 'il regalo', glossItPl: 'i regali', tags: ['object'], es: { gender: 'm' } },
  // travel
  { id: 'es/noun/viaje', lang: 'es', lemma: 'viaje', gloss: 'trip', glossIt: 'il viaggio', glossItPl: 'i viaggi', tags: ['abstract'], es: { gender: 'm' } },
  { id: 'es/noun/tren', lang: 'es', lemma: 'tren', gloss: 'train', glossIt: 'il treno', glossItPl: 'i treni', tags: ['vehicle'], es: { gender: 'm' } },
  { id: 'es/noun/avión', lang: 'es', lemma: 'avión', gloss: 'plane', glossIt: 'l’aereo', glossItPl: 'gli aerei', tags: ['vehicle'], es: { gender: 'm', pluralIrregular: 'aviones' } },
  { id: 'es/noun/autobús', lang: 'es', lemma: 'autobús', gloss: 'bus', glossPlural: 'buses', glossIt: 'l’autobus', glossItPl: 'gli autobus', tags: ['vehicle'], es: { gender: 'm', pluralIrregular: 'autobuses' } },
  { id: 'es/noun/hotel', lang: 'es', lemma: 'hotel', gloss: 'hotel', glossIt: 'l’albergo', glossItPl: 'gli alberghi', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/maleta', lang: 'es', lemma: 'maleta', gloss: 'suitcase', glossIt: 'la valigia', glossItPl: 'le valigie', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/billete', lang: 'es', lemma: 'billete', gloss: 'ticket', glossIt: 'il biglietto', glossItPl: 'i biglietti', tags: ['object'], es: { gender: 'm' } },
  { id: 'es/noun/aeropuerto', lang: 'es', lemma: 'aeropuerto', gloss: 'airport', glossIt: 'l’aeroporto', glossItPl: 'gli aeroporti', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/mar', lang: 'es', lemma: 'mar', gloss: 'sea', glossIt: 'il mare', glossItPl: 'i mari', tags: ['nature', 'place'], es: { gender: 'm' } },
  { id: 'es/noun/montaña', lang: 'es', lemma: 'montaña', gloss: 'mountain', glossIt: 'la montagna', glossItPl: 'le montagne', tags: ['nature', 'place'], es: { gender: 'f' } },
  // routine & meals
  { id: 'es/noun/desayuno', lang: 'es', lemma: 'desayuno', gloss: 'breakfast', glossIt: 'la colazione', glossItPl: 'le colazioni', tags: ['food', 'daily-routine'], es: { gender: 'm' } },
  { id: 'es/noun/comida', lang: 'es', lemma: 'comida', gloss: 'lunch, meal', glossIt: 'il pranzo', glossItPl: 'i pranzi', tags: ['food', 'daily-routine'], es: { gender: 'f' } },
  { id: 'es/noun/cena', lang: 'es', lemma: 'cena', gloss: 'dinner', glossIt: 'la cena', glossItPl: 'le cene', tags: ['food', 'daily-routine'], es: { gender: 'f' } },
  { id: 'es/noun/mañana', lang: 'es', lemma: 'mañana', gloss: 'morning', glossIt: 'la mattina', glossItPl: 'le mattine', tags: ['time'], es: { gender: 'f' } },
  { id: 'es/noun/tarde', lang: 'es', lemma: 'tarde', gloss: 'afternoon', glossIt: 'il pomeriggio', glossItPl: 'i pomeriggi', tags: ['time'], es: { gender: 'f' } },
  { id: 'es/noun/minuto', lang: 'es', lemma: 'minuto', gloss: 'minute', glossIt: 'il minuto', glossItPl: 'i minuti', tags: ['time'], es: { gender: 'm' } },
  { id: 'es/noun/momento', lang: 'es', lemma: 'momento', gloss: 'moment', glossIt: 'il momento', glossItPl: 'i momenti', tags: ['time'], es: { gender: 'm' } },
  { id: 'es/noun/fiesta', lang: 'es', lemma: 'fiesta', gloss: 'party', glossPlural: 'parties', glossIt: 'la festa', glossItPl: 'le feste', tags: ['abstract'], es: { gender: 'f' } },
]

export const ES_NOUN_BY_ID = new Map(ES_NOUNS.map((n) => [n.id, n]))
