import type { NounEntry } from '../../types'

// Starter nouns (M3). Grows with each unit's vocab packs.
export const ES_NOUNS: NounEntry[] = [
  { id: 'es/noun/casa', lang: 'es', lemma: 'casa', gloss: 'house', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/libro', lang: 'es', lemma: 'libro', gloss: 'book', tags: ['object'], es: { gender: 'm' } },
  { id: 'es/noun/agua', lang: 'es', lemma: 'agua', gloss: 'water', tags: ['drink'], es: { gender: 'f', singularArticle: 'el' } },
  { id: 'es/noun/café', lang: 'es', lemma: 'café', gloss: 'coffee', tags: ['drink'], es: { gender: 'm' } },
  { id: 'es/noun/pan', lang: 'es', lemma: 'pan', gloss: 'bread', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/manzana', lang: 'es', lemma: 'manzana', gloss: 'apple', tags: ['food'], es: { gender: 'f' } },
  { id: 'es/noun/mujer', lang: 'es', lemma: 'mujer', gloss: 'woman', tags: ['human'], es: { gender: 'f', pluralIrregular: 'mujeres' } },
  { id: 'es/noun/hombre', lang: 'es', lemma: 'hombre', gloss: 'man', tags: ['human'], es: { gender: 'm' } },
  { id: 'es/noun/amigo', lang: 'es', lemma: 'amigo', gloss: 'friend', tags: ['human'], es: { gender: 'm' } },
  { id: 'es/noun/ciudad', lang: 'es', lemma: 'ciudad', gloss: 'city', tags: ['place'], es: { gender: 'f', pluralIrregular: 'ciudades' } },
  { id: 'es/noun/trabajo', lang: 'es', lemma: 'trabajo', gloss: 'job', tags: ['abstract'], es: { gender: 'm' } },
  { id: 'es/noun/familia', lang: 'es', lemma: 'familia', gloss: 'family', tags: ['family'], es: { gender: 'f' } },
  // family
  { id: 'es/noun/padre', lang: 'es', lemma: 'padre', gloss: 'father', tags: ['family', 'human'], es: { gender: 'm' } },
  { id: 'es/noun/madre', lang: 'es', lemma: 'madre', gloss: 'mother', tags: ['family', 'human'], es: { gender: 'f' } },
  { id: 'es/noun/hermano', lang: 'es', lemma: 'hermano', gloss: 'brother', tags: ['family', 'human'], es: { gender: 'm' } },
  { id: 'es/noun/hermana', lang: 'es', lemma: 'hermana', gloss: 'sister', tags: ['family', 'human'], es: { gender: 'f' } },
  { id: 'es/noun/hijo', lang: 'es', lemma: 'hijo', gloss: 'son', tags: ['family', 'human'], es: { gender: 'm' } },
  { id: 'es/noun/hija', lang: 'es', lemma: 'hija', gloss: 'daughter', tags: ['family', 'human'], es: { gender: 'f' } },
  { id: 'es/noun/abuelo', lang: 'es', lemma: 'abuelo', gloss: 'grandfather', tags: ['family', 'human'], es: { gender: 'm' } },
  { id: 'es/noun/abuela', lang: 'es', lemma: 'abuela', gloss: 'grandmother', tags: ['family', 'human'], es: { gender: 'f' } },
  // people & professions
  { id: 'es/noun/profesor', lang: 'es', lemma: 'profesor', gloss: 'teacher (male)', tags: ['human', 'profession'], es: { gender: 'm' } },
  { id: 'es/noun/profesora', lang: 'es', lemma: 'profesora', gloss: 'teacher (female)', tags: ['human', 'profession'], es: { gender: 'f' } },
  { id: 'es/noun/estudiante', lang: 'es', lemma: 'estudiante', gloss: 'student', tags: ['human', 'profession'], es: { gender: 'm' } },
  { id: 'es/noun/médico', lang: 'es', lemma: 'médico', gloss: 'doctor (male)', tags: ['human', 'profession'], es: { gender: 'm' } },
  { id: 'es/noun/médica', lang: 'es', lemma: 'médica', gloss: 'doctor (female)', tags: ['human', 'profession'], es: { gender: 'f' } },
  { id: 'es/noun/niño', lang: 'es', lemma: 'niño', gloss: 'boy', tags: ['human'], es: { gender: 'm' } },
  { id: 'es/noun/niña', lang: 'es', lemma: 'niña', gloss: 'girl', tags: ['human'], es: { gender: 'f' } },
  // food & drink
  { id: 'es/noun/leche', lang: 'es', lemma: 'leche', gloss: 'milk', tags: ['drink'], es: { gender: 'f' } },
  { id: 'es/noun/queso', lang: 'es', lemma: 'queso', gloss: 'cheese', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/huevo', lang: 'es', lemma: 'huevo', gloss: 'egg', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/carne', lang: 'es', lemma: 'carne', gloss: 'meat', tags: ['food'], es: { gender: 'f' } },
  { id: 'es/noun/pescado', lang: 'es', lemma: 'pescado', gloss: 'fish', glossPlural: 'fish', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/arroz', lang: 'es', lemma: 'arroz', gloss: 'rice', tags: ['food'], es: { gender: 'm' } },
  { id: 'es/noun/fruta', lang: 'es', lemma: 'fruta', gloss: 'fruit', tags: ['food'], es: { gender: 'f' } },
  { id: 'es/noun/naranja', lang: 'es', lemma: 'naranja', gloss: 'orange', tags: ['food'], es: { gender: 'f' } },
  { id: 'es/noun/vino', lang: 'es', lemma: 'vino', gloss: 'wine', tags: ['drink'], es: { gender: 'm' } },
  { id: 'es/noun/cerveza', lang: 'es', lemma: 'cerveza', gloss: 'beer', tags: ['drink'], es: { gender: 'f' } },
  { id: 'es/noun/té', lang: 'es', lemma: 'té', gloss: 'tea', tags: ['drink'], es: { gender: 'm' } },
  // places
  { id: 'es/noun/escuela', lang: 'es', lemma: 'escuela', gloss: 'school', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/restaurante', lang: 'es', lemma: 'restaurante', gloss: 'restaurant', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/tienda', lang: 'es', lemma: 'tienda', gloss: 'shop', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/parque', lang: 'es', lemma: 'parque', gloss: 'park', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/calle', lang: 'es', lemma: 'calle', gloss: 'street', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/playa', lang: 'es', lemma: 'playa', gloss: 'beach', glossPlural: 'beaches', tags: ['place'], es: { gender: 'f' } },
  { id: 'es/noun/país', lang: 'es', lemma: 'país', gloss: 'country', glossPlural: 'countries', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/pueblo', lang: 'es', lemma: 'pueblo', gloss: 'town', tags: ['place'], es: { gender: 'm' } },
  { id: 'es/noun/mercado', lang: 'es', lemma: 'mercado', gloss: 'market', tags: ['place'], es: { gender: 'm' } },
  // everyday objects
  { id: 'es/noun/mesa', lang: 'es', lemma: 'mesa', gloss: 'table', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/silla', lang: 'es', lemma: 'silla', gloss: 'chair', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/puerta', lang: 'es', lemma: 'puerta', gloss: 'door', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/ventana', lang: 'es', lemma: 'ventana', gloss: 'window', tags: ['object'], es: { gender: 'f' } },
  { id: 'es/noun/coche', lang: 'es', lemma: 'coche', gloss: 'car', tags: ['vehicle'], es: { gender: 'm' } },
  { id: 'es/noun/teléfono', lang: 'es', lemma: 'teléfono', gloss: 'phone', tags: ['object'], es: { gender: 'm' } },
  { id: 'es/noun/ordenador', lang: 'es', lemma: 'ordenador', gloss: 'computer', tags: ['object'], es: { gender: 'm' } },
  { id: 'es/noun/ropa', lang: 'es', lemma: 'ropa', gloss: 'clothing', glossPlural: 'clothes', tags: ['clothing'], es: { gender: 'f' } },
  { id: 'es/noun/zapato', lang: 'es', lemma: 'zapato', gloss: 'shoe', tags: ['clothing'], es: { gender: 'm' } },
  { id: 'es/noun/bolso', lang: 'es', lemma: 'bolso', gloss: 'bag', tags: ['object'], es: { gender: 'm' } },
  // time & abstract
  { id: 'es/noun/día', lang: 'es', lemma: 'día', gloss: 'day', tags: ['time'], es: { gender: 'm' } },
  { id: 'es/noun/noche', lang: 'es', lemma: 'noche', gloss: 'night', tags: ['time'], es: { gender: 'f' } },
  { id: 'es/noun/semana', lang: 'es', lemma: 'semana', gloss: 'week', tags: ['time'], es: { gender: 'f' } },
  { id: 'es/noun/año', lang: 'es', lemma: 'año', gloss: 'year', tags: ['time'], es: { gender: 'm' } },
  { id: 'es/noun/hora', lang: 'es', lemma: 'hora', gloss: 'hour', tags: ['time'], es: { gender: 'f' } },
  { id: 'es/noun/nombre', lang: 'es', lemma: 'nombre', gloss: 'name', tags: ['abstract'], es: { gender: 'm' } },
  { id: 'es/noun/idioma', lang: 'es', lemma: 'idioma', gloss: 'language', tags: ['abstract'], es: { gender: 'm' } },
]

export const ES_NOUN_BY_ID = new Map(ES_NOUNS.map((n) => [n.id, n]))
