import type { VerbEntry } from '../../types'

// Starter lexicon (M2). Grows unit-by-unit; ids are append-only.
export const ES_VERBS: VerbEntry[] = [
  {
    id: 'es/verb/ser',
    lang: 'es',
    lemma: 'ser',
    gloss: 'to be (identity)',
    gloss3sg: 'is',
    tags: ['intransitive'],
    es: {
      class: 'er',
      irregular: {
        pres: { '1sg': 'soy', '2sg': 'eres', '3sg': 'es', '1pl': 'somos', '2pl': 'sois', '3pl': 'son' },
        pret: { '1sg': 'fui', '2sg': 'fuiste', '3sg': 'fue', '1pl': 'fuimos', '2pl': 'fuisteis', '3pl': 'fueron' },
      },
    },
  },
  {
    id: 'es/verb/estar',
    lang: 'es',
    lemma: 'estar',
    gloss: 'to be (state/place)',
    gloss3sg: 'is',
    tags: ['intransitive'],
    es: {
      class: 'ar',
      irregular: {
        pres: { '1sg': 'estoy', '2sg': 'estás', '3sg': 'está', '2pl': 'estáis', '3pl': 'están' },
        pret: { '1sg': 'estuve', '2sg': 'estuviste', '3sg': 'estuvo', '1pl': 'estuvimos', '2pl': 'estuvisteis', '3pl': 'estuvieron' },
      },
    },
  },
  {
    id: 'es/verb/tener',
    lang: 'es',
    lemma: 'tener',
    gloss: 'to have',
    gloss3sg: 'has',
    tags: ['transitive'],
    objectTags: ['object', 'animal', 'family'],
    es: {
      class: 'er',
      stemChange: 'e>ie',
      yoIrregular: 'tengo',
      irregular: {
        pret: { '1sg': 'tuve', '2sg': 'tuviste', '3sg': 'tuvo', '1pl': 'tuvimos', '2pl': 'tuvisteis', '3pl': 'tuvieron' },
      },
    },
  },
  {
    id: 'es/verb/hablar',
    lang: 'es',
    lemma: 'hablar',
    gloss: 'to speak',
    gloss3sg: 'speaks',
    tags: ['daily-routine'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/comer',
    lang: 'es',
    lemma: 'comer',
    gloss: 'to eat',
    gloss3sg: 'eats',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/vivir',
    lang: 'es',
    lemma: 'vivir',
    gloss: 'to live',
    gloss3sg: 'lives',
    tags: ['intransitive', 'daily-routine'],
    es: { class: 'ir' },
  },
  {
    id: 'es/verb/beber',
    lang: 'es',
    lemma: 'beber',
    gloss: 'to drink',
    gloss3sg: 'drinks',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['drink'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/trabajar',
    lang: 'es',
    lemma: 'trabajar',
    gloss: 'to work',
    gloss3sg: 'works',
    tags: ['intransitive', 'daily-routine'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/querer',
    lang: 'es',
    lemma: 'querer',
    gloss: 'to want',
    gloss3sg: 'wants',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    es: { class: 'er', stemChange: 'e>ie' },
  },
  {
    id: 'es/verb/poder',
    lang: 'es',
    lemma: 'poder',
    gloss: 'to be able to',
    gloss3sg: 'can',
    tags: ['intransitive'],
    es: { class: 'er', stemChange: 'o>ue' },
  },
  {
    id: 'es/verb/pedir',
    lang: 'es',
    lemma: 'pedir',
    gloss: 'to order / ask for',
    gloss3sg: 'orders',
    tags: ['transitive'],
    objectTags: ['food', 'drink'],
    es: { class: 'ir', stemChange: 'e>i' },
  },
  {
    id: 'es/verb/hacer',
    lang: 'es',
    lemma: 'hacer',
    gloss: 'to do / make',
    gloss3sg: 'does',
    tags: ['transitive'],
    objectTags: ['object'],
    es: {
      class: 'er',
      yoIrregular: 'hago',
      irregular: {
        pret: { '1sg': 'hice', '2sg': 'hiciste', '3sg': 'hizo', '1pl': 'hicimos', '2pl': 'hicisteis', '3pl': 'hicieron' },
      },
    },
  },
  {
    id: 'es/verb/ir',
    lang: 'es',
    lemma: 'ir',
    gloss: 'to go',
    gloss3sg: 'goes',
    tags: ['motion', 'intransitive'],
    es: {
      class: 'ir',
      irregular: {
        pres: { '1sg': 'voy', '2sg': 'vas', '3sg': 'va', '1pl': 'vamos', '2pl': 'vais', '3pl': 'van' },
        pret: { '1sg': 'fui', '2sg': 'fuiste', '3sg': 'fue', '1pl': 'fuimos', '2pl': 'fuisteis', '3pl': 'fueron' },
      },
    },
  },
]

export const ES_VERB_BY_ID = new Map(ES_VERBS.map((v) => [v.id, v]))
