import type { VerbEntry } from '../../types'

// Starter lexicon (M2). Grows unit-by-unit; ids are append-only.
export const ES_VERBS: VerbEntry[] = [
  {
    id: 'es/verb/ser',
    lang: 'es',
    lemma: 'ser',
    gloss: 'to be (identity)',
    gloss3sg: 'is',
    glossIt: 'essere',
    tags: ['intransitive'],
    es: {
      class: 'er',
      irregular: {
        pres: { '1sg': 'soy', '2sg': 'eres', '3sg': 'es', '1pl': 'somos', '2pl': 'sois', '3pl': 'son' },
        pret: { '1sg': 'fui', '2sg': 'fuiste', '3sg': 'fue', '1pl': 'fuimos', '2pl': 'fuisteis', '3pl': 'fueron' },
      },
    },
  },
  {
    id: 'es/verb/estar',
    lang: 'es',
    lemma: 'estar',
    gloss: 'to be (state/place)',
    gloss3sg: 'is',
    glossIt: 'stare',
    tags: ['intransitive'],
    es: {
      class: 'ar',
      irregular: {
        pres: { '1sg': 'estoy', '2sg': 'estás', '3sg': 'está', '2pl': 'estáis', '3pl': 'están' },
        pret: { '1sg': 'estuve', '2sg': 'estuviste', '3sg': 'estuvo', '1pl': 'estuvimos', '2pl': 'estuvisteis', '3pl': 'estuvieron' },
      },
    },
  },
  {
    id: 'es/verb/tener',
    lang: 'es',
    lemma: 'tener',
    gloss: 'to have',
    gloss3sg: 'has',
    glossIt: 'avere',
    tags: ['transitive'],
    objectTags: ['object', 'animal', 'family'],
    es: {
      class: 'er',
      stemChange: 'e>ie',
      yoIrregular: 'tengo',
      irregular: {
        pret: { '1sg': 'tuve', '2sg': 'tuviste', '3sg': 'tuvo', '1pl': 'tuvimos', '2pl': 'tuvisteis', '3pl': 'tuvieron' },
      },
    },
  },
  {
    id: 'es/verb/hablar',
    lang: 'es',
    lemma: 'hablar',
    gloss: 'to speak',
    gloss3sg: 'speaks',
    glossIt: 'parlare',
    tags: ['daily-routine'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/comer',
    lang: 'es',
    lemma: 'comer',
    gloss: 'to eat',
    gloss3sg: 'eats',
    glossIt: 'mangiare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/vivir',
    lang: 'es',
    lemma: 'vivir',
    gloss: 'to live',
    gloss3sg: 'lives',
    glossIt: 'vivere',
    tags: ['intransitive', 'daily-routine'],
    es: { class: 'ir' },
  },
  {
    id: 'es/verb/beber',
    lang: 'es',
    lemma: 'beber',
    gloss: 'to drink',
    gloss3sg: 'drinks',
    glossIt: 'bere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['drink'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/trabajar',
    lang: 'es',
    lemma: 'trabajar',
    gloss: 'to work',
    gloss3sg: 'works',
    glossIt: 'lavorare',
    tags: ['intransitive', 'daily-routine'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/querer',
    lang: 'es',
    lemma: 'querer',
    gloss: 'to want',
    gloss3sg: 'wants',
    glossIt: 'volere',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    es: { class: 'er', stemChange: 'e>ie' },
  },
  {
    id: 'es/verb/poder',
    lang: 'es',
    lemma: 'poder',
    gloss: 'to be able to',
    gloss3sg: 'can',
    glossIt: 'potere',
    tags: ['intransitive'],
    es: { class: 'er', stemChange: 'o>ue' },
  },
  {
    id: 'es/verb/pedir',
    lang: 'es',
    lemma: 'pedir',
    gloss: 'to order / ask for',
    gloss3sg: 'orders',
    glossIt: 'ordinare',
    tags: ['transitive'],
    objectTags: ['food', 'drink'],
    es: { class: 'ir', stemChange: 'e>i' },
  },
  {
    id: 'es/verb/hacer',
    lang: 'es',
    lemma: 'hacer',
    gloss: 'to do / make',
    gloss3sg: 'does',
    glossIt: 'fare',
    tags: ['transitive'],
    objectTags: ['object'],
    es: {
      class: 'er',
      yoIrregular: 'hago',
      irregular: {
        pret: { '1sg': 'hice', '2sg': 'hiciste', '3sg': 'hizo', '1pl': 'hicimos', '2pl': 'hicisteis', '3pl': 'hicieron' },
      },
    },
  },
  {
    id: 'es/verb/ir',
    lang: 'es',
    lemma: 'ir',
    gloss: 'to go',
    gloss3sg: 'goes',
    glossIt: 'andare',
    tags: ['motion', 'intransitive'],
    es: {
      class: 'ir',
      irregular: {
        pres: { '1sg': 'voy', '2sg': 'vas', '3sg': 'va', '1pl': 'vamos', '2pl': 'vais', '3pl': 'van' },
        pret: { '1sg': 'fui', '2sg': 'fuiste', '3sg': 'fue', '1pl': 'fuimos', '2pl': 'fuisteis', '3pl': 'fueron' },
      },
    },
  },
  {
    id: 'es/verb/estudiar',
    lang: 'es',
    lemma: 'estudiar',
    gloss: 'to study',
    gloss3sg: 'studies',
    glossIt: 'studiare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['abstract'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/escuchar',
    lang: 'es',
    lemma: 'escuchar',
    gloss: 'to listen (to)',
    gloss3sg: 'listens',
    glossIt: 'ascoltare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['human', 'object'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/mirar',
    lang: 'es',
    lemma: 'mirar',
    gloss: 'to look at / watch',
    gloss3sg: 'looks at',
    glossIt: 'guardare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object', 'human'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/comprar',
    lang: 'es',
    lemma: 'comprar',
    gloss: 'to buy',
    gloss3sg: 'buys',
    glossIt: 'comprare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food', 'drink', 'object', 'clothing'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/cocinar',
    lang: 'es',
    lemma: 'cocinar',
    gloss: 'to cook',
    gloss3sg: 'cooks',
    glossIt: 'cucinare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/caminar',
    lang: 'es',
    lemma: 'caminar',
    gloss: 'to walk',
    gloss3sg: 'walks',
    glossIt: 'camminare',
    tags: ['motion', 'intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/bailar',
    lang: 'es',
    lemma: 'bailar',
    gloss: 'to dance',
    gloss3sg: 'dances',
    glossIt: 'ballare',
    tags: ['intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/cantar',
    lang: 'es',
    lemma: 'cantar',
    gloss: 'to sing',
    gloss3sg: 'sings',
    glossIt: 'cantare',
    tags: ['intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/necesitar',
    lang: 'es',
    lemma: 'necesitar',
    gloss: 'to need',
    gloss3sg: 'needs',
    glossIt: 'avere bisogno di',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/tomar',
    lang: 'es',
    lemma: 'tomar',
    gloss: 'to take / drink',
    gloss3sg: 'takes',
    glossIt: 'prendere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['drink', 'food'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/leer',
    lang: 'es',
    lemma: 'leer',
    gloss: 'to read',
    gloss3sg: 'reads',
    glossIt: 'leggere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/escribir',
    lang: 'es',
    lemma: 'escribir',
    gloss: 'to write',
    gloss3sg: 'writes',
    glossIt: 'scrivere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object', 'abstract'],
    es: { class: 'ir' },
  },
  {
    id: 'es/verb/abrir',
    lang: 'es',
    lemma: 'abrir',
    gloss: 'to open',
    gloss3sg: 'opens',
    glossIt: 'aprire',
    tags: ['transitive'],
    objectTags: ['object'],
    es: { class: 'ir' },
  },
  {
    id: 'es/verb/aprender',
    lang: 'es',
    lemma: 'aprender',
    gloss: 'to learn',
    gloss3sg: 'learns',
    glossIt: 'imparare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['abstract'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/correr',
    lang: 'es',
    lemma: 'correr',
    gloss: 'to run',
    gloss3sg: 'runs',
    glossIt: 'correre',
    tags: ['motion', 'intransitive'],
    es: { class: 'er' },
  },
]

export const ES_VERB_BY_ID = new Map(ES_VERBS.map((v) => [v.id, v]))
