import type { VerbEntry } from '../../types'

// Starter lexicon (M2). Grows unit-by-unit; ids are append-only.
export const ES_VERBS: VerbEntry[] = [
  {
    id: 'es/verb/ser',
    lang: 'es',
    lemma: 'ser',
    gloss: 'to be (identity)',
    gloss3sg: 'is',
    glossIt: 'essere',
    tags: ['intransitive'],
    es: {
      class: 'er',
      irregular: {
        pres: { '1sg': 'soy', '2sg': 'eres', '3sg': 'es', '1pl': 'somos', '2pl': 'sois', '3pl': 'son' },
        pret: { '1sg': 'fui', '2sg': 'fuiste', '3sg': 'fue', '1pl': 'fuimos', '2pl': 'fuisteis', '3pl': 'fueron' },
        impf: { '1sg': 'era', '2sg': 'eras', '3sg': 'era', '1pl': 'éramos', '2pl': 'erais', '3pl': 'eran' },
      },
    },
  },
  {
    id: 'es/verb/estar',
    lang: 'es',
    lemma: 'estar',
    gloss: 'to be (state/place)',
    gloss3sg: 'is',
    glossIt: 'stare',
    tags: ['intransitive'],
    es: {
      class: 'ar',
      irregular: {
        pres: { '1sg': 'estoy', '2sg': 'estás', '3sg': 'está', '2pl': 'estáis', '3pl': 'están' },
        pret: { '1sg': 'estuve', '2sg': 'estuviste', '3sg': 'estuvo', '1pl': 'estuvimos', '2pl': 'estuvisteis', '3pl': 'estuvieron' },
      },
    },
  },
  {
    id: 'es/verb/tener',
    lang: 'es',
    lemma: 'tener',
    gloss: 'to have',
    gloss3sg: 'has',
    glossIt: 'avere',
    tags: ['transitive'],
    objectTags: ['object', 'animal', 'family'],
    es: {
      class: 'er',
      stemChange: 'e>ie',
      yoIrregular: 'tengo',
      irregular: {
        pret: { '1sg': 'tuve', '2sg': 'tuviste', '3sg': 'tuvo', '1pl': 'tuvimos', '2pl': 'tuvisteis', '3pl': 'tuvieron' },
      },
    },
  },
  {
    id: 'es/verb/hablar',
    lang: 'es',
    lemma: 'hablar',
    gloss: 'to speak',
    gloss3sg: 'speaks',
    glossIt: 'parlare',
    tags: ['daily-routine'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/comer',
    lang: 'es',
    lemma: 'comer',
    gloss: 'to eat',
    gloss3sg: 'eats',
    glossIt: 'mangiare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/vivir',
    lang: 'es',
    lemma: 'vivir',
    gloss: 'to live',
    gloss3sg: 'lives',
    glossIt: 'vivere',
    tags: ['intransitive', 'daily-routine'],
    es: { class: 'ir' },
  },
  {
    id: 'es/verb/beber',
    lang: 'es',
    lemma: 'beber',
    gloss: 'to drink',
    gloss3sg: 'drinks',
    glossIt: 'bere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['drink'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/trabajar',
    lang: 'es',
    lemma: 'trabajar',
    gloss: 'to work',
    gloss3sg: 'works',
    glossIt: 'lavorare',
    tags: ['intransitive', 'daily-routine'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/querer',
    lang: 'es',
    lemma: 'querer',
    gloss: 'to want',
    gloss3sg: 'wants',
    glossIt: 'volere',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    es: { class: 'er', stemChange: 'e>ie' },
  },
  {
    id: 'es/verb/poder',
    lang: 'es',
    lemma: 'poder',
    gloss: 'to be able to',
    gloss3sg: 'can',
    glossIt: 'potere',
    tags: ['intransitive'],
    es: { class: 'er', stemChange: 'o>ue' },
  },
  {
    id: 'es/verb/pedir',
    lang: 'es',
    lemma: 'pedir',
    gloss: 'to order / ask for',
    gloss3sg: 'orders',
    glossIt: 'ordinare',
    tags: ['transitive'],
    objectTags: ['food', 'drink'],
    es: { class: 'ir', stemChange: 'e>i' },
  },
  {
    id: 'es/verb/hacer',
    lang: 'es',
    lemma: 'hacer',
    gloss: 'to do / make',
    gloss3sg: 'does',
    glossIt: 'fare',
    tags: ['transitive'],
    objectTags: ['object'],
    es: {
      participle: 'hecho',
      class: 'er',
      yoIrregular: 'hago',
      irregular: {
        pret: { '1sg': 'hice', '2sg': 'hiciste', '3sg': 'hizo', '1pl': 'hicimos', '2pl': 'hicisteis', '3pl': 'hicieron' },
      },
    },
  },
  {
    id: 'es/verb/ir',
    lang: 'es',
    lemma: 'ir',
    gloss: 'to go',
    gloss3sg: 'goes',
    glossIt: 'andare',
    tags: ['motion', 'intransitive'],
    es: {
      class: 'ir',
      irregular: {
        pres: { '1sg': 'voy', '2sg': 'vas', '3sg': 'va', '1pl': 'vamos', '2pl': 'vais', '3pl': 'van' },
        pret: { '1sg': 'fui', '2sg': 'fuiste', '3sg': 'fue', '1pl': 'fuimos', '2pl': 'fuisteis', '3pl': 'fueron' },
        impf: { '1sg': 'iba', '2sg': 'ibas', '3sg': 'iba', '1pl': 'íbamos', '2pl': 'ibais', '3pl': 'iban' },
      },
    },
  },
  {
    id: 'es/verb/estudiar',
    lang: 'es',
    lemma: 'estudiar',
    gloss: 'to study',
    gloss3sg: 'studies',
    glossIt: 'studiare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['abstract'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/escuchar',
    lang: 'es',
    lemma: 'escuchar',
    gloss: 'to listen (to)',
    gloss3sg: 'listens',
    glossIt: 'ascoltare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['human', 'object'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/mirar',
    lang: 'es',
    lemma: 'mirar',
    gloss: 'to look at / watch',
    gloss3sg: 'looks at',
    glossIt: 'guardare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object', 'human'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/comprar',
    lang: 'es',
    lemma: 'comprar',
    gloss: 'to buy',
    gloss3sg: 'buys',
    glossIt: 'comprare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food', 'drink', 'object', 'clothing'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/cocinar',
    lang: 'es',
    lemma: 'cocinar',
    gloss: 'to cook',
    gloss3sg: 'cooks',
    glossIt: 'cucinare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['food'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/caminar',
    lang: 'es',
    lemma: 'caminar',
    gloss: 'to walk',
    gloss3sg: 'walks',
    glossIt: 'camminare',
    tags: ['motion', 'intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/bailar',
    lang: 'es',
    lemma: 'bailar',
    gloss: 'to dance',
    gloss3sg: 'dances',
    glossIt: 'ballare',
    tags: ['intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/cantar',
    lang: 'es',
    lemma: 'cantar',
    gloss: 'to sing',
    gloss3sg: 'sings',
    glossIt: 'cantare',
    tags: ['intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/necesitar',
    lang: 'es',
    lemma: 'necesitar',
    gloss: 'to need',
    gloss3sg: 'needs',
    glossIt: 'avere bisogno di',
    tags: ['transitive'],
    objectTags: ['object', 'food', 'drink'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/tomar',
    lang: 'es',
    lemma: 'tomar',
    gloss: 'to take / drink',
    gloss3sg: 'takes',
    glossIt: 'prendere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['drink', 'food'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/leer',
    lang: 'es',
    lemma: 'leer',
    gloss: 'to read',
    gloss3sg: 'reads',
    glossIt: 'leggere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/escribir',
    lang: 'es',
    lemma: 'escribir',
    gloss: 'to write',
    gloss3sg: 'writes',
    glossIt: 'scrivere',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['object', 'abstract'],
    es: { participle: 'escrito', class: 'ir' },
  },
  {
    id: 'es/verb/abrir',
    lang: 'es',
    lemma: 'abrir',
    gloss: 'to open',
    gloss3sg: 'opens',
    glossIt: 'aprire',
    tags: ['transitive'],
    objectTags: ['object'],
    es: { participle: 'abierto', class: 'ir' },
  },
  {
    id: 'es/verb/aprender',
    lang: 'es',
    lemma: 'aprender',
    gloss: 'to learn',
    gloss3sg: 'learns',
    glossIt: 'imparare',
    tags: ['transitive', 'daily-routine'],
    objectTags: ['abstract'],
    es: { class: 'er' },
  },
  {
    id: 'es/verb/correr',
    lang: 'es',
    lemma: 'correr',
    gloss: 'to run',
    gloss3sg: 'runs',
    glossIt: 'correre',
    tags: ['motion', 'intransitive'],
    es: { class: 'er' },
  },
  // ---- Units 3-6 ----
  {
    id: 'es/verb/venir',
    lang: 'es',
    lemma: 'venir',
    gloss: 'to come',
    gloss3sg: 'comes',
    glossIt: 'venire',
    tags: ['motion', 'intransitive'],
    es: {
      class: 'ir',
      stemChange: 'e>ie',
      yoIrregular: 'vengo',
      irregular: {
        pret: { '1sg': 'vine', '2sg': 'viniste', '3sg': 'vino', '1pl': 'vinimos', '2pl': 'vinisteis', '3pl': 'vinieron' },
      },
    },
  },
  {
    id: 'es/verb/salir',
    lang: 'es',
    lemma: 'salir',
    gloss: 'to go out / leave',
    gloss3sg: 'goes out',
    glossIt: 'uscire',
    tags: ['motion', 'intransitive', 'daily-routine'],
    es: { class: 'ir', yoIrregular: 'salgo' },
  },
  {
    id: 'es/verb/poner',
    lang: 'es',
    lemma: 'poner',
    gloss: 'to put',
    gloss3sg: 'puts',
    glossIt: 'mettere',
    tags: ['transitive'],
    objectTags: ['object'],
    es: {
      participle: 'puesto',
      class: 'er',
      yoIrregular: 'pongo',
      irregular: {
        pret: { '1sg': 'puse', '2sg': 'pusiste', '3sg': 'puso', '1pl': 'pusimos', '2pl': 'pusisteis', '3pl': 'pusieron' },
      },
    },
  },
  {
    id: 'es/verb/decir',
    lang: 'es',
    lemma: 'decir',
    gloss: 'to say / tell',
    gloss3sg: 'says',
    glossIt: 'dire',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: {
      participle: 'dicho',
      class: 'ir',
      stemChange: 'e>i',
      yoIrregular: 'digo',
      irregular: {
        pret: { '1sg': 'dije', '2sg': 'dijiste', '3sg': 'dijo', '1pl': 'dijimos', '2pl': 'dijisteis', '3pl': 'dijeron' },
      },
    },
  },
  {
    id: 'es/verb/ver',
    lang: 'es',
    lemma: 'ver',
    gloss: 'to see',
    gloss3sg: 'sees',
    glossIt: 'vedere',
    tags: ['transitive'],
    objectTags: ['human', 'object', 'place'],
    es: {
      participle: 'visto',
      class: 'er',
      yoIrregular: 'veo',
      irregular: {
        pres: { '2pl': 'veis' },
        pret: { '1sg': 'vi', '2sg': 'viste', '3sg': 'vio', '1pl': 'vimos', '2pl': 'visteis', '3pl': 'vieron' },
        impf: { '1sg': 'veía', '2sg': 'veías', '3sg': 'veía', '1pl': 'veíamos', '2pl': 'veíais', '3pl': 'veían' },
      },
    },
  },
  {
    id: 'es/verb/saber',
    lang: 'es',
    lemma: 'saber',
    gloss: 'to know (facts)',
    gloss3sg: 'knows',
    glossIt: 'sapere',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: {
      class: 'er',
      yoIrregular: 'sé',
      irregular: {
        pret: { '1sg': 'supe', '2sg': 'supiste', '3sg': 'supo', '1pl': 'supimos', '2pl': 'supisteis', '3pl': 'supieron' },
      },
    },
  },
  {
    id: 'es/verb/conocer',
    lang: 'es',
    lemma: 'conocer',
    gloss: 'to know (people/places)',
    gloss3sg: 'knows',
    glossIt: 'conoscere',
    tags: ['transitive'],
    objectTags: ['human', 'place'],
    es: { class: 'er', yoIrregular: 'conozco' },
  },
  {
    id: 'es/verb/dar',
    lang: 'es',
    lemma: 'dar',
    gloss: 'to give',
    gloss3sg: 'gives',
    glossIt: 'dare',
    tags: ['transitive'],
    objectTags: ['object'],
    es: {
      class: 'ar',
      yoIrregular: 'doy',
      irregular: {
        pres: { '2pl': 'dais' },
        pret: { '1sg': 'di', '2sg': 'diste', '3sg': 'dio', '1pl': 'dimos', '2pl': 'disteis', '3pl': 'dieron' },
      },
    },
  },
  {
    id: 'es/verb/dormir',
    lang: 'es',
    lemma: 'dormir',
    gloss: 'to sleep',
    gloss3sg: 'sleeps',
    glossIt: 'dormire',
    tags: ['intransitive', 'daily-routine'],
    es: { class: 'ir', stemChange: 'o>ue' },
  },
  {
    id: 'es/verb/volver',
    lang: 'es',
    lemma: 'volver',
    gloss: 'to return / go back',
    gloss3sg: 'returns',
    glossIt: 'tornare',
    tags: ['motion', 'intransitive'],
    es: { participle: 'vuelto', class: 'er', stemChange: 'o>ue' },
  },
  {
    id: 'es/verb/empezar',
    lang: 'es',
    lemma: 'empezar',
    gloss: 'to start',
    gloss3sg: 'starts',
    glossIt: 'cominciare',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: { class: 'ar', stemChange: 'e>ie' },
  },
  {
    id: 'es/verb/entender',
    lang: 'es',
    lemma: 'entender',
    gloss: 'to understand',
    gloss3sg: 'understands',
    glossIt: 'comprendere',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: { class: 'er', stemChange: 'e>ie' },
  },
  {
    id: 'es/verb/pensar',
    lang: 'es',
    lemma: 'pensar',
    gloss: 'to think',
    gloss3sg: 'thinks',
    glossIt: 'pensare',
    tags: ['intransitive'],
    es: { class: 'ar', stemChange: 'e>ie' },
  },
  {
    id: 'es/verb/jugar',
    lang: 'es',
    lemma: 'jugar',
    gloss: 'to play (a game)',
    gloss3sg: 'plays',
    glossIt: 'giocare',
    tags: ['intransitive', 'daily-routine'],
    es: { class: 'ar', stemChange: 'u>ue' },
  },
  {
    id: 'es/verb/buscar',
    lang: 'es',
    lemma: 'buscar',
    gloss: 'to look for',
    gloss3sg: 'looks for',
    glossIt: 'cercare',
    tags: ['transitive'],
    objectTags: ['object', 'human', 'place'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/pagar',
    lang: 'es',
    lemma: 'pagar',
    gloss: 'to pay',
    gloss3sg: 'pays',
    glossIt: 'pagare',
    tags: ['transitive'],
    objectTags: ['object'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/llegar',
    lang: 'es',
    lemma: 'llegar',
    gloss: 'to arrive',
    gloss3sg: 'arrives',
    glossIt: 'arrivare',
    tags: ['motion', 'intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/llamar',
    lang: 'es',
    lemma: 'llamar',
    gloss: 'to call',
    gloss3sg: 'calls',
    glossIt: 'chiamare',
    tags: ['transitive'],
    objectTags: ['human'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/llevar',
    lang: 'es',
    lemma: 'llevar',
    gloss: 'to wear / carry',
    gloss3sg: 'wears',
    glossIt: 'portare',
    tags: ['transitive'],
    objectTags: ['clothing', 'object'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/gustar',
    lang: 'es',
    lemma: 'gustar',
    gloss: 'to be pleasing (like)',
    gloss3sg: 'pleases',
    glossIt: 'piacere',
    tags: ['intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/encantar',
    lang: 'es',
    lemma: 'encantar',
    gloss: 'to delight (love)',
    gloss3sg: 'delights',
    glossIt: 'piacere moltissimo',
    tags: ['intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/levantar',
    lang: 'es',
    lemma: 'levantar',
    gloss: 'to get up',
    gloss3sg: 'gets up',
    glossIt: 'alzarsi',
    tags: ['daily-routine'],
    es: { class: 'ar', reflexive: true },
  },
  {
    id: 'es/verb/duchar',
    lang: 'es',
    lemma: 'duchar',
    gloss: 'to shower',
    gloss3sg: 'showers',
    glossIt: 'farsi la doccia',
    tags: ['daily-routine'],
    es: { class: 'ar', reflexive: true },
  },
  {
    id: 'es/verb/acostar',
    lang: 'es',
    lemma: 'acostar',
    gloss: 'to go to bed',
    gloss3sg: 'goes to bed',
    glossIt: 'andare a letto',
    tags: ['daily-routine'],
    es: { class: 'ar', stemChange: 'o>ue', reflexive: true },
  },
  {
    id: 'es/verb/despertar',
    lang: 'es',
    lemma: 'despertar',
    gloss: 'to wake up',
    gloss3sg: 'wakes up',
    glossIt: 'svegliarsi',
    tags: ['daily-routine'],
    es: { class: 'ar', stemChange: 'e>ie', reflexive: true },
  },
  {
    id: 'es/verb/desayunar',
    lang: 'es',
    lemma: 'desayunar',
    gloss: 'to have breakfast',
    gloss3sg: 'has breakfast',
    glossIt: 'fare colazione',
    tags: ['daily-routine'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/cenar',
    lang: 'es',
    lemma: 'cenar',
    gloss: 'to have dinner',
    gloss3sg: 'has dinner',
    glossIt: 'cenare',
    tags: ['daily-routine'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/terminar',
    lang: 'es',
    lemma: 'terminar',
    gloss: 'to finish',
    gloss3sg: 'finishes',
    glossIt: 'terminare',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/viajar',
    lang: 'es',
    lemma: 'viajar',
    gloss: 'to travel',
    gloss3sg: 'travels',
    glossIt: 'viaggiare',
    tags: ['motion', 'intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/visitar',
    lang: 'es',
    lemma: 'visitar',
    gloss: 'to visit',
    gloss3sg: 'visits',
    glossIt: 'visitare',
    tags: ['transitive'],
    objectTags: ['human', 'place'],
    es: { class: 'ar' },
  },
  // ---- Lexicon expansion (units 3-7) ----
  {
    id: 'es/verb/ayudar',
    lang: 'es',
    lemma: 'ayudar',
    gloss: 'to help',
    gloss3sg: 'helps',
    glossIt: 'aiutare',
    tags: ['transitive'],
    objectTags: ['human', 'family'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/amar',
    lang: 'es',
    lemma: 'amar',
    gloss: 'to love',
    gloss3sg: 'loves',
    glossIt: 'amare',
    tags: ['transitive'],
    objectTags: ['human', 'family'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/esperar',
    lang: 'es',
    lemma: 'esperar',
    gloss: 'to wait (for) / hope',
    gloss3sg: 'waits',
    glossIt: 'aspettare',
    tags: ['transitive'],
    objectTags: ['human', 'vehicle'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/preguntar',
    lang: 'es',
    lemma: 'preguntar',
    gloss: 'to ask',
    gloss3sg: 'asks',
    glossIt: 'domandare',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/contestar',
    lang: 'es',
    lemma: 'contestar',
    gloss: 'to answer',
    gloss3sg: 'answers',
    glossIt: 'rispondere',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/enseñar',
    lang: 'es',
    lemma: 'enseñar',
    gloss: 'to teach',
    gloss3sg: 'teaches',
    glossIt: 'insegnare',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/explicar',
    lang: 'es',
    lemma: 'explicar',
    gloss: 'to explain',
    gloss3sg: 'explains',
    glossIt: 'spiegare',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/usar',
    lang: 'es',
    lemma: 'usar',
    gloss: 'to use',
    gloss3sg: 'uses',
    glossIt: 'usare',
    tags: ['transitive'],
    objectTags: ['object'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/ganar',
    lang: 'es',
    lemma: 'ganar',
    gloss: 'to win / earn',
    gloss3sg: 'wins',
    glossIt: 'vincere',
    tags: ['transitive'],
    objectTags: ['abstract', 'object'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/perder',
    lang: 'es',
    lemma: 'perder',
    gloss: 'to lose',
    gloss3sg: 'loses',
    glossIt: 'perdere',
    tags: ['transitive'],
    objectTags: ['object'],
    es: { class: 'er', stemChange: 'e>ie' },
  },
  {
    id: 'es/verb/encontrar',
    lang: 'es',
    lemma: 'encontrar',
    gloss: 'to find',
    gloss3sg: 'finds',
    glossIt: 'trovare',
    tags: ['transitive'],
    objectTags: ['object', 'human', 'place'],
    es: { class: 'ar', stemChange: 'o>ue' },
  },
  {
    id: 'es/verb/recordar',
    lang: 'es',
    lemma: 'recordar',
    gloss: 'to remember',
    gloss3sg: 'remembers',
    glossIt: 'ricordare',
    tags: ['transitive'],
    objectTags: ['abstract', 'human'],
    es: { class: 'ar', stemChange: 'o>ue' },
  },
  {
    id: 'es/verb/olvidar',
    lang: 'es',
    lemma: 'olvidar',
    gloss: 'to forget',
    gloss3sg: 'forgets',
    glossIt: 'dimenticare',
    tags: ['transitive'],
    objectTags: ['abstract', 'object'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/enviar',
    lang: 'es',
    lemma: 'enviar',
    gloss: 'to send',
    gloss3sg: 'sends',
    glossIt: 'inviare',
    tags: ['transitive'],
    objectTags: ['object', 'abstract'],
    es: {
      class: 'ar',
      irregular: {
        pres: { '1sg': 'envío', '2sg': 'envías', '3sg': 'envía', '3pl': 'envían' },
      },
    },
  },
  {
    id: 'es/verb/recibir',
    lang: 'es',
    lemma: 'recibir',
    gloss: 'to receive',
    gloss3sg: 'receives',
    glossIt: 'ricevere',
    tags: ['transitive'],
    objectTags: ['object', 'abstract'],
    es: { class: 'ir' },
  },
  {
    id: 'es/verb/subir',
    lang: 'es',
    lemma: 'subir',
    gloss: 'to go up',
    gloss3sg: 'goes up',
    glossIt: 'salire',
    tags: ['motion', 'intransitive'],
    es: { class: 'ir' },
  },
  {
    id: 'es/verb/bajar',
    lang: 'es',
    lemma: 'bajar',
    gloss: 'to go down',
    gloss3sg: 'goes down',
    glossIt: 'scendere',
    tags: ['motion', 'intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/entrar',
    lang: 'es',
    lemma: 'entrar',
    gloss: 'to enter',
    gloss3sg: 'enters',
    glossIt: 'entrare',
    tags: ['motion', 'intransitive'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/dejar',
    lang: 'es',
    lemma: 'dejar',
    gloss: 'to leave (behind)',
    gloss3sg: 'leaves',
    glossIt: 'lasciare',
    tags: ['transitive'],
    objectTags: ['object'],
    es: { class: 'ar' },
  },
  {
    id: 'es/verb/llover',
    lang: 'es',
    lemma: 'llover',
    gloss: 'to rain',
    gloss3sg: 'rains',
    glossIt: 'piovere',
    tags: ['intransitive'],
    es: { class: 'er', stemChange: 'o>ue' },
  },
  {
    id: 'es/verb/nevar',
    lang: 'es',
    lemma: 'nevar',
    gloss: 'to snow',
    gloss3sg: 'snows',
    glossIt: 'nevicare',
    tags: ['intransitive'],
    es: { class: 'ar', stemChange: 'e>ie' },
  },
  {
    id: 'es/verb/sentir',
    lang: 'es',
    lemma: 'sentir',
    gloss: 'to feel',
    gloss3sg: 'feels',
    glossIt: 'sentire',
    tags: ['transitive'],
    objectTags: ['abstract'],
    es: { class: 'ir', stemChange: 'e>ie' },
  },
  {
    id: 'es/verb/morir',
    lang: 'es',
    lemma: 'morir',
    gloss: 'to die',
    gloss3sg: 'dies',
    glossIt: 'morire',
    tags: ['intransitive'],
    es: { participle: 'muerto', class: 'ir', stemChange: 'o>ue' },
  },
  {
    id: 'es/verb/nacer',
    lang: 'es',
    lemma: 'nacer',
    gloss: 'to be born',
    gloss3sg: 'is born',
    glossIt: 'nascere',
    tags: ['intransitive'],
    es: { class: 'er', yoIrregular: 'nazco' },
  },
  {
    id: 'es/verb/preferir',
    lang: 'es',
    lemma: 'preferir',
    gloss: 'to prefer',
    gloss3sg: 'prefers',
    glossIt: 'preferire',
    tags: ['transitive'],
    objectTags: ['food', 'drink', 'object'],
    es: { class: 'ir', stemChange: 'e>ie' },
  },
]

export const ES_VERB_BY_ID = new Map(ES_VERBS.map((v) => [v.id, v]))
