import type { VocabPack } from '../types'
import { DE_NOUNS } from './morphology/nouns'
import { DE_VERBS } from './morphology/verbs'
import type { VocabLexeme } from '../../engine/vocab'

export const DE_PACKS: VocabPack[] = [
  {
    id: 'de-pack-basics',
    lang: 'de',
    unitId: 'de-u1',
    title: { en: 'First words', it: 'Prime parole' },
    lexemeIds: [
      'de/noun/mann',
      'de/noun/frau',
      'de/noun/kind',
      'de/noun/haus',
      'de/noun/buch',
      'de/noun/wasser',
      'de/noun/kaffee',
      'de/noun/brot',
      'de/verb/machen',
      'de/verb/wohnen',
      'de/verb/kommen',
      'de/verb/trinken',
    ],
  },
  {
    id: 'de-pack-family',
    lang: 'de',
    unitId: 'de-u1',
    title: { en: 'Family', it: 'La famiglia' },
    lexemeIds: [
      'de/noun/familie',
      'de/noun/vater',
      'de/noun/mutter',
      'de/noun/bruder',
      'de/noun/schwester',
      'de/noun/sohn',
      'de/noun/tochter',
      'de/noun/junge',
      'de/noun/mädchen',
      'de/noun/freund',
    ],
  },
  {
    id: 'de-pack-food',
    lang: 'de',
    unitId: 'de-u2',
    title: { en: 'Food & drink', it: 'Cibo e bevande' },
    lexemeIds: [
      'de/noun/milch',
      'de/noun/käse',
      'de/noun/ei',
      'de/noun/fleisch',
      'de/noun/reis',
      'de/noun/obst',
      'de/noun/bier',
      'de/noun/wein',
      'de/noun/tee',
      'de/noun/saft',
      'de/noun/apfel',
      'de/verb/essen',
    ],
  },
  {
    id: 'de-pack-town',
    lang: 'de',
    unitId: 'de-u2',
    title: { en: 'Around town', it: 'In città' },
    lexemeIds: [
      'de/noun/stadt',
      'de/noun/schule',
      'de/noun/straße',
      'de/noun/park',
      'de/noun/land',
      'de/noun/dorf',
      'de/noun/bahnhof',
      'de/noun/supermarkt',
      'de/noun/restaurant',
      'de/verb/gehen',
    ],
  },
  {
    id: 'de-pack-daily',
    lang: 'de',
    unitId: 'de-u2',
    title: { en: 'Daily life', it: 'Vita quotidiana' },
    lexemeIds: [
      'de/noun/tag',
      'de/noun/nacht',
      'de/noun/woche',
      'de/noun/jahr',
      'de/noun/zeitung',
      'de/verb/lernen',
      'de/verb/spielen',
      'de/verb/kaufen',
      'de/verb/sehen',
      'de/verb/hören',
      'de/verb/arbeiten',
      'de/verb/aufstehen',
    ],
  },
  {
    id: 'de-pack-house',
    lang: 'de',
    unitId: 'de-u3',
    title: { en: 'Around the house', it: 'In casa' },
    lexemeIds: [
      'de/noun/küche',
      'de/noun/bad',
      'de/noun/schlafzimmer',
      'de/noun/wohnzimmer',
      'de/noun/bett',
      'de/noun/garten',
      'de/noun/spiegel',
      'de/noun/lampe',
      'de/noun/tisch',
      'de/noun/stuhl',
      'de/noun/fenster',
      'de/noun/tür',
    ],
  },
  {
    id: 'de-pack-clothes',
    lang: 'de',
    unitId: 'de-u4',
    title: { en: 'Clothes & shopping', it: 'Vestiti e acquisti' },
    lexemeIds: [
      'de/noun/hemd',
      'de/noun/hose',
      'de/noun/kleid',
      'de/noun/rock',
      'de/noun/mantel',
      'de/noun/jacke',
      'de/noun/geld',
      'de/noun/preis',
      'de/noun/geschenk',
      'de/noun/schuh',
      'de/noun/tasche',
      'de/verb/kaufen',
    ],
  },
  {
    id: 'de-pack-routine',
    lang: 'de',
    unitId: 'de-u5',
    title: { en: 'Daily routine', it: 'La routine quotidiana' },
    lexemeIds: [
      'de/noun/frühstück',
      'de/noun/abendessen',
      'de/noun/morgen',
      'de/noun/abend',
      'de/noun/stunde',
      'de/noun/minute',
      'de/verb/aufstehen',
      'de/verb/schlafen',
      'de/verb/essen',
      'de/verb/trinken',
      'de/verb/arbeiten',
    ],
  },
  {
    id: 'de-pack-travel',
    lang: 'de',
    unitId: 'de-u6',
    title: { en: 'Travel', it: 'In viaggio' },
    lexemeIds: [
      'de/noun/reise',
      'de/noun/zug',
      'de/noun/flugzeug',
      'de/noun/flughafen',
      'de/noun/hotel',
      'de/noun/koffer',
      'de/noun/fahrkarte',
      'de/noun/meer',
      'de/noun/berg',
      'de/noun/sonne',
      'de/verb/fahren',
      'de/verb/gehen',
    ],
  },
]

export const DE_LEXEME_BY_KEY: Map<string, VocabLexeme> = new Map(
  [...DE_NOUNS, ...DE_VERBS].map((l) => [l.id.split('/').pop()!, l]),
)
