import type { VocabPack } from '../types'
import { DE_NOUNS } from './morphology/nouns'
import { DE_VERBS } from './morphology/verbs'
import { DE_ADJS } from './morphology/adjectives'
import type { VocabLexeme } from '../../engine/vocab'

export const DE_PACKS: VocabPack[] = [
  {
    id: 'de-pack-basics',
    lang: 'de',
    unitId: 'de-u1',
    title: { en: 'First words', it: 'Prime parole' },
    lexemeIds: [
      'de/noun/mann',
      'de/noun/frau',
      'de/noun/kind',
      'de/noun/haus',
      'de/noun/buch',
      'de/noun/wasser',
      'de/noun/kaffee',
      'de/noun/brot',
      'de/verb/machen',
      'de/verb/wohnen',
      'de/verb/kommen',
      'de/verb/trinken',
    ],
  },
  {
    id: 'de-pack-family',
    lang: 'de',
    unitId: 'de-u1',
    title: { en: 'Family', it: 'La famiglia' },
    lexemeIds: [
      'de/noun/familie',
      'de/noun/vater',
      'de/noun/mutter',
      'de/noun/bruder',
      'de/noun/schwester',
      'de/noun/sohn',
      'de/noun/tochter',
      'de/noun/junge',
      'de/noun/mädchen',
      'de/noun/freund',
    ],
  },
  {
    id: 'de-pack-food',
    lang: 'de',
    unitId: 'de-u2',
    title: { en: 'Food & drink', it: 'Cibo e bevande' },
    lexemeIds: [
      'de/noun/milch',
      'de/noun/käse',
      'de/noun/ei',
      'de/noun/fleisch',
      'de/noun/reis',
      'de/noun/obst',
      'de/noun/bier',
      'de/noun/wein',
      'de/noun/tee',
      'de/noun/saft',
      'de/noun/apfel',
      'de/verb/essen',
    ],
  },
  {
    id: 'de-pack-town',
    lang: 'de',
    unitId: 'de-u2',
    title: { en: 'Around town', it: 'In città' },
    lexemeIds: [
      'de/noun/stadt',
      'de/noun/schule',
      'de/noun/straße',
      'de/noun/park',
      'de/noun/land',
      'de/noun/dorf',
      'de/noun/bahnhof',
      'de/noun/supermarkt',
      'de/noun/restaurant',
      'de/verb/gehen',
    ],
  },
  {
    id: 'de-pack-daily',
    lang: 'de',
    unitId: 'de-u2',
    title: { en: 'Daily life', it: 'Vita quotidiana' },
    lexemeIds: [
      'de/noun/tag',
      'de/noun/nacht',
      'de/noun/woche',
      'de/noun/jahr',
      'de/noun/zeitung',
      'de/verb/lernen',
      'de/verb/spielen',
      'de/verb/kaufen',
      'de/verb/sehen',
      'de/verb/hören',
      'de/verb/arbeiten',
      'de/verb/aufstehen',
    ],
  },
  {
    id: 'de-pack-house',
    lang: 'de',
    unitId: 'de-u3',
    title: { en: 'Around the house', it: 'In casa' },
    lexemeIds: [
      'de/noun/küche',
      'de/noun/bad',
      'de/noun/schlafzimmer',
      'de/noun/wohnzimmer',
      'de/noun/bett',
      'de/noun/garten',
      'de/noun/spiegel',
      'de/noun/lampe',
      'de/noun/tisch',
      'de/noun/stuhl',
      'de/noun/fenster',
      'de/noun/tür',
    ],
  },
  {
    id: 'de-pack-clothes',
    lang: 'de',
    unitId: 'de-u4',
    title: { en: 'Clothes & shopping', it: 'Vestiti e acquisti' },
    lexemeIds: [
      'de/noun/hemd',
      'de/noun/hose',
      'de/noun/kleid',
      'de/noun/rock',
      'de/noun/mantel',
      'de/noun/jacke',
      'de/noun/geld',
      'de/noun/preis',
      'de/noun/geschenk',
      'de/noun/schuh',
      'de/noun/tasche',
      'de/verb/kaufen',
    ],
  },
  {
    id: 'de-pack-routine',
    lang: 'de',
    unitId: 'de-u5',
    title: { en: 'Daily routine', it: 'La routine quotidiana' },
    lexemeIds: [
      'de/noun/frühstück',
      'de/noun/abendessen',
      'de/noun/morgen',
      'de/noun/abend',
      'de/noun/stunde',
      'de/noun/minute',
      'de/verb/aufstehen',
      'de/verb/schlafen',
      'de/verb/essen',
      'de/verb/trinken',
      'de/verb/arbeiten',
    ],
  },
  {
    id: 'de-pack-travel',
    lang: 'de',
    unitId: 'de-u6',
    title: { en: 'Travel', it: 'In viaggio' },
    lexemeIds: [
      'de/noun/reise',
      'de/noun/zug',
      'de/noun/flugzeug',
      'de/noun/flughafen',
      'de/noun/hotel',
      'de/noun/koffer',
      'de/noun/fahrkarte',
      'de/noun/meer',
      'de/noun/berg',
      'de/noun/sonne',
      'de/verb/fahren',
      'de/verb/gehen',
    ],
  },
  {
    id: 'de-pack-body',
    lang: 'de',
    unitId: 'de-u5',
    title: { en: 'Body & health', it: 'Corpo e salute' },
    lexemeIds: [
      'de/noun/kopf',
      'de/noun/auge',
      'de/noun/hand',
      'de/noun/fuß',
      'de/noun/arm',
      'de/noun/bein',
      'de/noun/herz',
      'de/noun/bauch',
      'de/noun/rücken',
      'de/noun/zahn',
      'de/noun/mund',
      'de/noun/nase',
      'de/noun/ohr',
      'de/noun/haar',
      'de/noun/krankenhaus',
    ],
  },
  {
    id: 'de-pack-feelings',
    lang: 'de',
    unitId: 'de-u4',
    title: { en: 'Feelings', it: 'Sentimenti' },
    lexemeIds: [
      'de/noun/angst',
      'de/noun/freude',
      'de/noun/liebe',
      'de/noun/problem',
      'de/noun/frage',
      'de/noun/antwort',
      'de/noun/wahrheit',
      'de/noun/glück',
      'de/noun/hilfe',
      'de/noun/idee',
      'de/noun/traum',
      'de/adj/traurig',
      'de/adj/glücklich',
      'de/adj/nervös',
      'de/adj/ruhig',
    ],
  },
  {
    id: 'de-pack-nature',
    lang: 'de',
    unitId: 'de-u6',
    title: { en: 'Weather & nature', it: 'Tempo e natura' },
    lexemeIds: [
      'de/noun/himmel',
      'de/noun/stern',
      'de/noun/mond',
      'de/noun/regen',
      'de/noun/schnee',
      'de/noun/wind',
      'de/noun/wolke',
      'de/noun/baum',
      'de/noun/blume',
      'de/noun/fluss',
      'de/noun/wald',
      'de/noun/wetter',
      'de/noun/see',
      'de/verb/regnen',
      'de/verb/schneien',
    ],
  },
  {
    id: 'de-pack-work',
    lang: 'de',
    unitId: 'de-u3',
    title: { en: 'Work & school', it: 'Lavoro e scuola' },
    lexemeIds: [
      'de/noun/büro',
      'de/noun/firma',
      'de/noun/chef',
      'de/noun/chefin',
      'de/noun/besprechung',
      'de/noun/email',
      'de/noun/brief',
      'de/noun/papier',
      'de/noun/prüfung',
      'de/noun/klasse',
      'de/noun/universität',
      'de/noun/wort',
      'de/noun/satz',
      'de/noun/hausaufgabe',
      'de/noun/beruf',
    ],
  },
  {
    id: 'de-pack-tech',
    lang: 'de',
    unitId: 'de-u4',
    title: { en: 'Tech & media', it: 'Tecnologia e media' },
    lexemeIds: [
      'de/noun/internet',
      'de/noun/film',
      'de/noun/musik',
      'de/noun/lied',
      'de/noun/radio',
      'de/noun/fernsehen',
      'de/noun/foto',
      'de/noun/nachricht',
      'de/noun/spiel',
      'de/noun/netz',
      'de/noun/computer',
      'de/noun/handy',
      'de/noun/telefon',
      'de/verb/anrufen',
    ],
  },
  {
    id: 'de-pack-city',
    lang: 'de',
    unitId: 'de-u6',
    title: { en: 'In the city', it: 'In città 2' },
    lexemeIds: [
      'de/noun/platz',
      'de/noun/kirche',
      'de/noun/museum',
      'de/noun/bank',
      'de/noun/brücke',
      'de/noun/ecke',
      'de/noun/eingang',
      'de/noun/ausgang',
      'de/noun/ticket',
      'de/noun/ubahn',
      'de/verb/suchen',
      'de/verb/finden',
    ],
  },
  {
    id: 'de-pack-food2',
    lang: 'de',
    unitId: 'de-u2',
    title: { en: 'More food', it: 'Altro cibo' },
    lexemeIds: [
      'de/noun/suppe',
      'de/noun/salat',
      'de/noun/hähnchen',
      'de/noun/tomate',
      'de/noun/kartoffel',
      'de/noun/zucker',
      'de/noun/salz',
      'de/noun/öl',
      'de/noun/nachtisch',
      'de/noun/eis',
      'de/noun/kuchen',
      'de/noun/butter',
    ],
  },
  {
    id: 'de-pack-time',
    lang: 'de',
    unitId: 'de-u7',
    title: { en: 'Days & seasons', it: 'Giorni e stagioni' },
    lexemeIds: [
      'de/noun/montag',
      'de/noun/dienstag',
      'de/noun/mittwoch',
      'de/noun/donnerstag',
      'de/noun/freitag',
      'de/noun/samstag',
      'de/noun/sonntag',
      'de/noun/monat',
      'de/noun/wochenende',
      'de/noun/frühling',
      'de/noun/sommer',
      'de/noun/herbst',
      'de/noun/winter',
      'de/noun/geburtstag',
      'de/noun/urlaub',
    ],
  },
  {
    id: 'de-pack-house2',
    lang: 'de',
    unitId: 'de-u3',
    title: { en: 'Home 2', it: 'In casa 2' },
    lexemeIds: [
      'de/noun/schlüssel',
      'de/noun/treppe',
      'de/noun/aufzug',
      'de/noun/wand',
      'de/noun/boden',
      'de/noun/decke',
      'de/noun/ofen',
      'de/noun/kühlschrank',
      'de/noun/waschmaschine',
      'de/noun/handtuch',
      'de/noun/seife',
      'de/noun/kissen',
      'de/noun/nachbar',
      'de/noun/nachbarin',
      'de/verb/bauen',
    ],
  },
  {
    id: 'de-pack-restaurant',
    lang: 'de',
    unitId: 'de-u4',
    title: { en: 'Eating out', it: 'Al ristorante' },
    lexemeIds: [
      'de/noun/kellner',
      'de/noun/kellnerin',
      'de/noun/gast',
      'de/noun/speisekarte',
      'de/noun/rechnung',
      'de/noun/trinkgeld',
      'de/noun/kasse',
      'de/noun/karte',
      'de/noun/bargeld',
      'de/noun/bäckerei',
      'de/noun/metzgerei',
      'de/verb/probieren',
      'de/verb/zahlen',
      'de/adj/süß',
      'de/adj/scharf',
    ],
  },
  {
    id: 'de-pack-school',
    lang: 'de',
    unitId: 'de-u5',
    title: { en: 'Learning German', it: 'Imparare il tedesco' },
    lexemeIds: [
      'de/noun/grammatik',
      'de/noun/übung',
      'de/noun/fehler',
      'de/noun/niveau',
      'de/noun/kurs',
      'de/noun/seite',
      'de/noun/heft',
      'de/noun/kuli',
      'de/noun/bleistift',
      'de/noun/bedeutung',
      'de/noun/sprache',
      'de/verb/üben',
      'de/verb/wiederholen',
      'de/verb/versuchen',
    ],
  },
  {
    id: 'de-pack-animals',
    lang: 'de',
    unitId: 'de-u6',
    title: { en: 'Animals & nature 2', it: 'Animali e natura 2' },
    lexemeIds: [
      'de/noun/tier',
      'de/noun/vogel',
      'de/noun/hund',
      'de/noun/katze',
      'de/noun/pferd',
      'de/noun/fisch',
      'de/noun/kuh',
      'de/noun/insel',
      'de/noun/stein',
      'de/noun/gras',
      'de/noun/blatt',
      'de/noun/strand',
      'de/adj/tief',
      'de/verb/fallen',
    ],
  },
  {
    id: 'de-pack-travel2',
    lang: 'de',
    unitId: 'de-u7',
    title: { en: 'Travel 2', it: 'In viaggio 2' },
    lexemeIds: [
      'de/noun/pass',
      'de/noun/grenze',
      'de/noun/reservierung',
      'de/noun/zimmer',
      'de/noun/ankunft',
      'de/noun/verspätung',
      'de/noun/gleis',
      'de/noun/flug',
      'de/noun/gepäck',
      'de/noun/reiseführer',
      'de/noun/landkarte',
      'de/noun/tourist',
      'de/verb/reisen',
      'de/verb/bleiben',
      'de/adj/romantisch',
    ],
  },
  {
    id: 'de-pack-essentials',
    lang: 'de',
    unitId: 'de-u7',
    title: { en: 'Essential words', it: 'Parole essenziali' },
    lexemeIds: [
      'de/noun/sache',
      'de/noun/mal',
      'de/noun/leben',
      'de/noun/welt',
      'de/noun/geschichte',
      'de/noun/licht',
      'de/noun/feuer',
      'de/noun/luft',
      'de/noun/lärm',
      'de/noun/geruch',
      'de/noun/farbe',
      'de/noun/form',
      'de/noun/teil',
      'de/noun/ende',
      'de/noun/anfang',
    ],
  },
]

// adjectives first: on a lemma-key collision (der Arm vs. arm) the noun must win,
// and Map keeps the LAST entry for a duplicate key
export const DE_LEXEME_BY_KEY: Map<string, VocabLexeme> = new Map(
  [...DE_ADJS, ...DE_NOUNS, ...DE_VERBS].map((l) => [l.id.split('/').pop()!, l]),
)
